### PR TITLE
Fix helm dep list reporting wrong status

### LINKED ISSUE #2056: helm dep list report missing for subcharts downloaded with version matching
If a subchart's version is defined implicitly, `helm dep list` would still report missing after a subchart is downloaded via `helm dep update` or `helm dep build`. This is because `helm dep list` does not consider implicit version when checking existence of a subchart.

Implicit version is like: 0.5.x, >=0.5.0, etc. 

A fix to this could be loading version information from requirements.lock instead of requirements.yaml.

### PR DESCRIPTION
**Pull request by qwangqw**
Version matching is used for checking status of subcharts.
closes: #2056

### CODE REVIEW

File: cmd/helm/dependency_test.go [hunk 1]
```diff
@@ -40,9 +40,12 @@ func TestDependencyListCmd(t *testing.T) {
 			expect: "WARNING: no requirements at ",
 		},
 		{
-			name:   "Requirements in chart dir",
-			args:   []string{"testdata/testcharts/reqtest"},
-			expect: "NAME        \tVERSION\tREPOSITORY                \tSTATUS  \nreqsubchart \t0.1.0  \thttps://example.com/charts\tunpacked\nreqsubchart2\t0.2.0  \thttps://example.com/charts\tunpacked\n",
+			name: "Requirements in chart dir",
+			args: []string{"testdata/testcharts/reqtest"},
+			expect: "NAME        \tVERSION\tREPOSITORY                \tSTATUS  \n" +
```
Comment (technosophos) [inline cmd/helm/dependency_test.go]: This is much easier to read. Thanks.

**Review by technosophos — APPROVED** [review]
