### PR TITLE
fix(helm): refactor 'helm update' to match new style

### LINKED ISSUE #696: helm update needs tests

### PR DESCRIPTION
**Pull request by technosophos**
And add tests.

Closes #696

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/helm/1107)

### CODE REVIEW

File: cmd/helm/update.go [hunk 1]
```diff
@@ -19,30 +19,47 @@ package main
...
+	cmd := &cobra.Command{
+		Use:     "update",
+		Aliases: []string{"up"},
+		Short:   "update information on available charts in the chart repositories",
+		Long:    updateDesc,
+		RunE: func(cmd *cobra.Command, args []string) error {
+			return u.run()
+		},
+	}
+	cmd.Flags().BoolVar(&u.verbose, "verbose", false, "verbose error messages")
```
Comment (adamreese) [inline cmd/helm/update.go]: Why not use the global `--debug` ?

Comment (michelleN) [inline cmd/helm/update.go]: +1
