### PR TITLE
validate release name during install

### LINKED ISSUE #9339: Helm does not validate release name during install, but validates it during uninstall
Output of `helm version`:
`helm.sh/helm/v3 v3.5.0` (from `go.mod`)

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Local

Scenario:

1. While writing a UT to test `helm install` and `helm uninstall` from my Go program, I repeatedly hit the error: `'uninstall: Release name is invalid: testNamespace-chart-name-id1-id2`.

2. The install went fine with no errors.

3. Looking at the source for `helm uninstall`, I see [here](https://github.com/helm/helm/blob/master/pkg/action/uninstall.go#L66-L68) that Helm validates the release name to [conform to the regex](https://github.com/helm/helm/blob/master/pkg/chartutil/validate_name.go#L30) `[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*`.

4. A similar check is present during an `upgrade` and `rollback`, but absent during an `install`.

5. I removed the camel-casing in my release name and things work fine.

Expected behaviour:

If the release name is invalid, an error should be encountered immediately while installing the release and not while uninstalling it.

### PR DESCRIPTION
**Pull request by mengjiao-liu**
**What this PR does / why we need it**:
Helm validate release name during install

fix #9339

### CODE REVIEW

**Comment by mengjiao-liu** [comment]
This is the first time I submitted PR at helm.
Can you review the code ？ @bacongobbler @adamreese

**Review by yxxhero — APPROVED** [review]
LGTM
@hickeyma @bacongobbler WDYT?

File: pkg/action/install.go [hunk 1]
```diff
@@ -410,14 +403,10 @@ func (i *Install) failRelease(rel *release.Release, err error) (*release.Release
...
 func (i *Install) availableName() error {
 	start := i.ReleaseName
-	if start == "" {
-		return errors.New("name is required")
-	}
 
-	if len(start) > releaseNameMaxLen {
-		return errors.Errorf("release name %q exceeds max length of %d", start, releaseNameMaxLen)
+	if err := chartutil.ValidateReleaseName(start); err != nil {
+		return errors.Errorf("install: Release name is invalid: %s, err: %s", start, err)
```
Comment (hickeyma) [inline pkg/action/install.go:408]: Can you try changing the error return:
return errors.Errorf("install: Release name is invalid: %s, err: %s", start, err)

to the following: return errors.Wrapf(err, "release name %q is invalid", start)

It would follow how we wrap error strings usually.

File: pkg/chartutil/validate_name.go [hunk 2]
```diff
@@ -37,7 +37,7 @@ var validName = regexp.MustCompile(`^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-
 
 var (
 	// errMissingName indicates that a release (name) was not provided.
-	errMissingName = errors.New("no name provided")
+	errMissingName = errors.New("name is required")
```
Comment (hickeyma) [inline pkg/chartutil/validate_name.go:40]: I would not change this as this is not the error but what is required.

File: pkg/chartutil/validate_name.go [hunk 3]
```diff
@@ -53,6 +53,9 @@ var (
 
 const (
 	// maxNameLen is the maximum length Helm allows for a release name
+	// As of Kubernetes 1.4, the max limit on a name is 63 chars. We reserve 10 for
+	// charts to add data. Effectively, that gives us 53 chars.
+	// See https://github.com/helm/helm/issues/1528
```
Comment (hickeyma) [inline pkg/chartutil/validate_name.go:58]: I would replace this comment with the following as its more accurate now:

```go
\\ According to the Kubernetes docs (https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#rfc-1035-label-names)
\\ some resource names have a max length of 63 characters while others have a max
\\ length of 253 characters. As we cannot be sure the resources used in a chart, we
\\ therefore need to limit it to 63 chars and reserve 10 chars for additional part to name
\\ of the resource. The reason is that chart maintainers can use release name as part of
\\ the resource name (and some additional chars).

```

**Review by hickeyma — CHANGES_REQUESTED** [review]
Thanks for pushing PR @mengjiao-liu. Some small comments to look at.

File: pkg/action/install.go (hunk 1 above)
Comment (mengjiao-liu) [reply pkg/action/install.go]: Thanks for your advice, it has been updated.

File: pkg/chartutil/validate_name.go (hunk 2 above)
Comment (mengjiao-liu) [reply pkg/chartutil/validate_name.go]: Yes, then there is no need to change, it has been restored.

File: pkg/chartutil/validate_name.go (hunk 3 above)
Comment (mengjiao-liu) [reply pkg/chartutil/validate_name.go]: Okay, updated comments.

**Comment by mengjiao-liu** [comment]
Request review again.  Thanks! @yxxhero @hickeyma

File: pkg/action/install.go (hunk 1 above)
Comment (hickeyma) [reply pkg/action/install.go]: Looking at the error returned again during manual testing, do you mind changing to the following as it would read better:

return errors.Wrapf(err, "release name %q", start)

**Review by hickeyma — CHANGES_REQUESTED** [review]
Nearly there. One small change to error message.

Also, one of the unit tests is failing because test was added after the initial push of the PR. It is using this golden file: https://github.com/helm/helm/blob/main/cmd/helm/testdata/output/template-with-kube-version.txt and needs to be updated. You will need to rebase to pick up the latest from main and then change the file.

**Comment by mengjiao-liu** [comment]
> Nearly there. One small change to error message.
> 
> Also, one of the unit tests is failing because test was added after the initial push of the PR. It is using this golden file: https://github.com/helm/helm/blob/main/cmd/helm/testdata/output/template-with-kube-version.txt and needs to be updated. You will need to rebase to pick up the latest from main and then change the file.

Thanks for catch！Rebased and updated.

File: pkg/action/install.go (hunk 1 above)
Comment (hickeyma) [reply pkg/action/install.go]: @mengjiao-liu  can you remove "is invalid""? ^^

Comment (mengjiao-liu) [reply pkg/action/install.go]: Ok, updated.

**Review by hickeyma — APPROVED** [review]
LGTM, thanks @mengjiao-liu.

Needs another core maintainer to approve before merging.

**Comment by mengjiao-liu** [comment]
ping @adamreese @bacongobbler @jdolitsky 
for approval

**Review by yxxhero — APPROVED** [review]
LGTM

**Comment by mengjiao-liu** [comment]
ping @mattfarina @bacongobbler

**Comment by mengjiao-liu** [comment]
No changes, just too long ago, sync with upstream main branch.

**Comment by mattfarina** [comment]
I've tested both and can see the difference. For example, see the below output...

```sh
❯ helm-pr install fooTestName ./footestname
Error: INSTALLATION FAILED: release name "fooTestName": invalid release name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 53

❯ helm install fooTestName ./footestname
Error: INSTALLATION FAILED: create: failed to create: Secret "sh.helm.release.v1.fooTestName.v1" is invalid: metadata.name: Invalid value: "sh.helm.release.v1.fooTestName.v1": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**Review by mattfarina — APPROVED** [review]
