### PR TITLE
fix: Ignore absolute path when RepoUrl is provided

### LINKED ISSUE #7862: Bug: `--repo` should takes precedence over local folder
Using local chart when a `--repo` flag is provided doesn't make sense, the assumption in [LocateChart](https://github.com/helm/helm/blob/c20d06d930aad1862b73aebdfbf36e1f00e75d28/pkg/action/install.go#L726-L795) function is not correct in this case,

Is it possible to ignore the local folders when `--repo` is provided?

Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

### PR DESCRIPTION
**Pull request by TerryHowe**
**What this PR does / why we need it**:

Ignore absolute path when RepoUrl is provided

Closes: https://github.com/helm/helm/issues/7862

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

File: pkg/action/install.go [hunk 1]
```diff
@@ -817,20 +817,26 @@ func (c *ChartPathOptions) LocateChart(name string, settings *cli.EnvSettings) (
...
+			if err != nil {
+				return abs, err
+			}
+			if c.Verify {
+				if _, err := downloader.VerifyChart(abs, abs+".prov", c.Keyring); err != nil {
+					return "", err
+				}
+				return abs, nil
 			}
+			if filepath.IsAbs(name) || strings.HasPrefix(name, ".") {
```
Comment (gjenkins8) [inline pkg/action/install.go]: Why is it wanted/needed to check if name is an absolute or hidden file here?

```
helm create foo
./bin/helm template `realpath foo`
Error: path "/Users/gjenkins8/Source/helm/helm/foo" not found
```

This seems to be wrong behavior?

Comment (TerryHowe) [reply pkg/action/install.go]: Bad cherry pick I think

**Review by gjenkins8 — APPROVED** [review]

**Review by joejulian — APPROVED** [review]
