### PR TITLE
Fix flaky TestDedupeRepos

### LINKED ISSUE #30573: Test flake on TestDedupeRepos
Reproducible steps - 
1. clone main
2. cd `pkg/downloads` 
3. `go test -run TestDedupeRepos -count=1` <- this should pass
4. `go test -run TestDedupeRepos -count=100` <- this fails pass

Seeing this flake on PR #13617, I have not looked into the cause at all

```go
--- FAIL: TestDedupeRepos (0.00s)
    --- FAIL: TestDedupeRepos/no_duplicates (0.00s)
        manager_test.go:661: received:
            [{"name":"","url":"https://example.com/charts2","username":"","password":"","certFile":"","keyFile":"","caFile":"","insecure_skip_tls_verify":false,"pass_credentials_all":false} {"name":"","url":"https://example.com/charts","username":"","password":"","certFile":"","keyFile":"","caFile":"","insecure_skip_tls_verify":false,"pass_credentials_all":false}]
            want:
            [{"name":"","url":"https://example.com/charts","username":"","password":"","certFile":"","keyFile":"","caFile":"","insecure_skip_tls_verify":false,"pass_credentials_all":false} {"name":"","url":"https://example.com/charts2","username":"","password":"","certFile":"","keyFile":"","caFile":"","insecure_skip_tls_verify":false,"pass_credentials_all":false}]
---... happens more...---
--- FAIL: TestDedupeRepos (0.00s)
    --- FAIL: TestDedupeRepos/no_duplicates (0.00s)
        manager_test.go:661: received:
           <same-output-again>
FAIL
exit status 1
```

### PR DESCRIPTION
**Pull request by felipecrs**
**What this PR does / why we need it**:

Closes #30573

**Special notes for your reviewer**:

~Sorry, I'm not a golanger. The solution doesn't seem the cleanest, but it's the cleanest I could come up with. I'm open to suggestions.~

As suggested by @gjenkins8 [here](https://github.com/helm/helm/pull/30576#discussion_r1966862055).

### CODE REVIEW

File: pkg/downloader/manager_test.go [hunk 1]
```diff
@@ -657,7 +658,17 @@ func TestDedupeRepos(t *testing.T) {
...
+			sort.Slice(got, func(i, j int) bool {
+				return got[i].URL < got[j].URL
+			})
+			sort.Slice(tt.want, func(i, j int) bool {
+				return tt.want[i].URL < tt.want[j].URL
+			})
+
+			if !reflect.DeepEqual(got, tt.want) {
 				t.Errorf("received:\n%v\nwant:\n%v", got, tt.want)
 			}
```
Comment (gjenkins8) [inline pkg/downloader/manager_test.go:673]: try: [assert.ElementsMatch](https://pkg.go.dev/github.com/stretchr/testify/assert#ElementsMatch)

```suggestion
			assert.ElementsMatch(t, tt.want, got)
```

Comment (felipecrs) [reply pkg/downloader/manager_test.go]: That works, but I had to add `github.com/tj/assert` to the list of dependencies. If that's undesirable, I can revert.

**Review by gjenkins8 — COMMENTED** [review]
Thanks for the speedy fix PR. One suggestion to use a helper from https://github.com/stretchr/testify?tab=readme-ov-file#assert-package 

This is frequently used (including in other places in Helm) for unit tests in golang, to the point where it is close to being idiomatic (I'm sure some people would disagree with this statement)

File: pkg/downloader/manager_test.go (hunk 1 above)
Comment (gjenkins8) [reply pkg/downloader/manager_test.go]: ah, I was just writing https://github.com/helm/helm/pull/30576#pullrequestreview-2635723822

 it should be: `"github.com/stretchr/testify/assert"`

File: pkg/downloader/manager_test.go [hunk 2]
```diff
@@ -22,6 +22,7 @@ import (
 	"reflect"
 	"testing"
 
+	"github.com/tj/assert"
```
Comment (gjenkins8) [inline pkg/downloader/manager_test.go:25]:
```suggestion
	 "github.com/stretchr/testify/assert"
```

Comment (felipecrs) [reply pkg/downloader/manager_test.go]: Fixed now.

File: go.mod [hunk 3]
```diff
@@ -133,6 +133,7 @@ require (
 	github.com/shopspring/decimal v1.4.0 // indirect
 	github.com/sirupsen/logrus v1.9.3 // indirect
 	github.com/spf13/cast v1.7.0 // indirect
+	github.com/tj/assert v0.0.3
```
Comment (gjenkins8) [inline go.mod:136]:
```suggestion
```

**Review by gjenkins8 — APPROVED** [review]
