### PR TITLE
Fix : No repository is not an error,use the helm repo list command ,if there is no repository,it should not be an error #30606

### LINKED ISSUE #30606: No repository is not an error,use the helm repo list command ,if there is no repository,it should not be an error
helm:v3.17.1
1.No repository is in my local computer. After using the helm repo list command, it prompts "Error: no repositories to show"

Image
2.Expected Results  After using the helm repo list command, it prompts "no repositories to show"

### PR DESCRIPTION
**Pull request by ayushontop**
**What this PR does / why we need it**:
Issue - No repository is not an error,use the helm repo list command ,if there is no repository,it should not be an error closes 
#30606 
**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by ayushontop** [comment]
@gjenkins8  let me know if changes needed, thanks

File: pkg/cmd/repo_list.go [hunk 1]
```diff
@@ -40,7 +39,8 @@ func newRepoListCmd(out io.Writer) *cobra.Command {
 		RunE: func(_ *cobra.Command, _ []string) error {
 			f, _ := repo.LoadFile(settings.RepositoryConfig)
 			if len(f.Repositories) == 0 && outfmt != output.JSON && outfmt != output.YAML {
-				return errors.New("no repositories to show")
+				fmt.Fprintln(out, "no repositories to show")
```
Comment (TerryHowe) [inline pkg/cmd/repo_list.go:42]: I would think this would go to stderr so it isn't interpreted as a repo

Comment (ayushontop) [reply pkg/cmd/repo_list.go]: thanks for review, I you mean that it might go to stdout and break the JSON pipeline, just did a change let me know if there are more issues

Comment (TerryHowe) [reply pkg/cmd/repo_list.go]: That makes sense to me. We'll see what @gjenkins8 thinks

**Review by TerryHowe — APPROVED** [review]
/lgtm

File: pkg/cmd/repo_list.go [hunk 2]
```diff
@@ -40,7 +39,8 @@ func newRepoListCmd(out io.Writer) *cobra.Command {
 		RunE: func(_ *cobra.Command, _ []string) error {
 			f, _ := repo.LoadFile(settings.RepositoryConfig)
 			if len(f.Repositories) == 0 && outfmt != output.JSON && outfmt != output.YAML {
-				return errors.New("no repositories to show")
+				fmt.Fprintln(cmd.ErrOrStderr(), "no repositories to show")
```
[the remark this answers is not in the document]
Comment (TerryHowe) [reply pkg/cmd/repo_list.go:42]: If you were piping the output somewhere, `no repositoryies to show` would be processed as a repo

**Review by godhanipayal — APPROVED** [review]
lgtm

**Comment by ayushontop** [comment]
Hello @gjenkins8 any more changes to do ?

**Review by gjenkins8 — DISMISSED** [review]

File: pkg/cmd/repo_list.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (gjenkins8) [reply pkg/cmd/repo_list.go:42]: I couldn't come up with a convincing argument for/against either way. Lets go with `stderr` as proposed. Will need to fix CI issue (cmd isn't defined)

File: pkg/cmd/repo_list.go [hunk 3]
```diff
@@ -40,7 +39,8 @@ func newRepoListCmd(out io.Writer) *cobra.Command {
 		RunE: func(_ *cobra.Command, _ []string) error {
```
Comment (TerryHowe) [inline pkg/cmd/repo_list.go:39]:
```suggestion
		RunE: func(cmd *cobra.Command, _ []string) error {
```

**Review by TerryHowe — CHANGES_REQUESTED** [review]

**Comment by ayushontop** [comment]
@gjenkins8  now it should pass the ci pipeline

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Review by gjenkins8 — APPROVED** [review]

**Review by mattfarina — APPROVED** [review]
lgtm
