### PR TITLE
fix: improve logging & safety of statefulSetReady

### LINKED ISSUE #10163: Helm does not wait for Statefulset to be ready after upgrade
Helm does not wait for Statefulset to be ready after upgrade to 3.6.3 from 3.3.1. I have tried using versions:
* 3.7.0 (does not work),
* 3.6.3 (does not work),
* 3.5.4 (works!),
* 3.3.1 (works!).

It seems that this behavior was introduced with: https://github.com/helm/helm/commit/98d98369ed9abcaec9b75352e07dd6f759a8804f

Helm 3.7.0 behavior - unexpected:

```
helm upgrade --install --reset-values XXX chart --version X.Y.Z --wait --timeout 900s --create-namespace --namespace dummy --values /tmp/helmfile351904154/XXX-values-6fd57cf55 ... --history-max 10 --debug
helm:whTHc> history.go:56: [debug] getting history for release XXX
helm:whTHc> upgrade.go:139: [debug] preparing upgrade for XXX
helm:whTHc> upgrade.go:488: [debug] resetting values to the chart's original version
helm:whTHc> upgrade.go:147: [debug] performing update for XXX
helm:whTHc> upgrade.go:319: [debug] creating upgraded release for XXX
helm:whTHc> client.go:218: [debug] checking 4 resources for changes
helm:whTHc> client.go:501: [debug] Looks like there are no changes for ConfigMap "XXX"
helm:whTHc> client.go:501: [debug] Looks like there are no changes for Service "XXX"
helm:whTHc> wait.go:48: [debug] beginning wait for 4 resources with timeout of 15m0s
helm:whTHc> upgrade.go:154: [debug] updating status for upgraded release for XXX
helm:whTHc> Release "XXX" has been upgraded. Happy Helming!
NAME: XXX
...
```

Helm 3.5.4 behavior - expected:
```
exec: helm upgrade --install --reset-values XXX chart --version X.Y.Z --wait --timeout 900s --create-namespace --namespace dummy --values /tmp/helmfile549477625/XXX-values-68c7579fb5 ... --history-max 10 --debug
helm:whTHc> history.go:56: [debug] getting history for release XXX
helm:whTHc> upgrade.go:123: [debug] preparing upgrade for XXX
helm:whTHc> upgrade.go:437: [debug] resetting values to the chart's original version
helm:whTHc> upgrade.go:131: [debug] performing update for XXX
helm:whTHc> upgrade.go:303: [debug] creating upgraded release for XXX
helm:whTHc> client.go:201: [debug] checking 4 resources for changes
helm:whTHc> client.go:464: [debug] Looks like there are no changes for PodDisruptionBudget "XXX"
helm:whTHc> client.go:464: [debug] Looks like there are no changes for ConfigMap "XXX"
helm:whTHc> client.go:464: [debug] Looks like there are no changes for Service "XXX"
helm:whTHc> wait.go:53: [debug] beginning wait for 4 resources with timeout of 15m0s
helm:whTHc> wait.go:348: [debug] StatefulSet is not ready: dummy/XXX. 0 out of 2 expected pods have been scheduled
helm:whTHc> wait.go:348: [debug] StatefulSet is not ready: dummy/XXX. 0 out of 2 expected pods have been scheduled
helm:whTHc> wait.go:348: [debug] StatefulSet is not ready: dummy/XXX. 0 out of 2 expected pods have been scheduled
helm:whTHc> wait.go:348: [debug] StatefulSet is not ready: dummy/XXX. 1 out of 2 expected pods have been scheduled
helm:whTHc> wait.go:348: [debug] StatefulSet is not ready: dummy/XXX. 1 out of 2 expected pods have been scheduled
...
helm:whTHc> wait.go:353: [debug] StatefulSet is not ready: dummy/XXX. 1 out of 2 expected pods are ready
helm:whTHc> wait.go:353: [debug] StatefulSet is not ready: dummy/XXX. 1 out of 2 expected pods are ready
...
helm:whTHc> upgrade.go:138: [debug] updating status for upgraded release for XXX
helm:whTHc> Release "XXX" has been upgraded. Happy Helming!
NAME: XXX
```

It's weird because I have similar releases of this chart where `--wait` works as expected. I do not know if it is relevant but release XXX was converted from Helm 2 release using 2to3 plugin a while ago.

Output of `helm version`:
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10", GitCommit:"8152330a2b6ca3621196e62966ef761b8f5a61bb", GitTreeState:"clean", BuildDate:"2021-08-11T18:06:15Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-15T20:56:38Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS+Kops

### PR DESCRIPTION
**Pull request by dnwe**
**What this PR does / why we need it**:

Confirm that the current and updated revision numbers also match as part of the readiness check.

Also add additional logging around the sts transitions from non-ready to ready.

Fixes: #10163

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by jonny08152 — APPROVED** [review]
This fix works perfectly. Waiting for StatefulSet rollout to finish now works as it should.

**Comment by libsamek** [comment]
Hey, any update on this getting merged?

**Review by hickeyma — COMMENTED** [review]
@dnwe Would it be possible to provide a unit test to replicate the issue?

**Comment by hickeyma** [comment]
@mattfarina @marckhouzam Looking at the [backwards compatibility HIP](https://github.com/helm/community/blob/main/hips/hip-0004.md), there doesn't seem any rule that new messages can't be added as is the case in this PR. There is a mention alright in [Open Issues](https://github.com/helm/community/blob/main/hips/hip-0004.md#open-issues). Are these message backward compatible to you?

**Comment by dnwe** [comment]
@mattfarina / @marckhouzam any thoughts on Martin's [question](https://github.com/helm/helm/pull/10622#issuecomment-1141187184) above? It would be great if we could get this fix into a release

**Comment by mattfarina** [comment]
@dnwe @hickeyma It should be ok to add these messages. In the case of the helm client, these are debug output that is additive. Others using the SDK can add their own loggers but it would be additional logging output in that case.

**Comment by dnwe** [comment]
Thanks @mattfarina — @hickeyma this should be ready for re-review

File: pkg/action/upgrade.go [hunk 1]
```diff
@@ -391,6 +391,9 @@ func (u *Upgrade) releasingUpgrade(c chan<- resultMessage, upgradedRelease *rele
 	}
 
 	if u.Wait {
+		u.cfg.Log(
+			"waiting for release %s resources (created=%d, updated=%d, deleted=%d)",
```
Comment (mattfarina) [inline pkg/action/upgrade.go:395]: I only have one nit (otherwise it looks good). Here you have an `=` between the thing being counted and the count. I was looking elsewhere in our log message and I didn't see a case where an `=` is being used. Instead there is either a space or `: ` (colon and a space). For the sake of consistency, can you switch to one of these.

Comment (hickeyma) [reply pkg/action/upgrade.go:395]: Nit but good point for consistency

**Comment by dnwe** [comment]
Rebased and updated log line as requested by @mattfarina

**Review by mattfarina — APPROVED** [review]

**Review by scottrigby — APPROVED** [review]
This code looks great, good tests, and works well! 👏 

Beyond automated testing, did manual test. For future ref, here's what I did:

1. `kind create cluster`
2. `helm install my-mariadb bitnami/mariadb --version 11.0.0`
    - Why this version? Looked on artifact hub for a good chart containing StatefulSet template ([bitnami/mariadb](https://artifacthub.io/packages/helm/bitnami/mariadb)). Used artifacthub template browser to check which version had a change in that resource. 11.0.0 -> current does, so just doing that
3. Test the upgrade
    ```
    # Checkout PR branch and build (ya know)
    $ gh pr checkout 10622
    $ make

    $ export MARIADB_ROOT_PASSWORD=$(kubectl get secret --namespace "default" my-mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 -d)
    $ ./bin/helm upgrade --namespace default my-mariadb bitnami/mariadb --set auth.rootPassword=$ROOT_PASSWORD
    ```
    - Note this charts output says we need a specific `--set` command on upgrade
    - Since we don't pass `--version` helm chooses the most recent, `11.0.13`
4. output is as expected:
    ```
    upgrade.go:394: [debug] waiting for release my-mariadb resources (created: 0 updated: 5  deleted: 0)
    wait.go:48: [debug] beginning wait for 5 resources with timeout of 5m0s
    ready.go:362: [debug] StatefulSet is not ready: default/my-mariadb. update has not yet been observed
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:393: [debug] StatefulSet is not ready: default/my-mariadb. 0 out of 1 expected pods are ready
    ready.go:402: [debug] StatefulSet is ready: default/my-mariadb. 1 out of 1 expected pods are ready
    upgrade.go:157: [debug] updating status for upgraded release for my-mariadb
    Release "my-mariadb" has been upgraded. Happy Helming!
    ```

**Comment by dnwe** [comment]
Fix released in [Helm v3.9.1](https://github.com/helm/helm/releases/tag/v3.9.1)
