### PR TITLE
fix(*): add support for "DELETING" status

### LINKED ISSUE #1511: feat: Add Status_DELETING status code to info object
Deletions can be in-process, and then fail. A status called DELETING could track the state where a release deletion is in-process. Failed deletes would then be left in the state DELETING.

### PR DESCRIPTION
**Pull request by technosophos**
Closes #1511

### CODE REVIEW

File: pkg/tiller/release_server.go [hunk 1]
```diff
@@ -964,9 +964,8 @@ func (s *ReleaseServer) UninstallRelease(c ctx.Context, req *services.UninstallR
 		return nil, fmt.Errorf("Could not get apiVersions from Kubernetes: %s", err)
 	}
 
-	// From here on out, the release is currently considered to be in Status_DELETED
-	// state. See https://github.com/kubernetes/helm/issues/1511 for a better way
-	// to do this.
+	// From here on out, the release is currently considered to be in Status_DELETINT
```
Comment (adamreese) [inline pkg/tiller/release_server.go]: Status_DELETING
