### PR TITLE
Make fixes

### LINKED ISSUE #270: Docker images are too big
docker images for expandybird and co are really big 600MB to 700MB+

We should consider using alpine or other alternatives to make these images smaller

### LINKED ISSUE #292: Fix image builds after helm/dm project merge
Docker images should be buildable (via `make`) for the following:

- manager
- resourcifier
- expandybird

### PR DESCRIPTION
**Pull request by jackgr**
This pull request fixes #292 and finishes the work started in #291 to fix #270.

It completes the work started in #291 to move the container build and push to the rootfs directory and removes the dockerfiles and makefiles for the directories under cmd, which are no longer needed, since the only thing they added to the go build and test was container build and push.

@adamreese PTAL.

### CODE REVIEW

File: stop.sh [hunk 1]
```diff
@@ -0,0 +1,24 @@
+#!/bin/bash
+
+echo "Stopping resourcifier..."
+RESOURCIFIER=`which resourcifier`
```
Comment (adamreese) [inline stop.sh]: RESOURCIFIER=`bin/resourcifier`

File: stop.sh [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+if [[ ! -z $RESOURCIFIER ]] ; then
+	pkill -f $RESOURCIFIER
+fi
+echo
+
+echo "Stopping expandybird..."
+EXPANDYBIRD=`which expandybird`
```
Comment (adamreese) [inline stop.sh]: EXPANDYBIRD=`bin/expandybird`

File: stop.sh [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+if [[ ! -z $EXPANDYBIRD ]] ; then
+	pkill -f $EXPANDYBIRD
+fi
+echo
+
+echo "Stopping deployment manager..."
+MANAGER=`which manager`
```
Comment (adamreese) [inline stop.sh]: MANAGER=`bin/manager`

File: stop.sh (hunk 1 above)
Comment (jackgr) [inline stop.sh]: Good catch. Thanks.

**Comment by technosophos** [comment]
After decluttering the top level directory, I am uncomfortable with putting shell scripts at the top level. Can we put the start/stop shell scripts in either `scripts/` or `hack/`?

File: include.mk [hunk 4]
```diff
@@ -1,6 +0,0 @@
-.PHONY: info
-info:
```
Comment (adamreese) [inline include.mk]: Why did `info` target get deleted?

Comment (adamreese) [inline include.mk]: scratch that, just found it in `rootfs`

**Comment by adamreese** [comment]
Not sure I understand the make targets.  For example what is the command now if I want to build an image and push to my account at `quay.io/adamreese/`

File: rootfs/include.mk [hunk 5]
```diff
@@ -0,0 +1,69 @@
...
+
+.docker:
+	@if [[ -z `which docker` ]] || ! docker version &> /dev/null; then echo "docker is not installed correctly"; exit 1; fi
+
+CROSS_IMAGE := $(PLATFORM)-$(ARCH)/$(IMAGE)/$(IMAGE)
+
+.PHONY: binary
+binary:
+	@if [[ -z $(CROSS_IMAGE) ]]; then \
+		echo cp ../../bin/$(CROSS_IMAGE) ./bin ; \
```
Comment (adamreese) [inline rootfs/include.mk]: Does this always pull in host arch rather than the required arch for the image?

File: include.mk (hunk 4 above)
Comment (jackgr) [inline include.mk]: Because it isn't used/needed at the top level.

File: rootfs/include.mk (hunk 5 above)
Comment (jackgr) [inline rootfs/include.mk]: Not sure why it would do that. What am I missing?

The reason it's here is that the directory structure of bin is different depending on whether we did a simple build or a cross build. We therefore try the cross build first, and if that doesn't succeed, then the simple build.

That said, a better solution would be to always use the cross build format, and to link the appropriate binary to the simple build output name for the host machine, so that we can use either the simple name or the cross build name in any reference.

**Comment by jackgr** [comment]
@technosophos Good catch.

**Comment by jackgr** [comment]
@adamreese it's no different from what it was. Just factored out the common parts into an include. The definitions are unchanged.

To push to `quay.io/adamreese/`, you would set `DOCKER_REGISTRY` to `quay.io`

File: rootfs/include.mk [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+		cp ../../bin/$(CROSS_IMAGE) ./bin ; \
+	else \
```
Comment (technosophos) [inline rootfs/include.mk]: What is the use case for this? Seems to me that it's a likely vector for an error that would not be caught until after the image was pushed and it failed to start.

File: rootfs/manager/Makefile [hunk 7]
```diff
@@ -11,30 +11,16 @@
...
-	gcloud docker push $(PREFIX)/$(IMAGE):$(TAG)
-else
-	docker push $(PREFIX)/$(IMAGE):$(TAG)
-endif
+include ../include.mk
 
-binary:
-	cp ../../bin/linux-amd64/manager ./bin
+.PHONY: extras
+extras: kubectl
```
Comment (technosophos) [inline rootfs/manager/Makefile]: Why is this target here?

File: rootfs/include.mk (hunk 6 above)
Comment (jackgr) [inline rootfs/include.mk]: #291 decouples the Docker build from the binary build. In addition, it changes the binary build to include both simple compile and cross compile. These two build targets structure the bin directory differently. This fix allows the container build to use either bin directory structure. Without it, the container build fails if the binary build used the cross compile.

Per my comment above, a more complete solution would be to make the simple compile use the same directory structure as the cross compile. However, I don't believe we need to make that change in order to push the rest of these changes.

File: rootfs/manager/Makefile (hunk 7 above)
Comment (jackgr) [inline rootfs/manager/Makefile]: It allows us to put the common parts of the binary build in include.mk, and to add any additional binary build steps in the individual makefiles.

Comment (technosophos) [inline rootfs/manager/Makefile]: I don't follow you there. This is a make target that just goes to another make target, and it's in a top-level file, not a shared one.

Comment (jackgr) [inline rootfs/manager/Makefile]: Sure. ../include.mk contains the following target:

```Makefile
.PHONY: container
container: .project .docker binary extras
	docker build -t $(FULL_IMAGE):latest -f Dockerfile .
	docker tag -f $(FULL_IMAGE):latest $(FULL_IMAGE):$(TAG)
```

It depends on extras, which is a target that any including Makefile must define, and can use to cause additional work to be done in the binary build.

Rather than put any additional work directly under extras, it seems cleaner to make extras depend on one or more targets that do the extra work.
