### PR TITLE
fix(*): fix various style issues from make test-style

### LINKED ISSUE #847: 'make test-style' errors
Running `make test` has several style errors that should be easy to correct:

```
/Users/mattbutcher/Code/Go/src/k8s.io/helm/cmd/helm/package.go:58:21: error strings should not end with punctuation
/Users/mattbutcher/Code/Go/src/k8s.io/helm/pkg/helm/client.go:11:2: comment on exported const HelmHostEnvVar should be of the form "HelmHostEnvVar ..."
/Users/mattbutcher/Code/Go/src/k8s.io/helm/pkg/helm/client.go:14:2: comment on exported const HelmHomeEnvVar should be of the form "HelmHomeEnvVar ..."
/Users/mattbutcher/Code/Go/src/k8s.io/helm/pkg/helm/client.go:17:2: comment on exported const DefaultHelmHost should be of the form "DefaultHelmHost ..."
/Users/mattbutcher/Code/Go/src/k8s.io/helm/pkg/helm/client.go:20:2: comment on exported const DefaultHelmHome should be of the form "DefaultHelmHome ..."
/Users/mattbutcher/Code/Go/src/k8s.io/helm/pkg/helm/client.go:24:1: comment on exported type Client should be of the form "Client ..." (with optional leading article)
/Users/mattbutcher/Code/Go/src/k8s.io/helm/pkg/helm/client.go:29:1: exported function NewClient should have comment or be unexported
/Users/mattbutcher/Code/Go/src/k8s.io/helm/pkg/helm/client.go:33:1: comment on exported method Client.Option should be of the form "Option ..."
/Users/mattbutcher/Code/Go/src/k8s.io/helm/pkg/helm/client.go:41:1: comment on exported method Client.Init should be of the form "Init ..."
/Users/mattbutcher/Code/Go/src/k8s.io/helm/pkg/helm/client.go:74:1: comment on exported method Client.DeleteRelease should be of the form "DeleteRelease ..."
/Users/mattbutcher/Code/Go/src/k8s.io/helm/pkg/helm/compat.go:10:5: exported var Config should have comment or be unexported
/Users/mattbutcher/Code/Go/src/k8s.io/helm/pkg/helm/compat.go:14:1: comment on exported function ListReleases should be of the form "ListReleases ..."
/Users/mattbutcher/Code/Go/src/k8s.io/helm/pkg/helm/compat.go:26:1: comment on exported function GetReleaseStatus should be of the form "GetReleaseStatus ..."
/Users/mattbutcher/Code/Go/src/k8s.io/helm/pkg/helm/compat.go:31:1: comment on exported function GetReleaseContent should be of the form "GetReleaseContent ..."
/Users/mattbutcher/Code/Go/src/k8s.io/helm/pkg/helm/compat.go:36:1: comment on exported function UpdateRelease should be of the form "UpdateRelease ..."
/Users/mattbutcher/Code/Go/src/k8s.io/helm/pkg/helm/compat.go:41:1: comment on exported function InstallRelease should be of the form "InstallRelease ..."
/Users/mattbutcher/Code/Go/src/k8s.io/helm/pkg/helm/compat.go:50:1: comment on exported function UninstallRelease should be of the form "UninstallRelease ..."
```

### PR DESCRIPTION
**Pull request by technosophos**
Closes #847.

### CODE REVIEW

File: cmd/helm/package.go [hunk 1]
```diff
@@ -71,7 +71,7 @@ func runPackage(cmd *cobra.Command, args []string) error {
 	}
 
 	if filepath.Base(path) != ch.Metadata.Name {
-		return fmt.Errorf("directory name (%s) and Chart.yaml name (%s) must match.", filepath.Base(path), ch.Metadata.Name)
+		return fmt.Errorf("directory name (%s) and Chart.yaml name (%s) must match", filepath.Base(path), ch.Metadata.Name)
```
Comment (michelleN) [inline cmd/helm/package.go]: ah and the infamous punctuation at the end of an error taboo strikes again 🔥
