### PR TITLE
fix: error when more than one post-renderer is specified

### LINKED ISSUE #13472: helm command allows multiple `--post-renderer` arguments
but ignores all but last one.

```
$ helm install name1 chart9 --post-renderer=tac --post-renderer=cat
NAME: name1
LAST DEPLOYED: Thu Nov 21 15:35:14 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=chart9,app.kubernetes.io/instance=name1" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080/ to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT
```
My helm version:
```
$ helm version
version.BuildInfo{Version:"v3.16.1", GitCommit:"5a5449dc42be07001fd5771d56429132984ab3ab", GitTreeState:"clean", GoVersion:"go1.22.7"}

### PR DESCRIPTION
**Pull request by yardenshoham**
We now make sure the post-renderer flag can be passed at most once instead of silently taking the last one passed.

Example:

```bash
$ helm template test ...  --post-renderer=true --post-renderer=cat
Error: invalid argument "cat" for "--post-renderer" flag: cannot specify --post-renderer flag more than once
```

- Closes https://github.com/helm/helm/issues/13472
-----
- [X] this PR contains unit tests
- [X] this PR has been tested for backwards compatibility (runs which specify more than one `--post-renderer` now fail)

### CODE REVIEW

File: cmd/helm/flags.go [hunk 1]
```diff
@@ -24,6 +24,7 @@ import (
 	"sort"
 	"strings"
 
+	"github.com/pkg/errors"
```
Comment (gjenkins8) [inline cmd/helm/flags.go:27]: This package is dead/unmaintained. Please don't add new usages.

File: cmd/helm/flags.go [hunk 2]
```diff
@@ -143,6 +144,9 @@ func (p *postRendererString) Set(val string) error {
 	if val == "" {
 		return nil
 	}
+	if p.options.binaryPath != "" && p.options.binaryPath != val {
```
Comment (gjenkins8) [inline cmd/helm/flags.go:147]: Is there a reason to support multiple usages with the same flag? Providing the flag mutliple times should be an error regardless

```suggestion
	if p.options.binaryPath != "" {
```

File: cmd/helm/flags.go [hunk 3]
```diff
@@ -143,6 +144,9 @@ func (p *postRendererString) Set(val string) error {
...
+		return errors.Errorf("cannot set post-renderer more than once, given: %s, previous: %s", val, p.options.binaryPath)
```
Comment (gjenkins8) [inline cmd/helm/flags.go:148]: I don't think we need to tell the user the values they supplied. Just stick to the pertinent message:

```suggestion
		return fmt.Errorf("cannot specify --post-renderer flag more than once")
```

**Review by gjenkins8 — CHANGES_REQUESTED** [review]
(see review comments)

**Comment by yardenshoham** [comment]
I made the requested changes

File: cmd/helm/flags.go (hunk 1 above)
Comment (yardenshoham) [reply cmd/helm/flags.go]: I will create a pull request to remove it from the codebase

Comment (yardenshoham) [reply cmd/helm/flags.go]: Nevermind it's deeply ingrained

**Review by gjenkins8 — DISMISSED** [review]
nice, appreciate the contribution!

**Comment by robertsirc** [comment]
Hi @yardenshoham first thank you for your PR. Your branch has conflicts could you please resolve so we can finish up the review?

**Comment by yardenshoham** [comment]
Sure, done.

**Review by robertsirc — APPROVED** [review]
LGTM
