### PR TITLE
bugfix: helm lint infinite loop

### LINKED ISSUE #11391: helm lint stuck with malformed template object
Hi

Output of `helm version`:

> version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.19.1"}

With this template file (notice the space between the first and the second curly brackets): 
`{ {- $relname := .Release.Name -}}`

helm lint does not respond whereas helm template throws an error (which is the normal behaviour) :
> Error: YAML parse error on onboarding-ms/templates/secret.yaml: error converting YAML to JSON: yaml: did not find expected node content
Use --debug flag to render out invalid YAML`

### PR DESCRIPTION
**Pull request by wujunwei**
Signed-off-by: wujunwei <wjw3323@live.com>

**What this PR does / why we need it**:
Fixes #11391
**Special notes for your reviewer**:

**If applicable**:
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

File: pkg/lint/rules/template.go [hunk 1]
```diff
@@ -141,10 +141,11 @@ func Templates(linter *support.Linter, values map[string]interface{}, namespace
 					break
 				}
 
-				// If YAML linting fails, we sill progress. So we don't capture the returned state
-				// on this linter run.
-				linter.RunLinterRule(support.ErrorSev, fpath, validateYamlContent(err))
-
+				// If YAML linting fails, it will always be fails next block. so we should return here.
```
Comment (yardenshoham) [inline pkg/lint/rules/template.go:144]:
```suggestion
				// If YAML linting fails here, it will always fail in the next block as well, so we should return here.
```

**Review by yardenshoham — CHANGES_REQUESTED** [review]

File: pkg/lint/rules/template.go (hunk 1 above)
Comment (wujunwei) [reply pkg/lint/rules/template.go]: thanks for this good suggestion :) !

**Comment by wujunwei** [comment]
This PR may fix a serious bug, could anyone have a look?

**Comment by wujunwei** [comment]
> @wujunwei sure. could you add some tests for this case? Thanks very much.

I have add some test ,  PTAL :)

File: pkg/lint/lint_test.go [hunk 2]
```diff
@@ -151,3 +153,26 @@ func TestSubChartValuesChart(t *testing.T) {
 		}
 	}
 }
+
+// lint stuck with malformed template object
+// See https://github.com/helm/helm/issues/11391
+func TestMalformedTemplate(t *testing.T) {
+	c := time.After(3 * time.Second)
```
Comment (yxxhero) [inline pkg/lint/lint_test.go:160]: why 3s?

Comment (wujunwei) [reply pkg/lint/lint_test.go:160]: > why 3s?

Before repair in the code, it will cause infinite loop when lint the malformed template . So  we wait it for 3s to test wheather a  infinite loop happen or not.  

It doesn't have to be 3s. Do you have any better suggestions?

Comment (yxxhero) [reply pkg/lint/lint_test.go:160]: @wujunwei ok. got it. Thanks very much.

**Comment by wujunwei** [comment]
I think this is a critical bug which should be fix as soon as possible.

**Review by mattfarina — APPROVED** [review]

**Review by sabre1041 — APPROVED** [review]
LGTM
