### PR TITLE
Tiller should only enforce what we expect from Helm

### LINKED ISSUE #3409: "Error: Transport is closing" message when attempting to install
I am trying to install spinnaker from the kubeapps hub using:

```helm install stable/spinnaker --name spinnaker -f values.yaml```

This gave me no output but i could see the pods being created, and then later:

```Error: transport is closing```

Using `--wait` and `--timeout` didn't help.

Spinnaker seems to have spun up successfully, but since helm didn't finish registering the installation as complete, helm is stuck in "PENDING_INSTALL" state for spinnaker meaning I can't update/upgrade later.

Any ideas what might be happening?

### PR DESCRIPTION
**Pull request by benlangfeld**
https://github.com/kubernetes/helm/pull/3183 added a keepalive to the Helm client of 30s period, while Tiller was never configured to permit this, keeping the default minimum keepalive period of 5 minutes, disconnecting any clients which ping more regularly than this.

This commit enforces a minimum that is lower than what Helm is configured for, preventing these disconnections, and thus fixes #3409.

### CODE REVIEW

**Comment by benlangfeld** [comment]
I'm not actually sure how to test this; there doesn't appear to be any documentation on building a Tiller docker image to deploy into a test cluster. Could someone provide some guidance?

**Comment by benlangfeld** [comment]
So, I did manage to test this, and I still encounter the bug as described in #3409. I think i'm misunderstanding something, and I'd appreciate some help here.

**Comment by benlangfeld** [comment]
Ok, my testing procedure was bad (pull policy). Looks like this works:

```
➭ helm version
Client: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8+unreleased", GitCommit:"3b22ecd53b2df89e1d0dc625c7fd569450ef13d8", GitTreeState:"clean"}
➭ helm delete --purge my-deploy; time helm install ~/Downloads/helm-bug --name my-deploy --wait --debug
release "my-deploy" deleted
[debug] Created tunnel using local port: '51314'

[debug] SERVER: "127.0.0.1:51314"

[debug] Original chart version: ""
[debug] CHART PATH: /Users/blangfeld/Downloads/helm-bug

Error: release my-deploy failed: timed out waiting for the condition
```

**Comment by benlangfeld** [comment]
I would appreciate a review from @helgi and @technosophos in particular, since both were involved in the original PR which this corrects.

It would be lovely to get this in v2.8.2.

**Review by bacongobbler — APPROVED** [review]
LGTM based on reviews from users. I just want to confirm with the other core maintainers that the max idle connection time wasn't intentionally enabled for just TLS-backed tillers

**Review by cmdshepard — APPROVED** [review]
I can confirm that this change fixes the issue I was facing in [#3409](https://github.com/kubernetes/helm/issues/3409)

**Comment by bacongobbler** [comment]
@fibonacci1729 do you know why we only enabled max idle connection times for TLS-backed tillers as opposed to enabling it for all?

File: cmd/tiller/tiller.go [hunk 1]
```diff
@@ -157,12 +157,16 @@ func start() {
...
-			// If needed, we can configure the max connection age
-		}))
 	}
 
+	opts = append(opts, grpc.KeepaliveParams(keepalive.ServerParameters{
+		MaxConnectionIdle: 10 * time.Minute,
+		// If needed, we can configure the max connection age
+	}))
+	opts = append(opts, grpc.KeepaliveEnforcementPolicy(keepalive.EnforcementPolicy{
+		MinTime: time.Duration(20) * time.Second, // For compatibility with the client keepalive.ClientParameters
```
Comment (helgi) [inline cmd/tiller/tiller.go]: 20 seconds is the default in client and server https://godoc.org/google.golang.org/grpc/keepalive#ClientParameters

**Comment by helgi** [comment]
I had visually tracked down the delta to https://github.com/kubernetes/helm/commit/44e5cecdcaee14c15055d20d6b9a72e80cd4794d on the potential breakage. @thomastaylor312 did that one, can you provide insight into what @bacongobbler asked

I am at an offsite so I'm very sporadic on availability but this PR looks fine (without having tested it)

File: cmd/tiller/tiller.go (hunk 1 above)
Comment (bacongobbler) [reply cmd/tiller/tiller.go]: For the timeout yes, but the default enforcement policy is 5 minutes :)

https://godoc.org/google.golang.org/grpc/keepalive#EnforcementPolicy

Comment (helgi) [reply cmd/tiller/tiller.go]: doh, good point. Need more ☕️

**Review by helgi — APPROVED** [review]

**Comment by benlangfeld** [comment]
@bacongobbler @fibonacci1729 Anything I can do to unblock this? This is a serious regression in v2.8.0 which makes it unusable.

**Comment by bacongobbler** [comment]
Sorry, we're incredibly busy prepping for the summit next week. There will be some downtime between now and the summit. For the time being I'd suggest downgrading to v2.7.2 as that works for now. I'm aware of a few other bugs in 2.8.1 which will call for a 2.8.2 release. I'll bring it up after the summit.

**Comment by maikelvl** [comment]
@benlangfeld Works like a charm here. Thanks! 😄

**Comment by Nowaker** [comment]
Thanks to everyone involved! 👍
