### PR TITLE
Fix(helm): fix the bug of helm search --regexp

### LINKED ISSUE #2865: helm search --regex case sensitivity
helm/tiller version 2.5.1

I had added a couple repos:
$ helm repo add helmDevel http://example.com/devel
$ helm repo add helmStable http://example.com/stable

However doing various searches:
```works``` $ helm search helmDevel
```works``` $ helm search helmStable
```works``` $ helm search --regex 'helm'
```fails``` $ helm search --regex 'helmDevel'
```fails``` $ helm search --regex 'helmStable'
```fails``` $ helm search --regex 'helm[DS]'

Since the first three work, that leads me to believe there is a problem with how regex is handling mixed casing.

### PR DESCRIPTION
**Pull request by rocky-nupt**
helm search cannot search for upper case by --regexp, because it
lowers all the letters when build repo index.

Closes #2865

### CODE REVIEW

**Comment by technosophos** [comment]
If I understand it, the new logic would make it so that a search for `github` would fail for a chart that had `GitHub` or `Github` or `gitHub` in the name. That was not the intention of the initial design.

I think we'd need to modify the SearchLiteral query to do a regexp with the `i` modifier to preserve backward compatibility. So `helm search github` should return results for `github`, `GitHub`, etc.

I think case sensitivity for regexp-based searches is fine, though.

**Comment by rocky-nupt** [comment]
Sorry, I don't know the intention of the initial design. I have changed the PR. Now helm search doesn't have case sensitivity while helm search --regexp still has. @technosophos

File: cmd/helm/search/search_test.go [hunk 1]
```diff
@@ -196,7 +196,7 @@ func TestSearchByName(t *testing.T) {
 		},
 		{
 			name:  "description search, two results",
-			query: "two",
```
Comment (nebril) [inline cmd/helm/search/search_test.go]: These test cases still need to pass, please add uppercase test cases as additional cases.

File: cmd/helm/search/search.go [hunk 2]
```diff
@@ -231,5 +232,5 @@ func (s scoreSorter) Less(a, b int) bool {
 func indstr(name string, ref *repo.ChartVersion) string {
 	i := ref.Name + sep + name + "/" + ref.Name + sep +
 		ref.Description + sep + strings.Join(ref.Keywords, " ")
-	return strings.ToLower(i)
```
Comment (nebril) [inline cmd/helm/search/search.go]: This change should be covered with unit tests (I think TestAddRepo_Sort should be altered for this).

**Review by nebril — CHANGES_REQUESTED** [review]
Looks like a good change, please revise tests as asked.

**Comment by rocky-nupt** [comment]
Thanks for your review! I have added an uppercase test and altered TestAddRepo_Sort. Is it ok? @nebril

File: cmd/helm/search/search_test.go [hunk 3]
```diff
@@ -203,13 +203,21 @@ func TestSearchByName(t *testing.T) {
...
+		},
+		{
 			name:   "nothing found",
 			query:  "mayflower",
 			expect: []*Result{},
 		},
 		{
 			name:  "regexp, one result",
-			query: "th[ref]*",
+			query: "Th[ref]*",
```
Comment (nebril) [inline cmd/helm/search/search_test.go]: Looks much better, but I have to be picky here: this change in test case is unaffected by your logic changes. It's really minor, so I will approve this PR.

**Review by nebril — APPROVED** [review]
LGTM!

**Comment by thomastaylor312** [comment]
@nebril Are you going to merge this one or are you waiting on something?
