### PR TITLE
fix(lint): add KubeVersion and TillerVersion to linter

### LINKED ISSUE #2393: helm lint error around `.Capabilities.KubeVersion`
### Issue

`helm lint` gives the following error on a seemingly appropriate use of checking `.Capabilities.KubeVersion.Minor`:

```
 $ helm lint stable/spotify-docker-gc/
==> Linting stable/spotify-docker-gc/
...
[ERROR] templates/: render error in "spotify-docker-gc/templates/daemonset.yaml": template: spotify-docker-gc/templates/daemonset.yaml:6:25: executing "spotify-docker-gc/templates/daemonset.yaml" at <.Capabilities.KubeVe...>: can't evaluate field Minor in type *version.Info
```

### Details

The [chart](https://github.com/kubernetes/charts/pull/982) installs successfully and the template logic is evaluated as expected: yaml is not added if `KubeVersion.Minor` is less than 6, yaml is added if greater than or equal to 6.

The relevant template section looks like:
```
  {{- if ge .Capabilities.KubeVersion.Minor "6" }}
  updateStrategy:
    type: RollingUpdate
  {{- end }}
```

### Helm version
```
 $ helm version
Client: &version.Version{SemVer:"v2.4.1", GitCommit:"46d9ea82e2c925186e1fc620a8320ce1314cbb02", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.1", GitCommit:"46d9ea82e2c925186e1fc620a8320ce1314cbb02", GitTreeState:"clean"}
```

### PR DESCRIPTION
**Pull request by technosophos**
Closes #2393

### CODE REVIEW

File: pkg/lint/rules/template.go [hunk 1]
```diff
@@ -51,7 +54,17 @@ func Templates(linter *support.Linter) {
 	}
 
 	options := chartutil.ReleaseOptions{Name: "testRelease", Time: timeconv.Now(), Namespace: "testNamespace"}
-	caps := &chartutil.Capabilities{APIVersions: chartutil.DefaultVersionSet}
+	caps := &chartutil.Capabilities{
+		APIVersions: chartutil.DefaultVersionSet,
+		KubeVersion: &version.Info{
```
Comment (adamreese) [inline pkg/lint/rules/template.go]: I think you can just use `&version.Info{}`

Comment (technosophos) [inline pkg/lint/rules/template.go]: I thought we'd want to have something resembling real data in that field for chart linting.

**Review by adamreese — APPROVED** [review]
