### PR TITLE
fix(helm): pass down username/password CLI parameters to OCI registry clients

### LINKED ISSUE #12767: Helm template doesnt work with credentials for oci registries
Following command doesn't work without login to the registry 
`helm template <release-name> oci://ghcr.io/org-name/charts/chart-name --version 0.0.15 --username <user> --password <password>`

But if i do
`helm registry login 
oci://ghcr.io/org-name`
and then try to template the chart from the source, it works as expected

Output of `helm version`:
version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}

Output of `kubectl version`:
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Kind, OpenShift

### PR DESCRIPTION
**Pull request by banjoh**
**What this PR does / why we need it**:

Ensures basic auth credentials passed in via helm CLI are passed down to clients connecting to the OCI registry

closes #12767, #13404

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests (existing tests cover this)
- [x] this PR has been tested for backwards compatibility

**Test cases**

| Command | Pass/Fail | Comment |
| ---------- |:---------:| -----:|
| `helm install` | ✅ | |
| `helm upgrade` | ✅  | |
| `helm template` | ✅ | |
| `helm show chart/all/readme/values` | ✅  | |
| `helm pull` | ✅ | |
| `helm push` | ✅ | |
| `helm dependency build\|update` | ✅ | |
| `helm show all\|chart\|crds\|readme\|values` | ✅ | |
| `helm package` | ✅ | |

### CODE REVIEW

File: cmd/helm/root.go [hunk 1]
```diff
@@ -292,10 +297,26 @@ func newDefaultRegistryClient(plainHTTP bool) (*registry.Client, error) {
...
+func newRegistryClientWithTLS(
+	certFile, keyFile, caFile string, insecureSkipTLSverify bool, username, password string,
+) (*registry.Client, error) {
+	tlsConf, err := tlsutil.NewClientTLS(certFile, keyFile, caFile, insecureSkipTLSverify)
+	if err != nil {
+		return nil, fmt.Errorf("can't create TLS config for client: %w", err)
+	}
+
 	// Create a new registry client
-	registryClient, err := registry.NewRegistryClientWithTLS(os.Stderr, certFile, keyFile, caFile, insecureSkipTLSverify,
```
Comment (banjoh) [inline cmd/helm/root.go:297]: I found it unnecessary to expose a new public function to pass in the username/password. The `ClientOpt...` registry builder APIs are sufficient

**Comment by banjoh** [comment]
Test cases

| Command | Pass/Fail | Comment |
| ---------- |:---------:| -----:|
| `helm install` | ✅ | |
| `helm upgrade` | ✅  | |
| `helm template` | ✅ | |
| `helm show chart/all/readme/values` | ✅  | |
| `helm pull` | ✅ | |
| `helm push` | ❌ | username and password options are absent |

**Comment by banjoh** [comment]
This PR is ready for review

**Comment by sabre1041** [comment]
@banjoh is the goal for `--username` and `--password` to be CLI options? If so, they are not currently exposed

**Comment by banjoh** [comment]
> @banjoh is the goal for `--username` and `--password` to be CLI options? If so, they are not currently exposed

Yes, the goal is to allow a user to run one command which authenticates and does the requested action (install, pull, push...) instead of needing to first login then perform the needed action in 2 steps. Here is an install use case

#### Before this PR
```sh
helm registry login registry.com --username john@mail.com --password <SECRET>
helm install my-chart oci://registry.com/chart:0.0.1
```

#### After this PR
```sh
helm install my-chart oci://registry.com/chart:0.0.1 --username john@mail.com --password <SECRET>
```

Also note that, with http/https registry, running `helm install my-chart https://registry.com/chart:0.0.1 --username john@mail.com --password <SECRET>` works. This only fails when we have an OCI registry

> If so, they are not currently exposed

Do you mean that `--username` and `--password` options are not exposed entirely, or are there specific cases they aren't? The intention of this PR is to ensure the already exposed options that work with http/https also behave the same way as with OCI registries

**Comment by sabre1041** [comment]
> > @banjoh is the goal for `--username` and `--password` to be CLI options?
> 
> Yes, the goal is to allow a user to run one command which authenticates and does the requested action (install, pull, push...) instead of needing to first login then perform the needed action in 2 steps. Here is an install use case
> 
> #### Before this PR
> ```shell
> helm registry login registry.com --username john@mail.com --password <SECRET>
> helm install my-chart oci://registry.com/chart:0.0.1
> ```
> 
> #### After this PR
> ```shell
> helm install my-chart oci://registry.com/chart:0.0.1 --username john@mail.com --password <SECRET>
> ```
> 
> Also note that, with http/https registry, running `helm install my-chart https://registry.com/chart:0.0.1 --username john@mail.com --password <SECRET>` works. This only fails when we have an OCI registry
> 
> > If so, they are not currently exposed
> 
> Do you mean that `--username` and `--password` options are not exposed entirely, or are there specific cases they aren't? The intention of this PR is to ensure the already exposed options that work with http/https also behave the same way as with OCI registries

The issue is that not all commands with OCI interaction have the fields exposed. For example, `helm push` do not expose a `--username` or `--password` option. In addition, did you have any thoughts as they relate to `helm package` and `helm dependency` subcommands? Would we assume that associated registries require valid authentication to be stored?

**Review by sabre1041 — DISMISSED** [review]
This looks really good! This PR also supersedes #13096

File: pkg/action/install.go [hunk 2]
```diff
@@ -759,9 +759,10 @@ func (c *ChartPathOptions) LocateChart(name string, settings *cli.EnvSettings) (
 		Getters: getter.All(settings),
 		Options: []getter.Option{
 			getter.WithPassCredentialsAll(c.PassCredentialsAll),
-			getter.WithTLSClientConfig(c.CertFile, c.KeyFile, c.CaFile),
+			getter.WithTLSClientConfig(c.CertFile, c.KeyFile, c.CAFile),
```
Comment (scottrigby) [inline pkg/action/install.go:762]: can't change this until Helm 4 (breaking change as this is a public package)

File: cmd/helm/dependency.go [hunk 3]
```diff
@@ -120,3 +121,16 @@ func newDependencyListCmd(out io.Writer) *cobra.Command {
 	f.UintVar(&client.ColumnWidth, "max-col-width", 80, "maximum column width for output table")
 	return cmd
 }
+
+func addDependencySubcommandFlags(f *pflag.FlagSet, client *action.Dependency) {
+	f.BoolVar(&client.Verify, "verify", false, "verify the packages against signatures")
+	f.StringVar(&client.Keyring, "keyring", defaultKeyring(), "keyring containing public keys")
+	f.BoolVar(&client.SkipRefresh, "skip-refresh", false, "do not refresh the local repository cache")
+	f.StringVar(&client.Username, "username", "", "chart repository username where to locate the requested chart")
+	f.StringVar(&client.Password, "password", "", "chart repository password where to locate the requested chart")
```
Comment (scottrigby) [inline cmd/helm/dependency.go:130]: what do you think about adding `--password-stdin` like docker does, for the same reason (setting password in a CLI command is insecure, especially in CI where many folks use Helm commands).

I know password opt is used already, so this may be a bigger issue outside the scope of your PR. May be good to approach all these consistently - eg, we have `passwordFromStdinOpt` only for repo add and registry login, etc.

File: cmd/helm/root.go [hunk 4]
```diff
@@ -292,10 +297,26 @@ func newDefaultRegistryClient(plainHTTP bool) (*registry.Client, error) {
 	return registryClient, nil
 }
 
-func newRegistryClientWithTLS(certFile, keyFile, caFile string, insecureSkipTLSverify bool) (*registry.Client, error) {
+func newRegistryClientWithTLS(
```
Comment (scottrigby) [inline cmd/helm/root.go:300]: I'm looking at the `NewRegistryClientWithTLS` function. It's only ever called from here. But since it's public we can't remove it until Helm 4. I wonder though, could we consolidate some of the logic in that function, in `newRegistryClientWithTLS`, and the logic wrapping the few places where these are called?

**Review by scottrigby — CHANGES_REQUESTED** [review]
Thanks for this @banjoh 
One change request and a few comments

File: cmd/helm/root.go (hunk 4 above)
Comment (banjoh) [reply cmd/helm/root.go:300]: I think this can be done. We’d leave `NewRegistryClientWithTLS` as just a wrapper calling `newRegistryClientWithTLS` like you suggested

File: cmd/helm/dependency.go (hunk 3 above)
Comment (banjoh) [reply cmd/helm/dependency.go:130]: I think I can follow-up with another PR to limit the number of changes in this PR

File: cmd/helm/root.go (hunk 4 above)
Comment (banjoh) [reply cmd/helm/root.go:300]: @scottrigby now I remember why I could not DRY this code previously. I'd need to expose a new public function (i.e `NewRegistryClientWithTLSWithCreds`) in `pkg/registry/util` for it to be called in `cmd/helm` since we cannot add new parameters to `NewRegistryClientWithTLS`. Copying code over to `cmd/helm` seemed like the lesser evil

Comment (scottrigby) [reply cmd/helm/root.go:300]: That seems reasonable to me 👍

File: cmd/helm/dependency_build.go [hunk 5]
```diff
@@ -41,7 +41,7 @@ If no lock file is found, 'helm dependency build' will mirror the behavior
 of 'helm dependency update'.
 `
 
-func newDependencyBuildCmd(cfg *action.Configuration, out io.Writer) *cobra.Command {
+func newDependencyBuildCmd(_ *action.Configuration, out io.Writer) *cobra.Command {
```
Comment (joejulian) [inline cmd/helm/dependency_build.go:44]: This is a private function, we can just remove cfg completely.

File: cmd/helm/dependency_update.go [hunk 6]
```diff
@@ -43,7 +44,7 @@ in the Chart.yaml file, but (b) at the wrong version.
 `
 
 // newDependencyUpdateCmd creates a new dependency update command.
-func newDependencyUpdateCmd(cfg *action.Configuration, out io.Writer) *cobra.Command {
+func newDependencyUpdateCmd(_ *action.Configuration, out io.Writer) *cobra.Command {
```
Comment (joejulian) [inline cmd/helm/dependency_update.go:47]: Same here, private function
```suggestion
func newDependencyUpdateCmd(out io.Writer) *cobra.Command {
```

File: cmd/helm/package.go [hunk 7]
```diff
@@ -47,7 +47,7 @@ If '--keyring' is not specified, Helm usually defaults to the public keyring
 unless your environment is otherwise configured.
 `
 
-func newPackageCmd(cfg *action.Configuration, out io.Writer) *cobra.Command {
+func newPackageCmd(_ *action.Configuration, out io.Writer) *cobra.Command {
```
Comment (joejulian) [inline cmd/helm/package.go:50]: again, private function

**Review by joejulian — CHANGES_REQUESTED** [review]

**Comment by joejulian** [comment]
I'm concerned about this PR, and when I talked with @sabre1041 he agreed with my concern. There are so many variations on the implementation of the OCI spec, it's impossible for us to test that it works with all of them.

Can you think of some way to satisfy this concern? Even if you can demonstrate a manual proof that this doesn't break the most common cloud-company oci registries that would go a long way to satisfying my worry.

We've had this problem before so I'm a bit touchy.

**Comment by banjoh** [comment]
> I'm concerned about this PR, and when I talked with @sabre1041 he agreed with my concern. There are so many variations on the implementation of the OCI spec, it's impossible for us to test that it works with all of them.
> 
> Can you think of some way to satisfy this concern? Even if you can demonstrate a manual proof that this doesn't break the most common cloud-company oci registries that would go a long way to satisfying my worry.
> 
> We've had this problem before so I'm a bit touchy.

That's a valid concern. I'll work on it.

**Comment by sfc-gh-jlangefeld** [comment]
We just ran into this and are interested in this fix as well!

**Comment by banjoh** [comment]
> We just ran into this and are interested in this fix as well!

I'll address the requested comments next week.

**Comment by banjoh** [comment]
- docker registry - https://github.com/distribution/distribution (Tested already)
- AWS ECR - https://docs.aws.amazon.com/AmazonECR/latest/userguide/push-oci-artifact.html
- GCP artifact registry - https://cloud.google.com/artifact-registry/docs/helm/manage-charts
- Gitlab package registry - https://docs.gitlab.com/ee/user/packages/helm_repository/
- ArtifactHub - https://artifacthub.io/docs/topics/repositories/helm-charts/
- DockerHub - https://docs.docker.com/docker-hub/oci-artifacts/

@joejulian this is the list of OCI registries I'll test with. Feel free to add more to the list. I'm not sure I'll be able to cover all, especially if costs are involved

I also noticed https://helm.sh/docs/topics/registries/#use-hosted-registries list. Is this to say that we need to test against all these registries?

**Comment by banjoh** [comment]
Using the same tests in the PR description, here are test runs from different registries

| Command | Pass/Fail | Comment |
| ---------- |:---------:| -----:|
| `docker registry` | ✅ | |

**Comment by joejulian** [comment]
> Using the same tests in the PR description, here are test runs from different OCI registries
> Command 	Pass/Fail
> Docker registry 	✅
> AWS ECR 	✅
> GCP artifact registry 	✅
> Gitlab package registry 	✅
> DockerHub 	✅

This works for me. Thank you.

**Review by joejulian — DISMISSED** [review]

**Review by sabre1041 — DISMISSED** [review]
LGTM from my side as well

Thank you for working through not only the iterative development process, but testing the various configurations and various registries

File: cmd/helm/dependency.go [hunk 8]
```diff
@@ -120,3 +121,16 @@ func newDependencyListCmd(out io.Writer) *cobra.Command {
...
+	f.StringVar(&client.CertFile, "cert-file", "", "identify HTTPS client using this SSL certificate file")
+	f.StringVar(&client.KeyFile, "key-file", "", "identify HTTPS client using this SSL key file")
+	f.BoolVar(&client.InsecureSkipTLSverify, "insecure-skip-tls-verify", false, "skip tls certificate checks for the chart download")
+	f.BoolVar(&client.PlainHTTP, "plain-http", false, "use insecure HTTP connections for the chart download")
+	f.StringVar(&client.CAFile, "ca-file", "", "verify certificates of HTTPS-enabled servers using this CA bundle")
```
Comment (scottrigby) [inline cmd/helm/dependency.go:135]: Following up on https://github.com/helm/helm/pull/12769#pullrequestreview-2215880469 I suggest that we make all newly added fields consistent case, matching the existing field we can't change. So `CaFile` not `CAFile`
```suggestion
	f.StringVar(&client.CaFile, "ca-file", "", "verify certificates of HTTPS-enabled servers using this CA bundle")
```

File: cmd/helm/dependency_build.go [hunk 9]
```diff
@@ -54,21 +54,27 @@ func newDependencyBuildCmd(cfg *action.Configuration, out io.Writer) *cobra.Comm
 			if len(args) > 0 {
 				chartpath = filepath.Clean(args[0])
 			}
+			registryClient, err := newRegistryClient(client.CertFile, client.KeyFile, client.CAFile,
```
Comment (scottrigby) [inline cmd/helm/dependency_build.go:57]: see above:
```suggestion
			registryClient, err := newRegistryClient(client.CertFile, client.KeyFile, client.CaFile,
```

File: cmd/helm/dependency_update.go [hunk 10]
```diff
@@ -57,13 +58,19 @@ func newDependencyUpdateCmd(cfg *action.Configuration, out io.Writer) *cobra.Com
 			if len(args) > 0 {
 				chartpath = filepath.Clean(args[0])
 			}
+			registryClient, err := newRegistryClient(client.CertFile, client.KeyFile, client.CAFile,
```
Comment (scottrigby) [inline cmd/helm/dependency_update.go:61]: see above:
```suggestion
			registryClient, err := newRegistryClient(client.CertFile, client.KeyFile, client.CaFile,
```

File: cmd/helm/package.go [hunk 11]
```diff
@@ -75,6 +75,12 @@ func newPackageCmd(cfg *action.Configuration, out io.Writer) *cobra.Command {
 				return err
 			}
 
+			registryClient, err := newRegistryClient(client.CertFile, client.KeyFile, client.CAFile,
```
Comment (scottrigby) [inline cmd/helm/package.go:78]: see above:
```suggestion
			registryClient, err := newRegistryClient(client.CertFile, client.KeyFile, client.CaFile,
```

File: cmd/helm/package.go [hunk 12]
```diff
@@ -119,6 +125,13 @@ func newPackageCmd(cfg *action.Configuration, out io.Writer) *cobra.Command {
 	f.StringVar(&client.AppVersion, "app-version", "", "set the appVersion on the chart to this version")
 	f.StringVarP(&client.Destination, "destination", "d", ".", "location to write the chart.")
 	f.BoolVarP(&client.DependencyUpdate, "dependency-update", "u", false, `update dependencies from "Chart.yaml" to dir "charts/" before packaging`)
+	f.StringVar(&client.Username, "username", "", "chart repository username where to locate the requested chart")
+	f.StringVar(&client.Password, "password", "", "chart repository password where to locate the requested chart")
+	f.StringVar(&client.CertFile, "cert-file", "", "identify HTTPS client using this SSL certificate file")
+	f.StringVar(&client.KeyFile, "key-file", "", "identify HTTPS client using this SSL key file")
+	f.BoolVar(&client.InsecureSkipTLSverify, "insecure-skip-tls-verify", false, "skip tls certificate checks for the chart download")
+	f.BoolVar(&client.PlainHTTP, "plain-http", false, "use insecure HTTP connections for the chart download")
+	f.StringVar(&client.CAFile, "ca-file", "", "verify certificates of HTTPS-enabled servers using this CA bundle")
```
Comment (scottrigby) [inline cmd/helm/package.go:134]: see above:
```suggestion
	f.StringVar(&client.CaFile, "ca-file", "", "verify certificates of HTTPS-enabled servers using this CA bundle")
```

File: pkg/action/dependency.go [hunk 13]
```diff
@@ -34,10 +34,17 @@ import (
...
-	ColumnWidth uint
+	Verify                bool
+	Keyring               string
+	SkipRefresh           bool
+	ColumnWidth           uint
+	Username              string
+	Password              string
+	CertFile              string
+	KeyFile               string
+	CAFile                string
```
Comment (scottrigby) [inline pkg/action/dependency.go:45]: see above:
```suggestion
	CaFile                string
```

File: pkg/action/package.go [hunk 14]
```diff
@@ -44,8 +44,15 @@ type Package struct {
...
-	RepositoryConfig string
-	RepositoryCache  string
+	RepositoryConfig      string
+	RepositoryCache       string
+	PlainHTTP             bool
+	Username              string
+	Password              string
+	CertFile              string
+	KeyFile               string
+	CAFile                string
```
Comment (scottrigby) [inline pkg/action/package.go:54]: see above:
```suggestion
	CaFile                string
```

**Review by scottrigby — CHANGES_REQUESTED** [review]
one minor change request for consistency. Following up on https://github.com/helm/helm/pull/12769#pullrequestreview-2215880469 I suggest that we make all newly added fields consistent case, matching the existing field we can't change. So `CaFile` not `CAFile`

**Review by joejulian — APPROVED** [review]

**Review by scottrigby — APPROVED** [review]
7a22dd28d13b02c6cd15bea19c35825f4f420caf commit squash looks good! All lgtm. Agree with sentiments above, really nice work. Especially manual testing across cloud providers 👏  Tests pass, and we have had 2 other approvers 😄

File: cmd/helm/root.go (hunk 1 above)
Comment (EronWright) [reply cmd/helm/root.go:294]: One reason is to encapsulate the call to `tlsutil.NewClientTLS` which is internal.

**Comment by scottrigby** [comment]
We need to also bring this into the `dev-v3` branch. "needs v3 port" might be a better label.

File: cmd/helm/root.go (hunk 1 above)
Comment (banjoh) [reply cmd/helm/root.go:294]: I'll plan to add this in a follow-up PR I'm working on
