### PR TITLE
lint: Add --kube-version flag to set capabilities and deprecation rules

### LINKED ISSUE #10664: helm lint should allow specifying --kube-version flag
We're currently using `helm lint` to find deprecated API versions in our charts, failing CI on warnings. However, helm assumes that the target Kubernetes version is the one specified through the k8sVersionMajor/k8sVersionMinor vars. The only way to work around this is rebuilding helm with LDFLAGS, or using a Helm release with the proper defaults.

The command-line flag `--kube-version` currently exists with `helm template`, `helm lint` should replicate the behaviour:
https://github.com/helm/helm/pull/9040

### PR DESCRIPTION
**Pull request by antoinedeschenes**
Signed-off-by: Antoine Deschênes <antoine@antoinedeschenes.com>

**What this PR does / why we need it**:
closes #10664

Adds a `--kube-version` flag to the `helm lint` command, allowing to specify the Kubernetes version to use for the deprecation check warnings.

There's a similar flag in the `helm template` command. 

Specific example of where this is useful: 
- helm 3.8.0 releases are currently targetting Kubernetes 1.23. 
- We're currently running Kubernetes 1.22 clusters. 
- `helm lint --strict` is currently erroring out on HorizontalPodAutoscaler `autoscaling/v2beta2` having to be replaced by `autoscaling/v2`. 
- `autoscaling/v2` doesn't exist yet on Kubernetes 1.22. 

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

File: pkg/lint/lint.go [hunk 1]
```diff
@@ -19,19 +19,20 @@ package lint // import "helm.sh/helm/v3/pkg/lint"
...
 	"path/filepath"
 
+	"helm.sh/helm/v3/pkg/chartutil"
 	"helm.sh/helm/v3/pkg/lint/rules"
 	"helm.sh/helm/v3/pkg/lint/support"
 )
 
 // All runs all of the available linters on the given base directory.
-func All(basedir string, values map[string]interface{}, namespace string, strict bool) support.Linter {
+func All(basedir string, values map[string]interface{}, namespace string, strict bool, kubeVersion *chartutil.KubeVersion) support.Linter {
```
[the remark this answers is not in the document]
Comment (antoinedeschenes) [reply pkg/lint/lint.go:28]: Got it, would one of these be acceptable?
a. changing global variables at runtime
b. add a new function parallel to this one with a different signature

Are the changes in the subpackages also considered breaking?

[the remark this answers is not in the document]
Comment (yxxhero) [reply pkg/lint/lint.go:28]: @antoinedeschenes please see https://github.com/helm/helm/pull/8493

**Comment by yxxhero** [comment]
ping @antoinedeschenes

File: pkg/lint/lint.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (antoinedeschenes) [reply pkg/lint/lint.go:28]: Thanks @yxxhero I might find some time soon

**Comment by antoinedeschenes** [comment]
@yxxhero Just reversed All and Templates signatures to the original, added new functions in parallel.

File: pkg/lint/rules/template.go [hunk 2]
```diff
@@ -46,6 +46,11 @@ var (
 
 // Templates lints the templates in the Linter.
 func Templates(linter *support.Linter, values map[string]interface{}, namespace string, strict bool) {
+	TemplatesWithVersion(linter, values, namespace, strict, nil)
+}
+
+// TemplatesWithVersion lints the templates in the Linter, allowing to specify the kubernetes version.
+func TemplatesWithVersion(linter *support.Linter, values map[string]interface{}, namespace string, strict bool, kubeVersion *chartutil.KubeVersion) {
```
Comment (yxxhero) [inline pkg/lint/rules/template.go:53]: TemplatesWithVersion --> TemplatesWithKubeVersion

File: pkg/lint/lint.go [hunk 3]
```diff
@@ -19,19 +19,25 @@ package lint // import "helm.sh/helm/v3/pkg/lint"
...
 	"helm.sh/helm/v3/pkg/lint/support"
 )
 
 // All runs all of the available linters on the given base directory.
 func All(basedir string, values map[string]interface{}, namespace string, strict bool) support.Linter {
+	return AllWithVersion(basedir, values, namespace, strict, nil)
+}
+
+// AllWithVersion runs all of the available linters on the given base directory, allowing to specify the kubernetes version.
+func AllWithVersion(basedir string, values map[string]interface{}, namespace string, strict bool, kubeVersion *chartutil.KubeVersion) support.Linter {
```
Comment (yxxhero) [inline pkg/lint/lint.go:33]: AllWithVersion --> AllWithKubeVersion

**Comment by antoinedeschenes** [comment]
pign @yxxhero

**Review by joejulian — APPROVED** [review]
Nice. This is what I originally had hoped to do when I added the upstream deprecation library. Thanks!

**Comment by pete-woods** [comment]
@yxxhero I don't like to nag, but this PR adds something super useful for us

**Comment by joejulian** [comment]
@pete-woods @yxxhero and I are just triage maintainers. You need a core maintainer to review.

**Comment by yxxhero** [comment]
@joejulian me too.

**Comment by pete-woods** [comment]
Ah. Didn't appreciate that - apologies

File: pkg/lint/rules/deprecations.go [hunk 4]
```diff
@@ -54,6 +56,11 @@ func validateNoDeprecations(resource *K8sYamlStruct) error {
 		return nil
 	}
 
+	if kubeVersion != nil {
+		k8sVersionMajor = kubeVersion.Major
+		k8sVersionMinor = kubeVersion.Minor
+	}
```
Comment (mattfarina) [inline pkg/lint/rules/deprecations.go:62]: This isn't going to work for long running services that consume this as a package. The package level from one run can be changed for a next or concurrent unrelated run. It works for Helm because it's not used for long running services.

This function will need a local variable for the major and minor version. It can use the package level ones as the default which can be overridden by the passed in values.

The package level major/minor are only used in this function so this type of change should be safe.

**Review by mattfarina — CHANGES_REQUESTED** [review]
Thanks for this PR. I've long wanted this feature and am excited for it to land.

I found one minor issue that shows up for SDK consumers. Should be a quick fix if you could please make the change. Otherwise it looks good to me.

**Comment by mattfarina** [comment]
@antoinedeschenes can you make the one small change or should someone else make it?

**Comment by antoinedeschenes** [comment]
> @antoinedeschenes can you make the one small change or should someone else make it?

@mattfarina Taking a look

File: pkg/lint/rules/deprecations.go (hunk 4 above)
Comment (antoinedeschenes) [reply pkg/lint/rules/deprecations.go]: @mattfarina Corrected

**Comment by zifter** [comment]
Any updates?

**Review by joejulian — APPROVED** [review]

**Comment by joejulian** [comment]
Tested this and it works for me. I wish we could make it an error if it's past the unavailable deadline, but that would be a breaking change, I guess, and outside the scope of this PR.

**Comment by antoinedeschenes** [comment]
Any timeframe in mind?

**Review by mattfarina — APPROVED** [review]

**Comment by mattfarina** [comment]
Note, I fixed a merge conflict caused by #12688 where `strict` became `_`. An unused argument. This was to pass linting.

**Comment by mattfarina** [comment]
Since my commit should not have made major changes to cause the failed test run, I checked out the commit before it and ran the test suite there. I get the same error of...

```
--- FAIL: TestLintCmdWithKubeVersionFlag (0.01s)
    --- FAIL: TestLintCmdWithKubeVersionFlag/lint_chart_with_deprecated_api_version_without_kube_version (0.00s)
        helm_test.go:61: running cmd (attempt 1): lint testdata/testcharts/chart-with-deprecated-api
        helm_test.go:70: does not match golden file testdata/output/lint-chart-with-deprecated-api.txt

            WANT:
            '==> Linting testdata/testcharts/chart-with-deprecated-api
            [INFO] Chart.yaml: icon is recommended
            [WARNING] templates/horizontalpodautoscaler.yaml: autoscaling/v2beta1 HorizontalPodAutoscaler is deprecated in v1.22+, unavailable in v1.25+; use autoscaling/v2 HorizontalPodAutoscaler

            1 chart(s) linted, 0 chart(s) failed
            '

            GOT:
            '==> Linting testdata/testcharts/chart-with-deprecated-api
            [INFO] Chart.yaml: icon is recommended

            1 chart(s) linted, 0 chart(s) failed
            '
```

This is for commit [46e3886](https://github.com/helm/helm/pull/10677/commits/46e388636fd431a2f3f67c8bb485275e6550c78d).

This is because the internal k8s version is set to 1.20 which is what's used for the testing. So the `lint` command without setting the Kubernetes version uses this which would not produce the error.

I'm not sure how this test ever passed.

The easy fix is to update `k8sVersionMinor`.

**Comment by joejulian** [comment]
> Since my commit should not have made major changes to cause the failed test run, I checked out the commit before it and ran the test suite there. I get the same error of...
> 
> ```
> --- FAIL: TestLintCmdWithKubeVersionFlag (0.01s)
>     --- FAIL: TestLintCmdWithKubeVersionFlag/lint_chart_with_deprecated_api_version_without_kube_version (0.00s)
>         helm_test.go:61: running cmd (attempt 1): lint testdata/testcharts/chart-with-deprecated-api
>         helm_test.go:70: does not match golden file testdata/output/lint-chart-with-deprecated-api.txt
> 
>             WANT:
>             '==> Linting testdata/testcharts/chart-with-deprecated-api
>             [INFO] Chart.yaml: icon is recommended
>             [WARNING] templates/horizontalpodautoscaler.yaml: autoscaling/v2beta1 HorizontalPodAutoscaler is deprecated in v1.22+, unavailable in v1.25+; use autoscaling/v2 HorizontalPodAutoscaler
> 
>             1 chart(s) linted, 0 chart(s) failed
>             '
> 
>             GOT:
>             '==> Linting testdata/testcharts/chart-with-deprecated-api
>             [INFO] Chart.yaml: icon is recommended
> 
>             1 chart(s) linted, 0 chart(s) failed
>             '
> ```
> 
> This is for commit [46e3886](https://github.com/helm/helm/pull/10677/commits/46e388636fd431a2f3f67c8bb485275e6550c78d).
> 
> This is because the internal k8s version is set to 1.20 which is what's used for the testing. So the `lint` command without setting the Kubernetes version uses this which would not produce the error.
> 
> I'm not sure how this test ever passed.
> 
> The easy fix is to update `k8sVersionMinor`.

This _should_ have made it work: https://github.com/helm/helm/pull/10677/commits/869c1d2560f493bb7d4d93e04b8932144ea11e0d#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R107

But it broke a bunch of other golden images that have labels with the k8s version data. 

Rather than have to update the golden files with every client-go release, I reverted the addition of ldflags on the test and switched the expected golden image to the old k8s one.

**Comment by joejulian** [comment]
sorry for my force-pushes. I neglected to sign my commit and am trying to help get this across the finish line for this release.

**Review by mattfarina — APPROVED** [review]
