### PR TITLE
fix(kube): fix wait and recreate

### LINKED ISSUE #2006: --wait does not work as expected with helm version 2.2.0 install/upgrade/rollback
It is expected for `helm install/upgrade/rollback` to wait before coming back  to make sure all the pods are up and running for a given release.. But, seems like it does not wait and comes back right away .. Logging an issue after conversation with @technosophos

### PR DESCRIPTION
**Pull request by adamreese**
fixes #2006

### CODE REVIEW

File: pkg/kube/client.go [hunk 1]
```diff
@@ -536,6 +543,16 @@ func getPods(client *internalclientset.Clientset, namespace string, selector map
 	return list.Items, err
 }
 
+func (c *Client) AsVersionedObject(obj runtime.Object) (runtime.Object, error) {
```
Comment (thomastaylor312) [inline pkg/kube/client.go]: This exported function needs a comment

**Review by thomastaylor312 — CHANGES_REQUESTED** [review]
This is causing a panic with a nil pointer dereference at 433. Only on upgrades with recreate pods. Install works ok.

**Comment by thomastaylor312** [comment]
Basically it looks like the `Selector` is nil. Not sure why that is happening

**Review by thomastaylor312 — APPROVED** [review]
