### PR TITLE
Closes #3352, add support for --ignore-not-found just like kubectl delete

### LINKED ISSUE #3352: Ignore errors on helm install or delete
I am deploying multiple releases into a Kubernetes cluster using helm via an automated pipeline.
In most cases I create a new release when the job runs through the pipeline.

However in some cases I need to redeploy with the same release name.
Is there any facility or flag in helm to ignore an error on install or delete?
Sometimes errors are acceptable/expected so I don't want my pipeline to crash or have to add a bunch of custom logic to circumvent the (expected) error.

A flag kin to what kubectl has would be ideal:
```
--ignore-not-found=true
```

### PR DESCRIPTION
**Pull request by suzaku**
**What this PR does / why we need it**:
Closes #3352, add the option `--ignore-not-found` for `helm uninstall`.
`kubectl delete` has a similar option, which is very handy when deleting a lot of resources because we don't have to make sure they exist beforehand.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by mircozanchi — APPROVED** [review]
LGTM

**Comment by suzaku** [comment]
Maybe we should just fork it instead of contributing PRs.

**Comment by scottrigby** [comment]
I like this proposal. There is a PR review meetup in Brooklyn tomorrow, this could be a good one for new reviewers

**Comment by suzaku** [comment]
Hi @scottrigby , any news from the PR review meetup?

**Comment by scottrigby** [comment]
Hi @suzaku , not yet - I am on vacation until Aug 30, and will check in with PR reviewers then. There were several new reviewers from that meetup, and one person has been given allocated time from their company to help 🙂

In the meantime Phillip Stehle has given a summary of this weeks Helm pull request review session that was planned during the last Helm dev meeting. See this slack thread:

https://kubernetes.slack.com/archives/C51E88VDG/p1660833138133719?thread_ts=1660317807.065359&channel=C51E88VDG&message_ts=1660833138.133719

File: pkg/action/uninstall.go [hunk 1]
```diff
@@ -71,6 +72,9 @@ func (u *Uninstall) Run(name string) (*release.UninstallReleaseResponse, error)
 
 	rels, err := u.cfg.Releases.History(name)
 	if err != nil {
+		if u.IgnoreNotFound {
```
Comment (sudermanjr) [inline pkg/action/uninstall.go:75]: Is `notFound` the only error that can be returned by the release history command? Digging through the storage driver for secrets, it seems like there are multiple errors that could be returned. I think to be thorough this should check for a specific error condition before returning nil.

Additionally, I wonder if a debug log message would be appropriate here.

**Review by sudermanjr — CHANGES_REQUESTED** [review]
Love the feature! Left an inline question about error checking. Thanks!

File: pkg/action/uninstall.go (hunk 1 above)
Comment (suzaku) [reply pkg/action/uninstall.go:75]: Good point, I'll check.

Comment (suzaku) [reply pkg/action/uninstall.go]: I've update the code to check for `ErrReleaseNotFound` explicitly.

**Review by sudermanjr — APPROVED** [review]
LGTM. Thanks!

**Comment by suzaku** [comment]
@sudermanjr Any news for this PR?

**Comment by stevo-f3** [comment]
Can this please be merged?

**Comment by suzaku** [comment]
@sudermanjr @mircozanchi Hello, if there's nothing terribly risky about merging this approved PR can we just merge it?

**Comment by joejulian** [comment]
This looks good. Any chance you can fix the merge conflict?

**Comment by suzaku** [comment]
> This looks good. Any chance you can fix the merge conflict @suzaku ?

Conflict resolved.

**Comment by suzaku** [comment]
> This looks good. Any chance you can fix the merge conflict @suzaku ?

Hello, can you merge it now?

**Review by joejulian — APPROVED** [review]
