### PR TITLE
Fix : Prints empty list in json/yaml is no repositories are present

### LINKED ISSUE #7939: Helm 3 ignores the output format for empty repos list
Dear team,

The command `helm repo list` returns an error when there are no repositories.
Due to this behaviour, the `-o json` flag is ignored and the same error is returned instead of an empty list `[]`

The expected behaviour would be the same of `helm list` when no installed charts are present

Output of `helm version` (I have tried with both):
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
version.BuildInfo{Version:"v3.2.0-rc.1", GitCommit:"7bffac813db894e06d17bac91d14ea819b5c2310", GitTreeState:"clean", GoVersion:"go1.13.10"}

Thanks

### PR DESCRIPTION
**Pull request by anshulvermapatel**
Prints empty repolist in json/yaml if there are no repositories and output format is given as json/yaml rather that printing the error msg "no repositories to show"
~~~
$ ./helm repo list -oyaml  
[]
$ ./helm repo list -ojson
[]
$ ./helm repo list       
Error: no repositories to show
~~~
Fixes [#7939](https://github.com/helm/helm/issues/7939)

### CODE REVIEW

**Comment by anshulvermapatel** [comment]
@mattfarina , can you please have a look at this?

File: cmd/helm/repo_list.go [hunk 1]
```diff
@@ -38,7 +38,7 @@ func newRepoListCmd(out io.Writer) *cobra.Command {
 		Args:    require.NoArgs,
 		RunE: func(cmd *cobra.Command, args []string) error {
 			f, err := repo.LoadFile(settings.RepositoryConfig)
-			if isNotExist(err) || len(f.Repositories) == 0 {
```
Comment (technosophos) [inline cmd/helm/repo_list.go:41]: I think this should use `output.JSON` and `output.YAML` instead of the string literals. Otherwise, looks great!

Comment (anshulvermapatel) [reply cmd/helm/repo_list.go:41]: @technosophos , Yes, I have made the changes.

**Comment by anshulvermapatel** [comment]
@technosophos , Have made the change, can you please review. Thanks.

**Review by technosophos — APPROVED** [review]
