### PR TITLE
fix(downloader): prevent concurrent file access errors on Windows

### LINKED ISSUE #11096: Concurrency issues pulling charts in Helm 3.7.2
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}
```

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.12-eks-a64ea69", GitCommit:"d4336843ba36120e9ed1491fddff5f2fec33eb77", GitTreeState:"clean", BuildDate:"2022-05-12T18:29:27Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AWS EKS

---

I have encountered an issue, superficially similar to to #10735, although I think the exact cause is different. In my case, the issue occurs when a command such as `helm template` attempts to pull the `.tgz` of a chart not already in the cache; if multiple such commands are being run concurrently, which involve the same chart and chart version, then, at least on Windows, they may attempt to place the `.tgz` file into the cache simultaneously, leading to errors.

Given the concurrency-related nature of this issue, it's not reproducible _reliably_, but I'm able to trigger it fairly often using a Powershell script like this:

```powershell
rm -r $env:LocalAppData\Temp\helm\repository\fluent-bit-0.20.3.tgz
1,2,3,4,5,6 | ForEach-Object -Parallel { helm --kube-context test template fluent-bit fluent/fluent-bit --values values.yaml --version 0.20.3 --debug --output-dir ./tmp/$_ } -ThrottleLimit 6
rm -r ./tmp
```

This will sometimes lead to failures, with output like

```
install.go:178: [debug] Original chart version: "0.20.3"
install.go:178: [debug] Original chart version: "0.20.3"
install.go:178: [debug] Original chart version: "0.20.3"
install.go:178: [debug] Original chart version: "0.20.3"
install.go:178: [debug] Original chart version: "0.20.3"
install.go:178: [debug] Original chart version: "0.20.3"
install.go:199: [debug] CHART PATH: C:\Users\me\AppData\Local\Temp\helm\repository\fluent-bit-0.20.3.tgz
install.go:199: [debug] CHART PATH: C:\Users\me\AppData\Local\Temp\helm\repository\fluent-bit-0.20.3.tgz
install.go:199: [debug] CHART PATH: C:\Users\me\AppData\Local\Temp\helm\repository\fluent-bit-0.20.3.tgz
Error: link error: cannot rename C:\Users\me\AppData\Local\Temp\helm\repository\fluent-bit-0.20.3.tgz456375323 to C:\Users\me\AppData\Local\Temp\helm\repository\fluent-bit-0.20.3.tgz: rename C:\Users\me\AppData\Local\Temp\helm\repository\fluent-bit-0.20.3.tgz456375323 C:\Users\me\AppData\Local\Temp\helm\repository\fluent-bit-0.20.3.tgz: Access is denied.
helm.go:88: [debug] rename C:\Users\me\AppData\Local\Temp\helm\repository\fluent-bit-0.20.3.tgz456375323 C:\Users\me\AppData\Local\Temp\helm\repository\fluent-bit-0.20.3.tgz: Access is denied.
link error: cannot rename C:\Users\me\AppData\Local\Temp\helm\repository\fluent-bit-0.20.3.tgz456375323 to C:\Users\me\AppData\Local\Temp\helm\repository\fluent-bit-0.20.3.tgz
helm.sh/helm/v3/internal/third_party/dep/fs.renameFallback
        helm.sh/helm/v3/internal/third_party/dep/fs/rename_windows.go:64
helm.sh/helm/v3/internal/third_party/dep/fs.RenameWithFallback
        helm.sh/helm/v3/internal/third_party/dep/fs/fs.go:62
helm.sh/helm/v3/internal/fileutil.AtomicWriteFile
        helm.sh/helm/v3/internal/fileutil/fileutil.go:50
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
        helm.sh/helm/v3/pkg/downloader/chart_downloader.go:110
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
        helm.sh/helm/v3/pkg/action/install.go:753
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:194
main.newTemplateCmd.func2
        helm.sh/helm/v3/cmd/helm/template.go:82
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371
install.go:199: [debug] CHART PATH: C:\Users\me\AppData\Local\Temp\helm\repository\fluent-bit-0.20.3.tgz
install.go:199: [debug] CHART PATH: C:\Users\me\AppData\Local\Temp\helm\repository\fluent-bit-0.20.3.tgz
```

### PR DESCRIPTION
**Pull request by orgads**
**What this PR does / why we need it**:
When multiple processes try to download the same chart version concurrently (e.g., via Terraform), they can race to write the destination file. On Windows, this results in 'Access Denied' errors because the file cannot be renamed while another process has a handle to the destination.

This commit introduces 'PlatformAtomicWriteFile' to the fileutil package. On Unix-like systems, it simply delegates to AtomicWriteFile, maintaining existing behavior. On Windows, it coordinates writes using a lock file (.lock). It acquires the lock, then performs the atomic write.

Crucially, this implementation ensures that existing files are overwritten (rather than skipped). This ensures that if a chart is republished with the same version, the local cache is correctly updated, preventing stale data issues.

Fixes #31633

Signed-off-by: Orgad Shaneh <orgad.shaneh@audiocodes.com>

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [X] this PR contains unit tests
- [X] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by TerryHowe — COMMENTED** [review]
You might want to wait for feedback on other maintainers, but maybe make a LockedAtomicWirteFile to fileutils instead of this and definitely don't use a goto in that.

**Comment by orgads** [comment]
> You might want to wait for feedback on other maintainers, but maybe make a LockedAtomicWirteFile to fileutils instead of this and definitely don't use a goto in that.

Thank you! Done.

**Comment by orgads** [comment]
ping?

File: internal/fileutil/fileutil.go [hunk 1]
```diff
@@ -48,3 +50,35 @@ func AtomicWriteFile(filename string, reader io.Reader, mode os.FileMode) error
...
+// LockedAtomicWriteFile atomically writes a file to disk with file locking to prevent
+// concurrent writes. This is particularly useful on Windows where concurrent writes
+// to the same file can cause "Access Denied" errors.
+//
+// The function acquires a lock on the target file, checks if it already exists,
+// and only writes if it doesn't exist. This prevents duplicate work when multiple
+// processes try to write the same file simultaneously.
+//
+// Returns true if the file was written, false if it already existed.
+func LockedAtomicWriteFile(filename string, data []byte, mode os.FileMode) (bool, error) {
```
Comment (TerryHowe) [inline internal/fileutil/fileutil.go]: Why are you passing bytes here instead of the Reader?

Comment (orgads) [reply internal/fileutil/fileutil.go]: Good point. Done.

**Comment by orgads** [comment]
ping

**Comment by orgads** [comment]
Please review this. It hits me all the time when working on Windows. See hashicorp/terraform-provider-helm#1683.

File: internal/fileutil/fileutil.go [hunk 2]
```diff
@@ -48,3 +50,34 @@ func AtomicWriteFile(filename string, reader io.Reader, mode os.FileMode) error
...
+//
+// The function acquires a lock on the target file, checks if it already exists,
+// and only writes if it doesn't exist. This prevents duplicate work when multiple
+// processes try to write the same file simultaneously.
+//
+// Returns true if the file was written, false if it already existed.
+func LockedAtomicWriteFile(filename string, reader io.Reader, mode os.FileMode) (bool, error) {
+	// Acquire a file lock for this specific file path to prevent concurrent writes
+	fileLock := flock.New(filename + ".lock")
+	if err := fileLock.Lock(); err != nil {
```
Comment (TerryHowe) [inline internal/fileutil/fileutil.go]: Should this to a `fileLock.TryLock()` instead? If that fails, it is probably being written by another thread/process would be my understanding.

I'm not entirely sure how flock works, but couldn't you just use the file as the lock file?

Messing around with flock on mac and `fileLock` file is not removed so this will leave junk around.

File: internal/fileutil/fileutil.go [hunk 3]
```diff
@@ -48,3 +50,34 @@ func AtomicWriteFile(filename string, reader io.Reader, mode os.FileMode) error
...
+		return false, err
+	}
+	defer fileLock.Unlock()
+
+	// Check if the file already exists (another process might have already written it)
```
Comment (TerryHowe) [inline internal/fileutil/fileutil.go]: If you use TryLock, you'd probably want to change this to look the returned `FileInfo.Size()` here.

**Review by TerryHowe — CHANGES_REQUESTED** [review]

File: internal/fileutil/fileutil.go (hunk 2 above)
Comment (orgads) [reply internal/fileutil/fileutil.go]: @TerryHowe Thank you for the thorough review! You were absolutely right about the lock file cleanup issue.

## Changes made:

1. **Lock file cleanup**: You're correct that `.lock` files were being left behind as "junk" on Mac (and other systems). The `flock` library only releases the lock but doesn't remove the file. I've added explicit cleanup:
```go
defer func() {
    fileLock.Unlock()
    // Clean up the lock file to avoid leaving "junk" around
    os.Remove(lockFileName)
}()
```
This ensures the .lock file is removed after use, addressing your concern.

2. Why we can't use the target file as lock: After testing, I discovered that on Windows, flock.Lock() creates an empty file if the target doesn't exist. This breaks atomic writes:
- Lock creates empty target file
- Code sees file exists and skips writing content
- Result: empty files instead of actual chart data
3. Lock() vs TryLock(): Keeping Lock() for serialized access without retry complexity.
4. Enhanced test: Added comprehensive verification:
- File is not empty
- File has correct size (matches source)
- File has valid gzip magic bytes (0x1f 0x8b)
- No lock file is left behind

Testing:

- ✅ Lock files are properly cleaned up (test verifies this)
- ✅ Concurrent writes work correctly (only one writes, others skip)
- ✅ Test verifies actual content is written, not empty files
- ✅ Test catches both empty file bug and lock file cleanup issues
- ✅ All downloader tests pass

The implementation now handles concurrent writes correctly while cleaning up lock files to avoid leaving junk around, with tests ensuring both behaviors work properly.

**Review by TerryHowe — DISMISSED** [review]
/lgtm

**Comment by orgads** [comment]
ping?

**Comment by orgads** [comment]
Anybody? @gjenkins8 @robertsirc @scottrigby?

**Comment by SeanKilleen** [comment]
Especially with the Helm 4.0 announcement, it would be great to get this in so that the basics of Helm continue to work solidly for everyone. I hit this issue multiple times per day.

I noticed it's linked to an issue that appears to be auto-closed. I wonder if a new issue being opened and linked to this would get it the attention it deserves?

**Comment by TerryHowe** [comment]
Closes: https://github.com/helm/helm/issues/31633

**Comment by orgads** [comment]
> Closes: #31633

Updated the commit message and the PR description.

**Review by banjoh — APPROVED** [review]
LGTM

**Review by banjoh — DISMISSED** [review]

**Comment by SeanKilleen** [comment]
What is the process for this PR to be reviewed and approved by one additional person?

Asking because there was a comment on the issue that the PR is stale, but it's already received one approval and is just pending (presumably) 1 more approval.

Asking as the non-author, because I have hit this issue 4 times now during attempted Helm deployments this morning and am very much looking forward to the symptom being resolved. :)

**Comment by orgads** [comment]
I just gave up and switched to WSL. It works much better.

**Comment by SeanKilleen** [comment]
> I just gave up and switched to WSL. It works much better.

I'd consider that except I'm working with a team whose understanding and familiarity with WSL varies. Hopefully this PR can get the one additional approval it needs and get things resolved. 🤞

File: pkg/downloader/chart_downloader.go [hunk 4]
```diff
@@ -156,7 +156,11 @@ func (c *ChartDownloader) DownloadTo(ref, version, dest string) (string, *proven
 	}
 
 	destfile := filepath.Join(dest, name)
-	if err := fileutil.AtomicWriteFile(destfile, data, 0644); err != nil {
+
+	// Use LockedAtomicWriteFile to handle concurrent writes safely
+	// This prevents "Access Denied" errors on Windows when multiple processes
+	// try to write to the same file simultaneously
+	if _, err := fileutil.LockedAtomicWriteFile(destfile, data, 0644); err != nil {
```
Comment (gjenkins8) [inline pkg/downloader/chart_downloader.go]: I don't think we should change the behavior on non-windows. Linux (for example) doesn't have the problem mention in https://github.com/helm/helm/issues/31633 I believe.

To do this, build target specific tags would/should be used. ref: https://go.dev/wiki/TargetSpecific

Comment (orgads) [reply pkg/downloader/chart_downloader.go]: Even if the file is not locked, having multiple concurrent writers to the same file is bad and can lead to unexpected behavior.

**Comment by SeanKilleen** [comment]
Hi all -- I see @gjenkins8 reviewed this and added a comment and @orgads responded in a few hours. That was 3 weeks ago. Coming back to this thread because I was once again blocked on a deployment and had to repeat it 5 times due to the locking issue.

Is there a way we can come to agreement on this? The point @orgads raises makes sense to be in general, and it seems that all the environments would benefit from the change. However, I'm not an expert in this specific stack.

File: pkg/downloader/chart_downloader.go (hunk 4 above)
Comment (orgads) [reply pkg/downloader/chart_downloader.go]: Done.

**Comment by orgads** [comment]
Rebased and separated Windows/non-Windows.

File: internal/fileutil/fileutil_unix.go [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+		// File already exists, skip writing
+		return false, nil
+	}
+
+	// File doesn't exist, write it atomically
+	if err := AtomicWriteFile(filename, reader, mode); err != nil {
+		return false, err
+	}
+
+	return true, nil
```
Comment (TerryHowe) [inline internal/fileutil/fileutil_unix.go]: I'd be curious what others think, but I'd be inclined to go this direction to preserve current behavior.
```suggestion
	return true, AtomicWriteFile(filename, reader, mode)
```

Another thing is this is not locked at all. Since we are ignoring the written bool, maybe call this something like `PlatformAtomicWriteFile`  and it just calls `AtomicWriteFile` here and `LockedAtomicWriteFile` for windows.

Comment (joejulian) [reply internal/fileutil/fileutil_unix.go]: I agree. The current PR changes the behavior and will break re-publishing charts with the same version/name.

**Review by joejulian — CHANGES_REQUESTED** [review]
This breaks existing behavior. It will leave stale chart/provenance data if a chart is republished with the same version/name

File: internal/fileutil/fileutil_unix.go (hunk 5 above)
Comment (orgads) [reply internal/fileutil/fileutil_unix.go]: Done

**Review by joejulian — APPROVED** [review]
lgtm, thanks!

**Review by TerryHowe — APPROVED** [review]
/lgtm

I don't have a windows system atm to test this, but looks good

**Comment by SeanKilleen** [comment]
Thank you @joejulian and @TerryHowe for giving this the reviews it needs. Thank you to @orgads for continuing to work on this and get it across the finish line 🎉 

It seems like there's nothing blocking this at this point from being merged and getting into the release cycle. I and other Helm users on Windows will be grateful for that!
