### PR TITLE
Return empty string instead of nil when linting on required

### LINKED ISSUE #4747: lint against a template with required behaves oddly
Output of `helm version`: 2.11.0

Since #4221 was merged I started playing around with removing some of my internal `required` checks in CI and I noticed an interesting behaviour which I'm unsure if it is a bug or not.

Looks to be due to it is allowing `nil` through unhindered which does not work great when doing something like `required "API Token required" .token | b64enc | quote`

Running `helm lint` against a template with `required` which then feeds into ` b64enc`:

```
helm lint
[INFO] Missing required value: API Token required
==> Linting .
[ERROR] templates/: render error in "templates/secrets.yaml": template: templates/secrets.yaml:9:77: executing "templates/secrets.yaml" at <b64enc>: invalid value; expected string

Error: 1 chart(s) linted, 1 chart(s) failed
```

When I placed an empty string in values.yaml or did an inline `default` - note, it has to be done with `()` otherwise `required` throws about too many args or similar

```
helm lint
[INFO] Missing required value: API Token required
==> Linting .

1 chart(s) linted, no failures
```

The other oddness is how the info message happens prior to `==> Linting`

### PR DESCRIPTION
**Pull request by helgi**
This allows lint to work in scenarios when required is used in secrets or it's output is passed to another function.

Due to lint mode no longer failing on missing value in required it is passing nil through which not all functions can accept.

Fixes #4747

### CODE REVIEW

File: pkg/engine/engine.go [hunk 1]
```diff
@@ -163,7 +163,8 @@ func (e *Engine) alterFuncMap(t *template.Template) template.FuncMap {
 				log.Printf("[INFO] Missing required value: %s", warn)
 				return val, nil
```
Comment (andytom) [inline pkg/engine/engine.go]: I think you might actually need to change it here so that it doesn't fail during lint mode.
```suggestion
				return "", nil
```

**Comment by helgi** [comment]
Apparently accepting changes with that new GH feature doesn't work with DCO :)

**Review by bacongobbler — APPROVED** [review]

**Comment by bacongobbler** [comment]
This definitely looks like a bug introduced in 2.11. I'll cherry pick this into the next 2.12 release candidate. Thanks @helgi, and sorry for taking so long to get back to you. Thank you for your patience. The tests look great. 👍

**Comment by helgi** [comment]
@bacongobbler Thanks for pulling this in 🥇 💯
