### PR TITLE
Fix pod recreation

### LINKED ISSUE #3372: Flag --recreate-pods broken
The flag `--recreate-pods` no longer works as expected. There are two problems:

- If there is no patch, recreation is not executed. But excactly when there is no patch the flag would be useful. When the feature was added, the function would not immediately return when there was no patch. The following commit seems to have changed this: https://github.com/kubernetes/helm/commit/0f461ba8b55cdfad6d10c8fa9caa658ecddefbd6#diff-a483d6c0863082c3df21f4aad513afe2R394. Was this change intentional?
- Only resources with specific API versions have been eligible for a restart since the check for a selector was introduced in #1956. I'm working on a fix for the first point. I managed to get recreation working for Deployments with APIVersion `extensions/v1beta1` only, not for `apps/v1beta1` onwards. This should not depend on specific APIVersions.

### PR DESCRIPTION
**Pull request by unguiculus**
Fixes #3372.

### CODE REVIEW

File: pkg/kube/client.go [hunk 1]
```diff
@@ -428,40 +428,39 @@ func updateResource(c *Client, target *resource.Info, currentObj runtime.Object,
...
 
-		if force {
-			// Attempt to delete...
-			if err := deleteResource(c, target); err != nil {
+		obj, err := helper.Patch(target.Namespace, target.Name, patchType, patch)
+		if err != nil {
+			kind := target.Mapping.GroupVersionKind.Kind
+			log.Printf("Cannot patch %s: %q (%v)", kind, target.Name, err)
+
+			if force {
```
Comment (pavelnikolov) [inline pkg/kube/client.go]: I would reverse this condition so that the code is more simple (less indented):

```
if !force {
    return err
}

// your force code here
```

Comment (unguiculus) [reply pkg/kube/client.go]: That's existing code I did not touch.

**Comment by mattfarina** [comment]
@adamreese in #1941, where you added support for TPR, you updated the `updateResource` to only recreate when there's a change in resources. Was that intentional? Is there more detail here not captured in the PR?

**Comment by mattfarina** [comment]
@unguiculus Is there a reason that unchanged resources should be restarted? Not debating the point but asking for your justification.

The code change looks ok and I tested that it works (and verified the issue). Prior to merging I just want to make sure there wasn't some intent change.

**Comment by unguiculus** [comment]
@mattfarina I think that's the main (if not only?) reason why this feature is useful. I want to use it in order to recreate pods when nothing changes. This is e. g. the case when you want to redeploy an updated `latest` image. The manifest doesn't change in this case. Not a production use case but sometimes useful for testing. If a Deployment does change, pods are recreated anyways. You don't need this flag then.

**Review by mattfarina — APPROVED** [review]
