### PR TITLE
Fix chartutil.Save returning empty path when passing a non-existent directory (Resolves #6344)

### LINKED ISSUE #6344: Helm package --destination needs to run twice
When running `helm package` with `--destination ./helm/tarballs` and this directory did not exist before, then the command needs to be run twice to succeed:

```
$ rm -rf helm/tarballs/
$ helm package .  --destination ./helm/tarballs/
Successfully packaged chart and saved it to: 
$ helm package .  --destination ./helm/tarballs/
Successfully packaged chart and saved it to: helm/tarballs/mytest-0.1.0.tgz
```
The chart tarball is only written on the second execution. 

Output of `helm version`: v3.0.0.beta.2

Output of `kubectl version`: v1.15.3

### PR DESCRIPTION
**Pull request by wxdao**
**What this PR does / why we need it**:

Fix chartutil.Save returning empty path when passing a non-existent directory, which causes `helm package --destination dir` has to be run twice when `dir` doesn't exist (#6344).

**If applicable**:
- [ ] this PR contains documentation
- [X] this PR contains unit tests
- [X] this PR has been tested for backwards compatibility

### CODE REVIEW

File: pkg/chartutil/save_test.go [hunk 1]
```diff
@@ -33,37 +34,39 @@ func TestSave(t *testing.T) {
...
-	c2, err := loader.LoadFile(where)
-	if err != nil {
-		t.Fatal(err)
-	}
-	if c2.Name() != c.Name() {
-		t.Fatalf("Expected chart archive to have %q, got %q", c.Name(), c2.Name())
-	}
-	if len(c2.Files) != 1 || c2.Files[0].Name != "scheherazade/shahryar.txt" {
-		t.Fatal("Files data did not match")
+	for _, dest := range []string{tmp, path.Join(tmp, "newdir")} {
```
Comment (bacongobbler) [inline pkg/chartutil/save_test.go]: Would you mind changing this to a `t.Run`? That way, these two tests cases can run in parallel. https://golang.org/pkg/testing/#hdr-Subtests_and_Sub_benchmarks

**Review by bacongobbler — CHANGES_REQUESTED** [review]

File: pkg/chartutil/save_test.go (hunk 1 above)
Comment (wxdao) [reply pkg/chartutil/save_test.go]: @bacongobbler Changed it. Thank you!

**Comment by wxdao** [comment]
Hi @bacongobbler. When will you be available to review my PR? I've just resolved a conflict to the upstream. It seems that another PR #6177 has applied the same fix with different motivation. However I think my PR still makes sense since it adds an essential test to avoid future mistakes.

**Comment by bacongobbler** [comment]
Hi @wxdao, sorry for not getting back to you sooner. Right now we are trying to arrange PR reviews for the 3.0.0-beta.4 release, making sure that things are merged smoothly. I'll put this on the beta.4 milestone so we don't lose track of this bugfix. Thanks again!

File: pkg/chartutil/save.go [hunk 2]
```diff
@@ -93,7 +93,7 @@ func Save(c *chart.Chart, outDir string) (string, error) {
 	filename := fmt.Sprintf("%s-%s.tgz", c.Name(), c.Metadata.Version)
 	filename = filepath.Join(outDir, filename)
 	if stat, err := os.Stat(filepath.Dir(filename)); os.IsNotExist(err) {
-		if err := os.MkdirAll(filepath.Dir(filename), 0755); !os.IsExist(err) {
+		if err := os.MkdirAll(filepath.Dir(filename), 0755); err != nil {
```
Comment (hickeyma) [inline pkg/chartutil/save.go]: Will this fail if the directory already exists? Is this expected  behaviour?

If not then maybe the check should be something like this:
`if err != nil && !os.IsExist(err)`

**Review by hickeyma — CHANGES_REQUESTED** [review]

File: pkg/chartutil/save.go (hunk 2 above)
Comment (wxdao) [reply pkg/chartutil/save.go]: Thanks for reviewing this. It seems that os.MkdirAll will only be called when the outer if fails, i.e. os.IsNotExist == true. So it wouldn't try to mkdir an existing directory, isn't it?

Comment (hickeyma) [reply pkg/chartutil/save.go]: That is correct. From API: "If path is already a directory, MkdirAll does nothing and returns nil."

**Review by hickeyma — APPROVED** [review]
lGTM, thanks @wxdao.
