### PR TITLE
fix(helm): fix output of helm package command

### LINKED ISSUE #672: fix output of `helm package`
```
helm [master*]$ ../helm/helm package ../../docs/examples/alpine/
Saved /Users/michellenoorali/.helm/local/alpine-0.1.0.tgz to $HELM_HOME/localSaved /Users/michellenoorali/gocode/src/github.com/kubernetes/helm/cmd/helm/alpine-0.1.0.tgz to current directory
```

should throw a newline in there

### PR DESCRIPTION
**Pull request by technosophos**
Closes #672

### CODE REVIEW

File: cmd/helm/package.go [hunk 1]
```diff
@@ -54,21 +54,25 @@ func runPackage(cmd *cobra.Command, args []string) error {
...
 		return err
 	}
 	name, err := chart.Save(ch, cwd)
-	if err == nil {
+	if err == nil && flagVerbose {
 		cmd.Printf("Saved %s to current directory\n", name)
 	}
+
+	// Save to $HELM_HOME/local directory. This is second, because we don't want
+	// the case where we saved here, but didn't save to the default destination.
```
Comment (michelleN) [inline cmd/helm/package.go]: 👍
