### PR TITLE
fix(cmd): acquire repository.lock

### LINKED ISSUE #6682: ...\repositories.yaml: The process cannot access the file...
I am trying Helm 3 Beta 4 and am running into an issue when trying to add a repo.  When I try the same thing with Beta 3 I do not get the error.

**Command**
helm repo add stable https://kubernetes-charts.storage.googleapis.com/

**Result**
Error: read C:\Users\me\AppData\Roaming\helm\repositories.yaml: The process cannot access the file because another process has locked a portion of the file.

Output of `helm version`:
version.BuildInfo{Version:"v3.0.0-beta.4", GitCommit:"7ffc879f137bd3a69eea53349b01f05e3d1d2385", GitTreeState:"dirty", GoVersion:"go1.13.1"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Docker for Windows

### PR DESCRIPTION
**Pull request by bacongobbler**
closes #6682

Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>

### CODE REVIEW

File: cmd/helm/repo_add.go [hunk 1]
```diff
@@ -85,8 +85,8 @@ func (o *repoAddOptions) run(out io.Writer) error {
 		return err
 	}
 
-	// Lock the repository file for concurrent goroutines or processes synchronization
-	fileLock := flock.New(o.repoFile)
+	// Acquire a file lock for process synchronization
+	fileLock := flock.New(o.repoFile[0:len(o.repoFile)-len(filepath.Ext(o.repoFile))] + "lock")
```
Comment (thomastaylor312) [inline cmd/helm/repo_add.go]: Non-blocking nit: This might read clearer with a `strings.Replace(o.repoFile, filepath.Ext(o.repoFile), "lock", 1)`

**Review by thomastaylor312 — APPROVED** [review]

File: cmd/helm/repo_add.go (hunk 1 above)
Comment (bacongobbler) [reply cmd/helm/repo_add.go]: I like cleaner code

Comment (bacongobbler) [reply cmd/helm/repo_add.go]: While this may work, it is a little risky doing it this way. `strings.Replace` replaces the first occurrence of the string. If we eventually exposed this as a public API, `repoFile` could be something other than repository.yaml.

in which case one could imagine passing a file called `repository.repo` or something similar, which would end up as `locksitory.repo`.

https://play.golang.org/p/znzd61mfU8l
