### PR TITLE
fix(pkg/strvals): preserve leading zeros in vals

### LINKED ISSUE #2693: integer with leading zero gets truncated
Hi there,
I use short git commit hashes as docker tags and stumbled across a issue with helm.

```
Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
```

## Issue
helm truncates integers with leading zeros.

## Example

`helm install --namespace tools --set deployment.dockerTag=0474915 helm/elastalert --debug --dry-run`  results in this:

```
USER-SUPPLIED VALUES:
deployment:
  dockerTag: 474915
```

```
spec:
      containers:
      - name: elastalert
        image: my-registry/elastalert:474915
```

The leading zero `0` gets truncated by helm which results in a kubernetes `imagePullError`.

I tried different quoting techniques with single and double quotes:
```
--set 'deployment.dockerTag=0474915'
--set "deployment.dockerTag=0474915"
--set deployment.dockerTag='0474915'
--set deployment.dockerTag="0474915"
```
All of them resulting in the same behavior described above.

this is the line from my template:
`image: {{ .Values.global.dockerRegistry }}/{{ .Values.deployment.dockerImage }}:{{ .Values.deployment.dockerTag }}`

Is there a way to stop helm from converting my values?

### PR DESCRIPTION
**Pull request by rbwsam**
When passing values with "helm install --set" values with leading zeros are
preserved and not parsed as ints.

Closes #2693

### CODE REVIEW

File: pkg/strvals/parser.go [hunk 1]
```diff
@@ -308,8 +308,11 @@ func typedVal(v []rune) interface{} {
 		return false
 	}
 
-	if iv, err := strconv.ParseInt(val, 10, 64); err == nil {
-		return iv
+	// If this value does not start with zero, try parsing it to an int
+	if len(val) != 0 && val[0] != 48 {
```
Comment (bacongobbler) [inline pkg/strvals/parser.go]: out of curiosity/lack of understanding, what does 48 translate to in this situation?

Comment (rbwsam) [inline pkg/strvals/parser.go]: 48 is the ASCII value for `0`. Thanks for pointing this out, this prompted me to learn more about runes and I found out that a better implementation would be to use a rune literal `'0'` instead which better communicates the intent of the code.

**Review by thomastaylor312 — APPROVED** [review]
Tested this and it looks good to go
