### PR TITLE
fix: Delay test hook deletion until after logs are retrieved with `helm test release --logs`

### LINKED ISSUE #9098: Helm test --logs fails with hook-delete-policy "hook-failed" or "hook-succeed"
When I execute:

`helm test <release> --logs`

I get the following error:

`unable to get pod logs for <release>: pods "<release>" not found`

This only happens, if I set `helm.sh/hook-delete-policy` to `hook-failed` or `hook-succeeded`

While in general, it makes sense that no logs can be retrieved, if the test pod was deleted, in Helm2 this used to work. The logs were retrieved before deletion of the pods.

Output of `helm version`: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

### PR DESCRIPTION
**Pull request by benoittgt**
**What this PR does / why we need it**:

This is a rebase of #10603

Fixing a [very old issue](https://github.com/helm/helm/pull/10603) with frequent activity from users.

When running `helm test <release-name> --logs`, test pods with `hook-succeeded` delete policy were being deleted before logs could be retrieved, resulting in "pods not found" errors. This PR delays the execution of hook deletion until after logs have been successfully retrieved.

**Special notes for your reviewer**:

Tested with a chart 
1. `helm create test-chart`
2. Modify the `tests/test-connection.yaml` generated file by adding one annotation `"helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded`
3. Run test
  ```
  helm test new-chart --logs        
NAME: new-chart
LAST DEPLOYED: Wed Nov 26 17:18:45 2025
NAMESPACE: default
STATUS: deployed
REVISION: 2
DESCRIPTION: Upgrade complete
TEST SUITE:     new-chart-test-connection
Last Started:   Wed Nov 26 17:18:48 2025
Last Completed: Wed Nov 26 17:18:51 2025
Phase:          Succeeded

Error: unable to get pod logs for new-chart-test-connection: pods "new-chart-test-connection" not found
```
4. With this branch
```
bin/helm test new-chart --logs
NAME: new-chart
LAST DEPLOYED: Wed Nov 26 17:18:45 2025
NAMESPACE: default
STATUS: deployed
REVISION: 2
DESCRIPTION: Upgrade complete
TEST SUITE:     new-chart-test-connection
Last Started:   Wed Nov 26 17:20:04 2025
Last Completed: Wed Nov 26 17:20:08 2025
Phase:          Succeeded

POD LOGS: new-chart-test-connection
Connecting to new-chart:80 (192.168.194.168:80)
saving to 'index.html'
index.html           100% |********************************|   612  0:00:00 ETA
'index.html' saved
``` 

Fixes #9098
Closes: #10603

**If applicable**:
- [ ] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

File: pkg/action/hooks.go [hunk 1]
```diff
@@ -33,6 +33,27 @@ import (
 
 // execHook executes all of the hooks for the given hook event.
 func (cfg *Configuration) execHook(rl *release.Release, hook release.HookEvent, waitStrategy kube.WaitStrategy, timeout time.Duration, serverSideApply bool) error {
+	shutdown, err := cfg.execHookWithDelayedShutdown(rl, hook, waitStrategy, timeout, serverSideApply)
+	if shutdown == nil {
+		return nil
```
Comment (banjoh) [inline pkg/action/hooks.go]: Return the error if there was one.

```suggestion
		return err
```

File: pkg/action/hooks.go [hunk 2]
```diff
@@ -33,6 +33,27 @@ import (
...
+			return err
+		}
+		return err
+	}
+	return shutdown()
+}
+
+type ExecuteShutdownHooks = func() error
+
+func ShutdownNoOp() error {
```
Comment (banjoh) [inline pkg/action/hooks.go]: I'd leave this privately scoped (`shutdownNoOp`) and make it public only if necessary. It allow flexibility of making changes later on

File: pkg/action/hooks.go [hunk 3]
```diff
@@ -33,6 +33,27 @@ import (
...
+	if err != nil {
+		if err := shutdown(); err != nil {
+			return err
+		}
+		return err
+	}
+	return shutdown()
+}
+
+type ExecuteShutdownHooks = func() error
```
Comment (banjoh) [inline pkg/action/hooks.go]: I'd leave this privately scoped (`executeShutdownHooks`) and make it public only if necessary. It allow flexibility of making changes later on

**Review by banjoh — COMMENTED** [review]
Changes look good overall. I left a few comments

File: pkg/action/hooks.go (hunk 3 above)
Comment (banjoh) [inline pkg/action/hooks.go]: nit pick: Rename to executeShutdownFunc to depict its purpose as a function

File: pkg/action/hooks.go (hunk 1 above)
Comment (benoittgt) [reply pkg/action/hooks.go]: Thanks. Good idea. I’ve addressed all your requests.

File: pkg/action/hooks.go (hunk 3 above)
Comment (benoittgt) [reply pkg/action/hooks.go]: Linting is not happy

```
pkg/action/release_testing.go:60:57: unexported-return: exported method Run returns unexported type action.executeShutdownFunc, which can be annoying to use (revive)
func (r *ReleaseTesting) Run(name string) (ri.Releaser, executeShutdownFunc, error) {
```

Comment (banjoh) [reply pkg/action/hooks.go]: That's a valid point. I guess we can leave this one as-is since its a return variable of a public function

**Review by banjoh — APPROVED** [review]
LGMT

**Comment by benoittgt** [comment]
@TerryHowe do you have feedbacks on this one?

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Comment by benoittgt** [comment]
It seems I have 2 approvals @TerryHowe ? 😊
