### PR TITLE
fix(helm): remove duplicate commands

### LINKED ISSUE #2238: 'helm help' prints duplicate help text (and TLS may not work)
Reported in Slack by @seh.

Certain commands get duplicate help text:

- helm test
- helm reset
- helm version

What appears to have happened is that two merges both changed (conceptually) the same piece of code, but in a way that did not trigger a conflict on merge.

As an odd offshoot, it may be the case that the TLS flags for test, version, and reset do not work.

### PR DESCRIPTION
**Pull request by technosophos**
Closes #2238

### CODE REVIEW

File: cmd/helm/helm.go [hunk 1]
```diff
@@ -139,12 +139,10 @@ func newRootCmd(out io.Writer) *cobra.Command {
 		addFlagsTLS(newReleaseTestCmd(nil, out)),
 		addFlagsTLS(newResetCmd(nil, out)),
 		addFlagsTLS(newVersionCmd(nil, out)),
+
 		newCompletionCmd(out),
 		newHomeCmd(out),
 		newInitCmd(out),
-		newResetCmd(nil, out),
```
Comment (seh) [inline cmd/helm/helm.go]: I confirmed that all three of these are taken care of above [on lines 139-141](https://github.com/technosophos/k8s-helm/blob/1a79c28f45f64967be118d0d684008dd7e493835/cmd/helm/helm.go#L139-L141), where they're decorated with the TLS-related flags.

**Review by seh — APPROVED** [review]

**Review by adamreese — APPROVED** [review]
