### PR TITLE
fix(helm): manifests string parsing works for newlines in the manifests

### LINKED ISSUE #2158: tiller crashes on 'helm test' run when there's blank line in test pod yaml
When there's a blank line at the top of the test pod yaml template, tiller crashes on 'helm test' run.

Here's the problomatic (and rendered) yaml file:
```
(blank line)
---
apiVersion: v1
kind: Pod
metadata:
  name: "keystone-tempest-test"
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
...
```
If I run 'helm test' command, the following error is shown.
```
root@att-helm:~/workspace/openstack-helm# helm test keystone
Error: transport is closing
root@att-helm:~/workspace/openstack-helm# helm test keystone
Error: could not find a ready tiller pod
```
The tiller pod log says:
```
root@att-helm:~# kubectl logs tiller-deploy-3210613906-djz5c -n kube-system
Starting Tiller v2.2.3
GRPC listening on :44134
Probes listening on :44135
Storage driver is ConfigMap
2017/03/22 07:22:15 storage.go:133: Getting release history for 'keystone'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd44c8a]

goroutine 46 [running]:
panic(0x156c840, 0xc42000a030)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/helm/pkg/releasetesting.newTest(0xc42044b400, 0x0, 0x4110f8, 0x40, 0x161d1e0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/releasetesting/test_suite.go:174 +0x11a
k8s.io/helm/pkg/releasetesting.(*TestSuite).Run(0xc4203f9f40, 0xc420587b90, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/releasetesting/test_suite.go:72 +0x9a
k8s.io/helm/pkg/tiller.(*ReleaseServer).RunReleaseTest(0xc42021ad00, 0xc42040b8a0, 0x1ff05c0, 0xc4204082e0, 0x0, 0x18)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/tiller/release_server.go:1100 +0x244
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_RunReleaseTest_Handler(0x16c8d20, 0xc42021ad00, 0x1fefcc0, 0xc420089440, 0xc4202becb8, 0x4110f8)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:928 +0x117
k8s.io/helm/pkg/tiller.newStreamInterceptor.func1(0x16c8d20, 0xc42021ad00, 0x1fefcc0, 0xc420089440, 0xc42040b840, 0x17e0aa0, 0xc4202d5400, 0x4111d8)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/pkg/tiller/server.go:63 +0x112
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc4200d3080, 0x1ff0740, 0xc4200893b0, 0xc4200cb1d0, 0xc42043a720, 0x2035960, 0xc42029ff20, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:723 +0x2b6
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200d3080, 0x1ff0740, 0xc4200893b0, 0xc4200cb1d0, 0xc42029ff20)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:800 +0xc36
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420408140, 0xc4200d3080, 0x1ff0740, 0xc4200893b0, 0xc4200cb1d0)
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:449 +0xab
created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/ubuntu/.go_workspace/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:450 +0xa3
```

This issue only takes place with 'helm test' command. 
If I remove the '"helm.sh/hook": test-success' from the above yaml file so that the pod can be launched by 'helm install' command, it just worked fine without any error.

Test Environment
- Helm version: 2.2.3
- OS: Ubuntu 16.04

### PR DESCRIPTION
**Pull request by anubhavmishra**
Now new line such as:
```
(blank line)
---
apiVersion: v1
kind: Pod
metadata:
  name: "keystone-tempest-test"
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
...
```
doesn't return a whitespace while parsing through the manifests.

Trying to fix #2158

### CODE REVIEW

File: pkg/releaseutil/manifest.go [hunk 1]
```diff
@@ -40,7 +40,9 @@ func SplitManifests(bigfile string) map[string]string {
 	sep := "\n---\n"
 	tpl := "manifest-%d"
 	res := map[string]string{}
-	tmp := strings.Split(bigfile, sep)
+	// Making sure yaml formatting doesn't matter when generating manifest from string.
+	bigFileTmp := strings.TrimSpace(bigfile)
+	tmp := strings.Split(bigFileTmp, sep)
```
Comment (seh) [inline pkg/releaseutil/manifest.go]: - [ ] How about using [`(*regexp.Regexp).Split`](https://golang.org/pkg/regexp/#Regexp.Split) instead?  
  It looks like you want to match a YAML document separator with any amount of whitespace around it. Note that [a YAML document starting boundary marker](http://yaml.org/spec/current.html#c-document-start) must occur at the beginning of the line. Hence, I recommend the following regular expression:
```(?:^|\\s*\n)---\\s*```
That is, the boundary marker is either at the beginning of the document of occurring after a newline, but preceded by any amount of whitespace.  

  [Here's a sample using this technique in the Go playground.](https://play.golang.org/p/FsdylWkbWU)

**Review by seh — CHANGES_REQUESTED** [review]

File: pkg/releaseutil/manifest.go [hunk 2]
```diff
@@ -40,7 +40,9 @@ func SplitManifests(bigfile string) map[string]string {
 	sep := "\n---\n"
 	tpl := "manifest-%d"
 	res := map[string]string{}
-	tmp := strings.Split(bigfile, sep)
+	// Making sure yaml formatting doesn't matter when generating manifest from string.
```
Comment (seh) [inline pkg/releaseutil/manifest.go]: - [ ] While we're here, capitalize the word "YAML":  
> Make sure that any extra whitespace in the YAML stream doesn't preclude splitting its documents.

File: pkg/releaseutil/manifest.go [hunk 3]
```diff
@@ -37,12 +38,12 @@ func SplitManifests(bigfile string) map[string]string {
 	// Basically, we're quickly splitting a stream of YAML documents into an
 	// array of YAML docs. In the current implementation, the file name is just
 	// a place holder, and doesn't have any further meaning.
-	sep := "\n---\n"
+	sep := regexp.MustCompile("(?:^|\\s*\n)---\\s*")
 	tpl := "manifest-%d"
 	res := map[string]string{}
-	// Making sure yaml formatting doesn't matter when generating manifest from string.
+	// Making sure YAML formatting doesn't matter when generating manifest from string.
 	bigFileTmp := strings.TrimSpace(bigfile)
```
Comment (seh) [inline pkg/releaseutil/manifest.go]: - [ ] There's no need for this call, given that the regular expression defined at line 41 already eats the space surrounding the boundary marker.

File: pkg/releaseutil/manifest.go [hunk 4]
```diff
@@ -37,12 +38,12 @@ func SplitManifests(bigfile string) map[string]string {
 	// Basically, we're quickly splitting a stream of YAML documents into an
 	// array of YAML docs. In the current implementation, the file name is just
 	// a place holder, and doesn't have any further meaning.
-	sep := "\n---\n"
+	sep := regexp.MustCompile("(?:^|\\s*\n)---\\s*")
```
Comment (seh) [inline pkg/releaseutil/manifest.go]: - [ ] Consider declaring this as a top-level `var`.  
  Doing so avoids compiling the regular expression on every invocation, though I don't know how often this function will be called.

File: pkg/releaseutil/manifest.go [hunk 5]
```diff
@@ -37,12 +38,12 @@ func SplitManifests(bigfile string) map[string]string {
...
 	tpl := "manifest-%d"
 	res := map[string]string{}
-	// Making sure yaml formatting doesn't matter when generating manifest from string.
+	// Making sure YAML formatting doesn't matter when generating manifest from string.
```
Comment (seh) [inline pkg/releaseutil/manifest.go]: - [ ] [As suggested earlier](https://github.com/kubernetes/helm/pull/2190#discussion_r108066539), consider revising this comment, as it doesn't read properly in American English.  
  > Make sure that any extra whitespace in the YAML stream doesn't preclude splitting its documents.

File: pkg/releaseutil/manifest.go [hunk 6]
```diff
@@ -37,12 +38,12 @@ func SplitManifests(bigfile string) map[string]string {
...
 	bigFileTmp := strings.TrimSpace(bigfile)
-	tmp := strings.Split(bigFileTmp, sep)
+	tmp := sep.Split(bigFileTmp, -1)
```
Comment (seh) [inline pkg/releaseutil/manifest.go]: - [ ] `tmp` is an odd name here, as all of these variables are "temporary."  
  Instead, use "docs" for a sequence of YAML documents.

**Review by seh — CHANGES_REQUESTED** [review]
I wasn't clear enough in my previous suggestion, which I intended to eliminate the need for trimming the file content explicitly.

File: pkg/releaseutil/manifest.go (hunk 3 above)
Comment (anubhavmishra) [inline pkg/releaseutil/manifest.go]: Sorry! That was my bad, I wasn't paying attention.

**Comment by anubhavmishra** [comment]
@thomastaylor312 this doesn't fix #2158. Just helps with better parsing of YAML string.

File: pkg/releaseutil/manifest.go [hunk 7]
```diff
@@ -31,17 +31,19 @@ type SimpleHead struct {
 	} `json:"metadata,omitempty"`
 }
 
+var sep = regexp.MustCompile("(?:^|\\s*\n)---\\s*")
```
Comment (seh) [inline pkg/releaseutil/manifest.go]: In the interest of full disclosure, I'll note that it's _possible_—though I don't think Kubernetes does so—that the YAML stream could also include a positive number of [_ending_ document boundary markers](http://yaml.org/spec/current.html#c-document-end) ("...") before the starting one ("---"). Accommodating those—including any intervening comments that would be valid—with a regular expression is impractical.

**Review by seh — APPROVED** [review]

**Comment by anubhavmishra** [comment]
@thomastaylor312 can we merge this?

**Comment by thomastaylor312** [comment]
@anubhavmishra Sorry for the delay on this. I am a 1 man show this week, so I have been a bit backlogged. I will get to this tomorrow. Luckily, @seh already did a good review so it should be fairly simple for me

**Comment by anubhavmishra** [comment]
@thomastaylor312 its all good! Just wondering what was up haha 😄

File: pkg/releaseutil/manifest.go (hunk 7 above)
Comment (seh) [inline pkg/releaseutil/manifest.go]: I intend to add these boundary markers (both starting and ending) in a fix for #2181.

File: pkg/releaseutil/manifest.go [hunk 8]
```diff
@@ -31,17 +31,19 @@ type SimpleHead struct {
...
+
 // SplitManifests takes a string of manifest and returns a map contains individual manifests
 func SplitManifests(bigfile string) map[string]string {
 	// This is not the best way of doing things, but it's how k8s itself does it.
```
Comment (thomastaylor312) [inline pkg/releaseutil/manifest.go]: I am guessing that since you changed this, it no longer holds true. Can you update this comment to reflect the new code?

**Review by thomastaylor312 — COMMENTED** [review]
One small fix to a comment @anubhavmishra and this is ready to go

**Review by thomastaylor312 — APPROVED** [review]

File: pkg/releaseutil/manifest.go (hunk 1 above)
Comment (technosophos) [inline pkg/releaseutil/manifest.go]: This is a good idea.
