### PR TITLE
fix: --dry-run=server now respect generateName

### LINKED ISSUE #31509: [Helm 4]  --dry-run=server with "generateName" creates error
### What happened?

Running `helm template . --dry-run=server` when a template contains `generateName`  generates an error. This used to work before helm 4.

```
Error: unable to continue with install: could not get information about the resource Job "" in namespace "hello-world": resource name may not be empty
```

### What did you expect to happen?

No error.

### How can we reproduce it (as minimally and precisely as possible)?

Run `helm template . --dry-run=server` with the template below:

```
apiVersion: batch/v1
kind: Job
metadata:
  generateName: "hello-world-"
spec:
  template:
    spec:
      containers:
        - name: "hello-world"
          image: "hello-world"
      restartPolicy: Never

```

Error:

```
Error: unable to continue with install: could not get information about the resource Job "" in namespace "hello-world": resource name may not be empty
```

### Helm version

<details>

```console
$ helm version
version.BuildInfo{Version:"v4.0.0", GitCommit:"99cd1964357c793351be481d55abbe21c6b2f4ec", GitTreeState:"clean", GoVersion:"go1.25.3", KubeClientVersion:"v1.34"}
```
</details>

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.34.2
Kustomize Version: v5.7.1
Server Version: v1.34.1
```

</details>

### PR DESCRIPTION
**Pull request by Mujib-Ahasan**
**What this PR does / why we need it**:
Helm4 was facing problem with `--dry-run=server` as it was not respecting the `generateName`. The actual behavior is `generateName` is considered only in CREATE client method, not GET. A simple change is made, if `Name == ""`, this will be skipped to avoid error mentioned in issue #31509.

**Special notes for your reviewer**:
Other changes could also be possible, ex: we could `return` at the very first `Name == ""` instead of `continue`. This PR preferred continue because it is intended. 

**If applicable**:
- [ ] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [ ] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

closes #31509

### CODE REVIEW

File: pkg/kube/resource.go [hunk 1]
```diff
@@ -29,6 +29,9 @@ func (r *ResourceList) Append(val *resource.Info) {
 // Visit implements resource.Visitor. The visitor stops if fn returns an error.
 func (r ResourceList) Visit(fn resource.VisitorFunc) error {
 	for _, i := range r {
+		if i.Name == "" {
```
Comment (gjenkins8) [inline pkg/kube/resource.go]: This function is a generic visitor for any/all scenarios. It should not implement business logic like skipping objects missing a name

**Review by gjenkins8 — CHANGES_REQUESTED** [review]
https://github.com/helm/helm/pull/31563/files#r2554270362

File: pkg/kube/resource.go (hunk 1 above)
Comment (Mujib-Ahasan) [reply pkg/kube/resource.go]: Thank you @gjenkins8 for pointing out. This now make sense to me that general visitor functions must not implement business logic. PTAL at new changes. Hope that would solve the problem.

**Review by gjenkins8 — CHANGES_REQUESTED** [review]
Thanks for the updates!

The logic I think is complete. But can we (perhaps) create a helper function and include test coverage.

**Comment by Mujib-Ahasan** [comment]
Thanks @gjenkins8 for the direction. As you mentioned, I created a helper function for that business logic and added test coverage(each separate commit).

File: pkg/action/validate.go [hunk 2]
```diff
@@ -201,3 +209,14 @@ func mergeStrStrMaps(current, desired map[string]string) map[string]string {
...
+
+func validateNameAndgenerateName(info *resource.Info) (bool, error) {
+	accessor, _ := meta.Accessor(info.Object)
+	if info.Name == "" && accessor.GetGenerateName() != "" {
+		return true, nil
+	} else if info.Name != "" && accessor.GetGenerateName() != "" {
+		return true, fmt.Errorf("metadata.name and metadata.generateName cannot both be set")
+	}
+
+	return false, nil
```
Comment (gjenkins8) [inline pkg/action/validate.go]: The return above make the else redundant here. Removing makes the logic easier to follow:

```suggestion
	accessor, _ := meta.Accessor(info.Object)
	if info.Name == "" && accessor.GetGenerateName() != "" {
		return true, nil
	}
	
	if info.Name != "" && accessor.GetGenerateName() != "" {
		return true, fmt.Errorf("metadata.name and metadata.generateName cannot both be set")
	}

	return false, nil
```

File: pkg/action/validate.go [hunk 3]
```diff
@@ -46,6 +46,11 @@ func requireAdoption(resources kube.ResourceList) (kube.ResourceList, error) {
 			return err
 		}
 
+		skip, err := validateNameAndgenerateName(info)
+		if skip {
```
Comment (gjenkins8) [inline pkg/action/validate.go]:
```suggestion
		isGenerateName, err := validateNameAndgenerateName(info)
		if isGenerateName {
```

and others below..

File: pkg/action/validate.go [hunk 4]
```diff
@@ -201,3 +209,14 @@ func mergeStrStrMaps(current, desired map[string]string) map[string]string {
 	maps.Copy(result, desired)
 	return result
 }
+
+func validateNameAndgenerateName(info *resource.Info) (bool, error) {
```
Comment (gjenkins8) [inline pkg/action/validate.go]:
```suggestion
// validateNameAndgenerateName validates that an object only has either `Name` or `GenerateName` set (and not both)
// If `GenerateName` is set, true is returned
// If an invalid combination of `Name` and `GenerateName` are set, an error is returned
func validateNameAndgenerateName(info *resource.Info) (bool, error) {
```

File: pkg/action/validate.go [hunk 5]
```diff
@@ -201,3 +209,14 @@ func mergeStrStrMaps(current, desired map[string]string) map[string]string {
...
+	accessor, _ := meta.Accessor(info.Object)
```
Comment (gjenkins8) [inline pkg/action/validate.go]: The error should be handled here I think? (any specific reason to not handle?)

```suggestion
	accessor, err := meta.Accessor(info.Object)
	if err != nil {
        ...
```

File: pkg/action/validate.go (hunk 3 above)
Comment (Mujib-Ahasan) [reply pkg/action/validate.go]: Yes, this sounds good!!

File: pkg/action/validate.go (hunk 5 above)
Comment (Mujib-Ahasan) [reply pkg/action/validate.go]: Well, I cannot remember the intension, but handling that would be a better solution. Thank you @gjenkins8

File: pkg/action/validate.go [hunk 6]
```diff
@@ -71,6 +75,11 @@ func existingResourceConflict(resources kube.ResourceList, releaseName, releaseN
 			return err
 		}
 
+		isGenerateName, err := validateNameAndgenerateName(info)
+		if isGenerateName {
```
Comment (gjenkins8) [inline pkg/action/validate.go]:
```suggestion
		if isGenerateName || err != nil {
```

Let's explicitly handle the error, rather than relying on `isGenerateName` being true

File: pkg/action/validate.go [hunk 7]
```diff
@@ -46,6 +46,11 @@ func requireAdoption(resources kube.ResourceList) (kube.ResourceList, error) {
...
```
Comment (gjenkins8) [inline pkg/action/validate.go]:
```suggestion
		if isGenerateName || err != nil {
```

Let's explicitly handle the error, rather than relying on `isGenerateName` being true

File: pkg/action/validate.go [hunk 8]
```diff
@@ -201,3 +209,23 @@ func mergeStrStrMaps(current, desired map[string]string) map[string]string {
...
 	return result
 }
+
+// validateNameAndgenerateName validates that an object only has either `Name` or `GenerateName` set (and not both)
+// If `GenerateName` is set, true is returned
+// If an invalid combination of `Name` and `GenerateName` are set, an error is returned
+func validateNameAndgenerateName(info *resource.Info) (bool, error) {
+	accessor, err := meta.Accessor(info.Object)
+	if err != nil {
+		return true, err
```
Comment (gjenkins8) [inline pkg/action/validate.go]:
```suggestion
		return false, err
```

`GenerateName` has not being determined to be true, we should not return true here

File: pkg/action/validate.go [hunk 9]
```diff
@@ -201,3 +209,23 @@ func mergeStrStrMaps(current, desired map[string]string) map[string]string {
 	maps.Copy(result, desired)
 	return result
 }
+
+// validateNameAndgenerateName validates that an object only has either `Name` or `GenerateName` set (and not both)
+// If `GenerateName` is set, true is returned
+// If an invalid combination of `Name` and `GenerateName` are set, an error is returned
+func validateNameAndgenerateName(info *resource.Info) (bool, error) {
```
Comment (gjenkins8) [inline pkg/action/validate.go]:
```suggestion
func validateNameAndGenerateName(info *resource.Info) (bool, error) {
```

Just noticed (on my final review) the casing isn't correctly "camelCase" here

File: pkg/action/validate.go [hunk 10]
```diff
@@ -201,3 +209,23 @@ func mergeStrStrMaps(current, desired map[string]string) map[string]string {
 	maps.Copy(result, desired)
 	return result
 }
+
+// validateNameAndgenerateName validates that an object only has either `Name` or `GenerateName` set (and not both)
```
Comment (gjenkins8) [inline pkg/action/validate.go]:
```suggestion
// validateNameAndGenerateName validates that an object only has either `Name` or `GenerateName` set (and not both)
```

As below

**Review by gjenkins8 — COMMENTED** [review]
Thanks for the updates! All looks good, except I noticed (on my final pass though looking at the code) the mentioned casing issue

**Comment by Mujib-Ahasan** [comment]
> Thanks for the updates! All looks good, except I noticed (on my final pass though looking at the code) the mentioned casing issue

Thank you @gjenkins8 for the reviews. Changes are made as suggested!

**Review by gjenkins8 — APPROVED** [review]

**Review by banjoh — APPROVED** [review]

**Review by gjenkins8 — APPROVED** [review]
