### PR TITLE
Fix make helm list show all by default

### LINKED ISSUE #9442: List pending releases by default
As the ongoing discussion in https://github.com/helm/helm/issues/8987 and https://github.com/helm/helm/issues/8959 shows, it is surprising that running `helm list` doesn't show pending releases by default.

A common operational situation is:
* `helm upgrade --install ...`
* something happens: ^C, connection drops, chart breaks for some other reason
* `helm list` - where is the release I just tried to upgrade?!

I think this surprising behaviour could be solved by listing pending releases by default. Would you accept a PR to implement this behaviour?

Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
kind v0.10.0 go1.15.7 linux/amd64
```

### PR DESCRIPTION
**Pull request by TerryHowe**
**What this PR does / why we need it**:

Make helm list show all releases by default and remove -a flag

Closes: https://github.com/helm/helm/issues/9442

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

File: pkg/cmd/list.go [hunk 1]
```diff
@@ -117,13 +120,12 @@ func newListCmd(cfg *action.Configuration, out io.Writer) *cobra.Command {
...
-	f.BoolVar(&client.Uninstalling, "uninstalling", false, "show releases that are currently being uninstalled")
-	f.BoolVar(&client.Deployed, "deployed", false, "show deployed releases. If no other is specified, this will be automatically enabled")
-	f.BoolVar(&client.Failed, "failed", false, "show failed releases")
-	f.BoolVar(&client.Pending, "pending", false, "show pending releases")
+	f.BoolVar(&client.Uninstalled, "uninstalled", false, "show only uninstalled releases (if 'helm uninstall --keep-history' was used)")
+	f.BoolVar(&client.Superseded, "superseded", false, "show only superseded releases")
+	f.BoolVar(&client.Uninstalling, "uninstalling", false, "show only releases that are currently being uninstalled")
+	f.BoolVar(&client.Deployed, "deployed", false, "show only deployed releases")
+	f.BoolVar(&client.Failed, "failed", false, "show only failed releases")
+	f.BoolVar(&client.Pending, "pending", false, "show only pending releases")
```
Comment (mattfarina) [inline pkg/cmd/list.go]: If I mix these flags it will list multiple types. For example `--failed --pending` will list both failed and pending releases.

This update added "only" to the description on the flag. Can you remove the "only"?

Comment (TerryHowe) [reply pkg/cmd/list.go]: Done.

File: pkg/action/list_test.go [hunk 2]
```diff
@@ -176,9 +176,9 @@ func TestList_StateMask(t *testing.T) {
 
 	res, err := lister.Run()
 	is.NoError(err)
-	is.Len(res, 2)
-	is.Equal("three", res[0].Name)
-	is.Equal("two", res[1].Name)
+	is.Len(res, 3)
+	is.Equal("one", res[0].Name)
+	is.Equal("three", res[1].Name)
```
Comment (gjenkins8) [inline pkg/action/list_test.go]:
```suggestion
	is.Equal("three", res[1].Name)
	is.Equal("two", res[2].Name)
```

something like this?

File: pkg/cmd/list.go [hunk 3]
```diff
@@ -36,9 +36,12 @@ import (
...
 
-By default, it lists only releases that are deployed or failed. Flags like
-'--uninstalled' and '--all' will alter this behavior. Such flags can be combined:
-'--uninstalled --failed'.
+By default, it lists all releases in any status including deployed, failed,
+pending-upgrade, pending-install, pending-rollback, uninstalled, uninstalling,
+superseded, and unknown. Individual status filters like '--deployed', '--failed',
+'--pending', '--uninstalled', '--superseded', and '--uninstalling' can be used
+to show only releases in specific states. Such flags can be combined:
+'--deployed --failed'.
```
Comment (gjenkins8) [inline pkg/cmd/list.go]: I think we can reduce verbosity here:
```suggestion
By default, it lists all releases in any status. Individual status filters like '--deployed', '--failed',
'--pending', '--uninstalled', '--superseded', and '--uninstalling' can be used
to show only releases in specific states. Such flags can be combined:
'--deployed --failed'.
```

**Review by gjenkins8 — DISMISSED** [review]

**Review by gjenkins8 — DISMISSED** [review]

**Review by mattfarina — APPROVED** [review]
tested. lgtm

**Review by gjenkins8 — APPROVED** [review]
