### PR TITLE
fix(tiller): merge -f values correctly

### LINKED ISSUE #920: Unused overrides in chartutil.CoalesceValues
In #912 I noticed that the last parameter in chartutil.CoalesceValues doesn't seem to be used anywhere other than tests anymore. Should we remove the option, or do you see a need for it in a future change to the values?

https://github.com/kubernetes/helm/blob/master/pkg/chartutil/values.go#L142

/cc @technosophos

### LINKED ISSUE #971: helm doesn't inherit values for subcharts with -f myvals.yaml
to reproduce:

- create a chart with subcharts
- package chart
- install chart with custom subchart vals: helm install foo.tgz -f myvals.yaml 

helm doesn't care about myvals.yaml

### PR DESCRIPTION
**Pull request by technosophos**
This fixes a bug in which passed-in values files were not correctly
merged into the chart's default values YAML data. I believe it also
fixes some other prioritization bugs in values merging.

The existing unit test was wrong (see TestCoalesceValues). It is
fixed now. Also added more tests to simulate issue #971.

In the course of writing this, I removed some vestigial code as
mentioned in #920.

Closes #971
Closes #920

### CODE REVIEW

File: pkg/chartutil/values_test.go [hunk 1]
```diff
@@ -268,7 +325,7 @@ func TestCoalesceTables(t *testing.T) {
 		t.Fatal("Address went away.")
 	}
 
-	if addr["street"].(string) != "234 Spouter Inn Ct." {
+	if addr["street"].(string) != "123 Spouter Inn Ct." {
```
Comment (technosophos) [inline pkg/chartutil/values_test.go]: For those watching along at home, this is the test that was broken and led to a false positive.
