### PR TITLE
lint: lint all documents in a multi-doc yaml file

### LINKED ISSUE #8621: Linting fails in 3.3.0 when a template file results in only a comment.
Output of `helm version`:
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}

An error occurs when linting a chart that results in a template file containing only a comment:
```` 
# comment on first line
{{- if false }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mychart-configmap
data:
  myvalue: "Hello World"
{{- end }}
````

the resulting lint throws an error:
````
[ERROR] templates/configmap-false.yaml: object name does not conform to Kubernetes naming requirements: ""
````

Essentially an empty file with only a comment triggers this issue.

```` 
# comment on first line
{{- if true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mychart-configmap
data:
  myvalue: "Hello World"
{{- end }}
````

results in a successful lint:
````
1 chart(s) linted, 0 chart(s) failed
````

### PR DESCRIPTION
**Pull request by bonifaido**
Signed-off-by: Nandor Kracser <bonifaido@gmail.com>

**What this PR does / why we need it**:
The current linting code handled YAML files incorrectly, so I tried my best to fix multiple issues around that:
- multiple documents, only the first document got parsed and linted
- YAML files without actual documents, just containing a `---` marker
- empty YAML files with comments

There might be other issues that I have fixed accidentally.

Related: #8621

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

File: pkg/lint/rules/template.go [hunk 1]
```diff
@@ -20,14 +20,15 @@ import (
...
+	"io"
 	"os"
 	"path"
 	"path/filepath"
 	"regexp"
 	"strings"
 
 	"github.com/pkg/errors"
-	"sigs.k8s.io/yaml"
+	"k8s.io/apimachinery/pkg/util/yaml"
```
Comment (bacongobbler) [inline pkg/lint/rules/template.go:31]: this might be considered a breaking change as it's unclear whether these two yaml parsers are compatible with each other. One YAML parser's output can differ from another.

Can you see if this can be reverted?

Comment (bonifaido) [reply pkg/lint/rules/template.go:31]: The main feature why I have changed to `apimachinery` is that it supports multi-document YAML files correctly (the `---` separator).

Just checked which YAML parser is used underneath, and `apimachinery` uses the same: `sigs.k8s.io/yaml`, it just wraps it to add multi-document support, so I think it is safe to say that it is the same YAML parser.

https://github.com/kubernetes/apimachinery/blob/d10b9c3a6d2ee7cd58bec9931482a0d604534231/pkg/util/yaml/decoder.go#L32

**Review by mattfarina — APPROVED** [review]
lgtm

File: pkg/lint/rules/testdata/multi-template-fail/templates/_helpers.tpl [hunk 2]
```diff
@@ -0,0 +1,63 @@
+{{/* vim: set filetype=mustache: */}}
```
Comment (hickeyma) [inline pkg/lint/rules/testdata/multi-template-fail/templates/_helpers.tpl:1]: You shouldn't need the `_helpers.tpl` file

File: pkg/lint/rules/testdata/multi-template-fail/values.yaml [hunk 3]
```diff
@@ -0,0 +1,66 @@
+# Default values for multi-template-fail.
```
Comment (hickeyma) [inline pkg/lint/rules/testdata/multi-template-fail/values.yaml:1]: You shouldn't need the `values.yaml` file

File: pkg/lint/rules/template.go (hunk 1 above)
Comment (hickeyma) [reply pkg/lint/rules/template.go:31]: Looked at the code in `k8s.io/apimachinery/pkg/util/yaml` and also discussed with @mattfarina. The code wraps `sigs.k8s.io/yaml` with an IO reader to read multi-doc yaml file and then calls the yaml unmarshall for each doc contained. It is using the same parser as previous and good to use.

**Review by hickeyma — CHANGES_REQUESTED** [review]
Thanks for fixing this @bonifaido. Its nearly there just some small cleanup of test files to address.

**Comment by hickeyma** [comment]
@bonifaido You will need to rebase as well to resolve conflict.

**Comment by bonifaido** [comment]
I hopefully managed to fix those, thanks!

**Review by hickeyma — APPROVED** [review]
LGTM, thanks for the fix @bonifaido.
