### PR TITLE
fix(kube): use non global Scheme to convert

### LINKED ISSUE #7400: Usage of global Scheme can cause Helm to wrongly choose a 3-way-merge patch
While using Helm as a package instead of just using the binary the problem exists that due to the [usage of the global `scheme.Scheme` in `pkg/kube/converter.go` to create versioned objects](https://github.com/helm/helm/blob/master/pkg/kube/converter.go#L40), custom resources added to `scheme.Scheme` by e.g. versioned clients [will make Helm attempt to 3-way-merge patch those resources as they are no longer of type `runtime.Unstructured`](https://github.com/helm/helm/blob/master/pkg/kube/client.go#L373).

My proposal is to use a separate `scheme.Scheme`, with only native Kubernetes added to it, to break free from (generated) versioned Kubernetes clients automagically registering their resources to the global `scheme.Scheme`.

### PR DESCRIPTION
**Pull request by hiddeco**
But instead use a newly initialized Scheme with only Kubernetes native
resources added. This ensures the 3-way-merge patch strategy is not
accidentally chosen for custom resources due to them being added
to the global Scheme by e.g. versioned clients while using Helm as a
package, and not a self-contained binary.

Signed-off-by: Hidde Beydals <hello@hidde.co>

Closes #7400

### CODE REVIEW

File: pkg/kube/converter.go [hunk 1]
```diff
@@ -33,12 +36,28 @@ func AsVersioned(info *resource.Info) runtime.Object {
...
+// native resources added to it. This is required to break free of custom resources
+// that may have been added to scheme.Scheme due to Helm being used as a package in
+// combination with e.g. a versioned kube client. If we would not do this, the client
+// may attempt to perform e.g. a 3-way-merge strategy patch for custom resources.
+func kubernetesNativeScheme() *runtime.Scheme {
+	s := runtime.NewScheme()
+	utilruntime.Must(scheme.AddToScheme(s))
+	// API extensions are not in the above scheme set,
+	// and must thus be added separately.
+	utilruntime.Must(apiextensionsv1beta1.AddToScheme(s))
```
Comment (hiddeco) [inline pkg/kube/converter.go]: Depending on other internals I may not be aware of, not registering this would make it possible to drop the `isCRD` patch recently added here: https://github.com/helm/helm/blob/master/pkg/kube/client.go#L376

File: pkg/kube/converter.go [hunk 2]
```diff
@@ -33,12 +36,28 @@ func AsVersioned(info *resource.Info) runtime.Object {
...
 	return obj
 }
+
+// kubernetesNativeScheme returns a clean *runtime.Scheme with _only_ Kubernetes
+// native resources added to it. This is required to break free of custom resources
+// that may have been added to scheme.Scheme due to Helm being used as a package in
+// combination with e.g. a versioned kube client. If we would not do this, the client
+// may attempt to perform e.g. a 3-way-merge strategy patch for custom resources.
+func kubernetesNativeScheme() *runtime.Scheme {
+	s := runtime.NewScheme()
```
Comment (thomastaylor312) [inline pkg/kube/converter.go]: We should probably use `sync.Once` to set this up and then only generate it once instead of every time. `convertWithMapper` is used a lot (basically for every resource), so it might be good to do this once. It could be stored in a non-exported global variable local to this package

File: pkg/kube/converter.go (hunk 1 above)
Comment (thomastaylor312) [reply pkg/kube/converter.go]: I think we register them for now. We've had a lot of issues with not registering API extensions, so let's play it safe

**Review by thomastaylor312 — CHANGES_REQUESTED** [review]
Good fix on this. Just one point of feedback around constructing the scheme

**Review by thomastaylor312 — APPROVED** [review]
LGTM. Thanks for this fix!
