### PR TITLE
(fix/issue-6237) Add check to see if connected to the kubernetes cluster

### LINKED ISSUE #6237: Helm 3: helm list shows no error when disconnected from internet
No internet:
```
$ bin/helm list --debug
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART
$
```

Internet:
```
$ bin/helm list --debug
NAME     	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART
myrelease	default  	1       	2019-08-15 10:25:39.538926 -0400 EDT	deployed	nginx-4.3.3
$
```

### PR DESCRIPTION
**Pull request by waveywaves**
Signed-off-by: Vibhav Bobade <vibhav.bobde@gmail.com>

**What this PR does / why we need it**:
Fixes #6237 

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

cc @mattfarina @thomastaylor312 @adamreese

### CODE REVIEW

**Comment by waveywaves** [comment]
Let me know if I need to make any changes.
Output of the command looks like the following when not connected to the internet.
```
➜  helm git:(fix/6237) ✗ helm list --debug
helm.go:132: [debug] Please connect to the Internet.
NAME    NAMESPACE       REVISION   
```

**Comment by waveywaves** [comment]
cc @jdolitsky

**Comment by jdolitsky** [comment]
Hi thanks for looking into this. I think that there is maybe a more elegant
way to check connection via the kube client. I think connected to the
“internet” is misstated - should be connected to “cluster” (think minikube
for example, no internet connection required)

**Comment by waveywaves** [comment]
@jdolitsky That makes more sense. I will update the PR accordingly.

**Comment by jdolitsky** [comment]
Cool. My guess is there is an ignored error somewhere? (Sry away from
computer)

**Comment by waveywaves** [comment]
@jdolitsky I have updated the PR and this time I am checking if the Kubernetes client is reachable. DO let me know if I need ot make any changes.

File: cmd/helm/helm.go [hunk 1]
```diff
@@ -92,6 +92,11 @@ func initActionConfig(actionConfig *action.Configuration, allNamespaces bool) {
 		// TODO return error
 		log.Fatal(err)
 	}
+	err = kc.IsReachable()
```
Comment (mattfarina) [inline cmd/helm/helm.go]: Two things come to mind here...

1. #6232 is in flight to remove the `init` command. Right now it only setups up missing files locally as tiller is gone. The idea is to lazy create the directories if not present.
2. The init action no longer requires communicating with the server. In this function the goal is to get the client set which is locally available and the namespace which is also locally available. If I'm on a plane working on something and need to init helm why shouldn't it work? This is a real work situation for me a couple times a year. Maybe others.

Does it matter if the Kubernetes cluster is available at this step?

Comment (marckhouzam) [reply cmd/helm/helm.go]: I second point #2:
- there are times where I don't have a network and still use some parts of helm for development.
- there are times when I have internet but can't reach my cluster (VPN not activated).  

I guess verifying the cluster connection should be done for commands that actually need the cluster.

For example, `helm --help` should always work (it does not with this patch).
`helm repo add ...`, `helm show ...` are other examples where the cluster is not needed.

Comment (waveywaves) [reply cmd/helm/helm.go]: It only makes sense to have the check run for certain commands which would use kubernetes. Thank you for helping me out. I have updated the PR accordingly.

Comment (akashshinde) [reply cmd/helm/helm.go]: @mattfarina 
we should have way to check cluster connection just to make sure helm commands going to work. How about having explicit helm command to check such as `helm cluster status` ? 
cc: @marckhouzam

Comment (waveywaves) [reply cmd/helm/helm.go]: @mattfarina @jdolitsky I have made further changes to the PR. Have added the check only in places which seem necessary in terms of connecting to the Kubernetes cluster.

**Comment by waveywaves** [comment]
Test coverage is failing here, on my local system it works. Any idea why this might be happening @jdolitsky

File: cmd/helm/get.go [hunk 2]
```diff
@@ -47,6 +48,9 @@ func newGetCmd(cfg *action.Configuration, out io.Writer) *cobra.Command {
 		Long:  getHelp,
 		Args:  require.ExactArgs(1),
 		RunE: func(cmd *cobra.Command, args []string) error {
+			kc := kube.New(kubeConfig())
+			kc.IsReachable()
```
Comment (mattfarina) [inline cmd/helm/get.go]: Can you please move this to the [`action` package](https://github.com/helm/helm/tree/dev-v3/pkg/action)? In this code flow you'll find it inside `client.Run()`. That way if someone imports the action package to leverage this functionality they will have checks for for connectivity.

File: pkg/kube/client.go [hunk 3]
```diff
@@ -63,6 +64,16 @@ func New(getter genericclioptions.RESTClientGetter) *Client {
 
 var nopLogger = func(_ string, _ ...interface{}) {}
 
+// Test connectivity to the Client
+func (c *Client) IsReachable() {
+	client, _ := c.Factory.KubernetesClientSet()
+	_, err := client.ServerVersion()
+	if err != nil {
+		c.Log("--- Kubernetes Cluster Unreachable ---")
+		os.Exit(1)
```
Comment (mattfarina) [inline pkg/kube/client.go]: Instead of performing an `os.Exit` can you return an error. Then where this code is used can you check for an error and return it up the stack.

**Comment by waveywaves** [comment]
@jdolitsky  @mattfarina I have made the necessary changes, do check it out

**Review by jdolitsky — APPROVED** [review]
This looks good

**Review by mattfarina — APPROVED** [review]

**Comment by marckhouzam** [comment]
@waveywaves This is really nice!  I think `helm test run` would also benefit from this check:

```
> helm test run hello
Error: query: failed to query with labels: 
Get https://mycluster:6443/api/v1/namespaces/default/secrets?labelSelector=name%3Dhello%2Cowner%3Dhelm: 
Get https://myopenid-configuration: dial tcp: lookup mykubehost: no such host
```
