### PR TITLE
fix: handle OCI digest algorithm prefix in chart downloader

### LINKED ISSUE #31600: Inconsistent digest + tag handling in helm 4 install with OCI Chart
### What happened?

I tried many different references with unexpected results:

For reference, the tag in the registry is `1.4.2`, and digest is `sha256:aef46c66a7f2d5a12a7e3f54a64790daf5c9a9e66af3f46955efdaa6c900341d`. A tag `v1.4.2` does NOT exist.

```sh
# tag only
$ helm4 upgrade --install nginx-ingress oci://ghcr.io/nginxinc/charts/nginx-ingress:1.4.2
# works

# tag with "v"
$ helm4 upgrade --install nginx-ingress oci://ghcr.io/nginxinc/charts/nginx-ingress:v1.4.2
Error: failed to perform "FetchReference" on source: ghcr.io/nginxinc/charts/nginx-ingress:v1.4.2: not found

# digest only
$ helm4 upgrade --install nginx-ingress oci://ghcr.io/nginxinc/charts/nginx-ingress@sha256:aef46c66a7f2d5a12a7e3f54a64790daf5c9a9e66af3f46955efdaa6c900341d
# works

# tag without "v" and digest 
$ helm4 upgrade --install nginx-ingress oci://ghcr.io/nginxinc/charts/nginx-ingress:1.4.2@sha256:aef46c66a7f2d5a12a7e3f54a64790daf5c9a9e66af3f46955efdaa6c900341d
Error: encoding/hex: invalid byte: U+0073 's'

# tag with "v" and digest
$ helm4 upgrade --install nginx-ingress oci://ghcr.io/nginxinc/charts/nginx-ingress:v1.4.2@sha256:aef46c66a7f2d5a12a7e3f54a64790daf5c9a9e66af3f46955efdaa6c900341d
# works

# tag + wrong digest
$ helm4 upgrade --install nginx-ingress oci://ghcr.io/nginxinc/charts/nginx-ingress:1.4.2@sha256:aef46c66a7f2d5a12a7e3f54a64790daf5c9a9e66af3f46955efdaa6c9003xxx
Error: invalid reference: invalid digest "sha256:aef46c66a7f2d5a12a7e3f54a64790daf5c9a9e66af3f46955efdaa6c9003xxx": invalid checksum digest format
# unexpected, but very nice

# Wrong tag + digest
$ helm4 upgrade --install nginx-ingress oci://ghcr.io/nginxinc/charts/nginx-ingress:v1.4.2xxx@sha256:aef46c66a7f2d5a12a7e3f54a64790daf5c9a9e66af3f46955efdaa6c900341d
# works
```

### What did you expect to happen?

More consistency:

- tag+digest should work. Why does it only work with an invalid tag?
- if specifying a wrong digest gets validated, the reverse should also be true. If the tag points to a different digest this should cause an error
  - actually, most client usually ignore the tag entirely if a digest is present. But as-is the helm4 implementation is inconsistent.

### How can we reproduce it (as minimally and precisely as possible)?

See my sample commands above.

### Helm version

<details>

```console
$ helm4 version
version.BuildInfo{Version:"v4.0.1", GitCommit:"12500dd401faa7629f30ba5d5bff36287f3e94d3", GitTreeState:"clean", GoVersion:"go1.25.4", KubeClientVersion:"v1.34"}```
</details>


### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.34.1
Kustomize Version: v5.7.1
Server Version: v1.34.0```

</details>

### PR DESCRIPTION
**Pull request by banjoh**
**What this PR does / why we need it**:

OCI references with tag+digest (e.g., `chart:1.0@sha256:abc...`) failed with "invalid byte" error because the `sha256:` prefix was passed to `hex.DecodeString()`.

Closed: https://github.com/helm/helm/issues/31600

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

File: pkg/repo/v1/repotest/server.go [hunk 1]
```diff
@@ -140,11 +140,12 @@ func newServer(t *testing.T, docroot string, options ...ServerOption) *Server {
...
-	Dir          string
-	TestUsername string
-	TestPassword string
-	Client       *ociRegistry.Client
+	RegistryURL    string
+	Dir            string
+	TestUsername   string
+	TestPassword   string
+	Client         *ociRegistry.Client
+	ManifestDigest string // Digest of the pushed oci-dependent-chart manifest
```
Comment (TerryHowe) [inline pkg/repo/v1/repotest/server.go]: This is a bit odd to put ManifestDigest here in a object about server configuration.  There's no other way to validate?

**Comment by TerryHowe** [comment]
Thanks for pulling to PR together so fast @banjoh !

File: pkg/repo/v1/repotest/server.go (hunk 1 above)
Comment (banjoh) [reply pkg/repo/v1/repotest/server.go]: Agreed! I'll see how best to do this

Comment (banjoh) [reply pkg/repo/v1/repotest/server.go]: @TerryHowe I addressed this

**Review by TerryHowe — DISMISSED** [review]
/lgtm

File: pkg/downloader/chart_downloader_test.go [hunk 2]
```diff
@@ -485,3 +485,41 @@ func TestDownloadToCache(t *testing.T) {
...
+			expected: "",
+		},
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			result := stripDigestAlgorithm(tt.input)
+			if result != tt.expected {
+				t.Errorf("stripDigestAlgorithm(%q) = %q, want %q", tt.input, result, tt.expected)
+			}
```
Comment (gjenkins8) [inline pkg/downloader/chart_downloader_test.go]:
```suggestion
			assert.Equal(t, tt.expected, result)
```

Use testify?

File: pkg/downloader/chart_downloader_test.go [hunk 3]
```diff
@@ -485,3 +485,41 @@ func TestDownloadToCache(t *testing.T) {
 		c.Keyring = ""
 	})
 }
+
+func TestStripDigestAlgorithm(t *testing.T) {
+	tests := []struct {
```
Comment (gjenkins8) [inline pkg/downloader/chart_downloader_test.go]: use a map here? e.g.
```
    tests := map[string]struct {
		input    string
		expected string
	}{
         "sha256 prefixed digest": {
             input:  "...
```

Then below:
```
for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
```

**Review by TerryHowe — APPROVED** [review]
/lgtm

File: pkg/downloader/chart_downloader_test.go (hunk 3 above)
Comment (banjoh) [reply pkg/downloader/chart_downloader_test.go]: Addressed

File: pkg/downloader/chart_downloader_test.go (hunk 2 above)
Comment (banjoh) [reply pkg/downloader/chart_downloader_test.go]: Addressed
