### PR TITLE
fix(lint): validateNoMissingValues template regex

### LINKED ISSUE #1367: linter: validateNoMissingValues rule doesn't pick up templates suppressing newlines
For example, the linter doesn't pick up `{{- inexistantFunction }}` as an inexistantFunction, because the regex it uses doesn't pick up templates with dashes.

The validateNoMissingValues logic also doesn't deal well with if/else/end.

### PR DESCRIPTION
**Pull request by prydonius**
Fixes the regex for extracting templates to include templates that
suppress newlines and ignore any conditional flow statements.

closes #1367

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/helm/1368)

### CODE REVIEW

File: pkg/lint/rules/template.go [hunk 1]
```diff
@@ -71,11 +71,11 @@ func Templates(linter *support.Linter) {
 	}
 
 	/* Iterate over all the templates to check:
-	   - It is a .yaml file
```
Comment (technosophos) [inline pkg/lint/rules/template.go]: Yeah, it does that. We just let it have its way. ;-)
