### PR TITLE
Fix nested null value overrides

### LINKED ISSUE #5184: Nested `null` values don't remove keys as expected
<https://github.com/helm/helm/pull/2648> allows for deletion of keys by setting `null` values in a `values.yaml` file. However it doesn't work for nested values, e.g.:

```yaml
web:
  livenessProbe:
    httpGet: null
    exec:
      command:
      - curl
      - -f
      - http://localhost:8080/api/v1/info
```

Will not remove `web.livenessProbe.httpGet` from the original values, rather it just overrides the value with `null` and prints the warning:

```
2019/01/18 11:30:07 Warning: Merging destination map for chart 'concourse'. Cannot overwrite table item 'httpGet', with non table value: map[path:/api/v1/info port:atc]
```

Ironically, above is a small variant on the example given in the docs, which I'm pretty sure does not actually do what it claims to: <https://docs.helm.sh/chart_template_guide/#deleting-a-default-key>

I suspect that since the template rendering doesn't seem to differentiate much between a null value and a value not being specified, that this warnings are being ignored and not having much effect.

Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

EKS

### PR DESCRIPTION
**Pull request by uzxmx**
Closes #5184

I tested with the latest release v3.1.1, but with no luck, the [deleting a default key](https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key) still didn't work.  I found the merged PR #5185 solved that problem, but it only lives on dev-v2 branch, seems it hasn't been picked in v3.x.

So I created this PR. Hopefully it will help others who has met such problem as me.

### CODE REVIEW

**Comment by bacongobbler** [comment]
After #5185 was merged, we also had to address it with #5821 and #6080. Can you please follow the discussion in #5184 and make sure this PR reflects what had to be addressed in order to get this to work?

**Comment by strider-golang** [comment]
Seems to be working as expected. 👍

**Comment by uzxmx** [comment]
@bacongobbler Thanks for pointing out those information. I've read #5821, #6080 and #6146. Below is what I learned:

For #5821, actually this has nothing to do with the issue in #5184, the author just did some refactor work based on dev-v2 branch when he created #5185. But since v3 has been released, a lot of refactor work about `pkg/chartuti/*.go` has been made. So we may not need to port those refactor from #5821.

For #6080, the author solved the problem that multiple calling `coalesceDeps` causes subchart value deletion not working.

For #6146, it's the same as #6080, the author just added another unit test due to repeated fix with #6080.

And for the whole story in #5184, there are two issues that need to be solved. One bug is about value deletion for top level chart. The second is about value deletion for subchart.

My first commit only solved the first bug. Thanks to your information, I've ported #6080 (the same as #6146) to the second commit, and added test cases about subchart value deletion.

Please give it a try. If there is other problem, feel free to tell me.

File: pkg/chartutil/coalesce.go [hunk 1]
```diff
@@ -47,10 +47,7 @@ func CoalesceValues(chrt *chart.Chart, vals map[string]interface{}) (Values, err
 	if valsCopy == nil {
 		valsCopy = make(map[string]interface{})
 	}
-	if _, err := coalesce(chrt, valsCopy); err != nil {
-		return valsCopy, err
-	}
-	return coalesceDeps(chrt, valsCopy)
+	return coalesce(chrt, valsCopy)
```
Comment (technosophos) [inline pkg/chartutil/coalesce.go:50]: You did not update the docs that explain why this was called twice (lines 38-39 above).

**Review by technosophos — APPROVED** [review]
LGTM. I left a note that one of the comments in the code is wrong. Once that is fixed, I'll merge.

**Review by adamreese — APPROVED** [review]

File: pkg/chartutil/coalesce.go (hunk 1 above)
Comment (uzxmx) [reply pkg/chartutil/coalesce.go:50]: Sorry, I overlooked the comment at lines 38 - 39. I think we can just remove that comment, or we can change the comment to "create a copy of vals and then pass it to coalesce, as it will mutate the passed values", because `coalesceDeps` was invoked in `colesce`, so that invoke was duplicated.

Comment (technosophos) [reply pkg/chartutil/coalesce.go:50]: I removed the comment in a followw-up PR because I wanted to get this merged in time for Helm 3.2 RC.1. Thanks again!
