### PR TITLE
Verify generation in readiness checks

### LINKED ISSUE #10859: bug- race condition due to unused resource generation metadata/spec
I would like to propose a new 'ReadinessCheckDelay' argument to the helm commands: 'install', 'upgrade', and 'rollback' based on a race condition we are seeing between helm and a kubernetes controller.  We are running helm install with the 'wait' and 'atomic' arguments, but helm doesn't track the resource readiness state (we are seeing this in approximately half of our installs that contain a statefulset). We have reviewed the api-server logs and found that helm makes both the [patch](https://github.com/helm/helm/blob/main/pkg/kube/client.go#L511) and [resource readiness get](https://github.com/helm/helm/blob/de8034c097a5814c2032cb7d73c09ae4f746b403/pkg/kube/ready.go#L176) calls before the statefulset controller has the chance to update the resource.  This is causing a false positive for the readiness check on the statefulset, and helm incorrectly updates the install status as completed successfully.  I am proposing a 'ReadinessCheckDelay' argument that can be used to add some delay between the resources being patched by helm and the subsequent readiness checks.  Unfortunately I can't share logs because this is something I am encountering in my cluster at work (highly restrictive fintech).  This is something I'm happy to contribute assuming the community is open to this change.  Thanks for the feedback :)

Output of `helm version`: 3.8.0

Output of `kubectl version`: 1.21.5

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

### PR DESCRIPTION
**Pull request by rohnyn**
Signed-off-by: James Oden <james.oden.dev@gmail.com>

**What this PR does / why we need it**: This patches a bug where helm preemptively marks resources as ready.  This is due to a race condition between the helm readiness check and the associated k8s controller updating the resource.  I've added generational validation to readiness checks for all applicable resources.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

closes #10859
Associated k8s [issue](https://github.com/kubernetes/kubernetes/issues/109490#issuecomment-1101704320)
Thanks for the help!

### CODE REVIEW

**Comment by muang0** [comment]
@joejulian Anything I can do on my end to help get this one triaged?  Thanks for the help!

**Comment by muang0** [comment]
@mattfarina @bacongobbler @yxxhero Anything I can do on my end to help get this one triaged? Thanks for the help!

**Comment by muang0** [comment]
@zonggen @joejulian @yxxhero Anything I can do on my end to help get this one triaged? Thanks for the help!

**Comment by yxxhero** [comment]
@muang0 need more comments for review. Thanks very much.

**Comment by muang0** [comment]
> @muang0 need more comments for review. Thanks very much.

@yxxhero thanks for the response!  Do you mind clarifying what you mean?  Do you need me to provide more clarification on this PR in a comment?

A concise summary: During resource readiness checks, helm doesn't utilize the k8s generation/observedGeneration fields. This creates an opening for a race condition between helm and the associated k8s controller.  In this case, a resource is incorrectly marked as ready by helm (before the associated k8s controller picks up the changes to the spec from helm).  If we add generational checks to helm readiness validation, then helm would notice the generation & observedGeneration are out of sync, and avoid this race condition entirely.

What we are observing as a result:  While using the wait flag, helm doesn't wait for the resources to be created but rather immediately marks resource creation as complete and finishes the install.

k8s api-conventions description of observedGeneration & generation: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md?plain=1#L476-L479

**Comment by muang0** [comment]
Hi @yxxhero any action I should take from my end?  Thanks for the help!

**Comment by muang0** [comment]
Hi @yxxhero, hope you're having a good week! So sorry to bother, just bumping this so it doesn't fall between the cracks :) It's a small change at its core, most of the lines are unit tests.

**Comment by muang0** [comment]
@yxxhero I hate to bother you :sweat_smile:  this PR is really a small change at its core, shouldn't take long to review/triage.  You'd be helping us out a ton by helping push this one along :smile:

**Comment by yxxhero** [comment]
@muang0 those changes are valuable. but The code changes a lot, I need more time to review. Thanks very much.

**Comment by muang0** [comment]
Gentle bump 😀

**Comment by Dentrax** [comment]
This PR is what exactly I was looking for. I was playing with Kind cluster using Helm and noticed `--wait` does not as expected, so found the following comment: https://github.com/helm/helm/issues/10061#issuecomment-1143752352

And ended up this PR eventually. So I tested on my local env:

```
$ gh pr checkout 10920
$ make build

$ cat <<EOF | kind create cluster --name helm-test --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
EOF

# The next two commands does not wait
$ helm upgrade fluent-bit fluent/fluent-bit --install --wait
$ helm upgrade --wait --reuse-values --set flush=3 fluent-bit fluent/fluent-bit

# Now test with this PR
$ ./bin/helm upgrade --wait --reuse-values --set flush=1 fluent-bit fluent/fluent-bit
```

Works like a charm, great job @muang0! 👏 

Any possibility to make review process a bit faster to keep time window short to get this merge to main branch?

Kind ping @yxxhero @mattfarina @bacongobbler 🤗

**Comment by muang0** [comment]
Kind ping :)

**Comment by muang0** [comment]
Kind ping, plz fam, it's not a complex change 😅

**Comment by rmendal-Harness** [comment]
We've run into this issue too. Would really appreciate it if this got reviewed please and thanks.

**Comment by muang0** [comment]
@dnwe Thank you greatly for your contribution!! :fireworks: Your statefulset generational readiness check is valuable work :smile: 
https://github.com/helm/helm/commit/7c74f1dd027709156c3345e1965693f04b8dd9ac

@yxxhero @mattfarina @bacongobbler I think this type of generational check would be valuable for other resources as well.  In this PR I've applied generational readiness checks for all applicable resources.  If you think this is something helm can benefit from, and willing to commit to reviewing these changes, I'm happy resolve my merge conflicts.  Just let me know!

@rmendal-Harness @Dentrax This will likely be the last activity on this PR from me unless maintainers are interested in this PR.  Thank you for the shoutouts :100:

**Review by sudermanjr — COMMENTED** [review]
This looks great. The test coverage is great, and I was able to make the tests fail. This seems to me to be the correct way to check for readiness. I left one small nit inline about a comment. 

I'm still digging into the logic on the IsRead, specifically the removal of the variable declaration at the top. I don't quite understand why it was there in the first place, so I'm not certain removing it is the right move. Will keep looking

Also, it looks like this could use a rebase. I can bring this to the next community meeting if you want to do that and address the comment.

File: pkg/kube/ready.go [hunk 1]
```diff
@@ -272,6 +284,16 @@ func (c *ReadyChecker) volumeReady(v *corev1.PersistentVolumeClaim) bool {
 }
 
 func (c *ReadyChecker) deploymentReady(rs *appsv1.ReplicaSet, dep *appsv1.Deployment) bool {
+	// Verify the generation observed by the replicaSet controller matches the spec generation
```
[the remark this answers is not in the document]
Comment (muang0) [reply pkg/kube/ready.go]: updated, good catch!

**Comment by mattfarina** [comment]
@muang0 can you rebase this from main? The CI error you encountered is fixed there.

**Comment by muang0** [comment]
@mattfarina just rebased, checks passing!

**Comment by muang0** [comment]
Kind ping

**Comment by muang0** [comment]
Kind ping @mattfarina @sudermanjr

**Review by bjosv — COMMENTED** [review]
Very nice! Seems to be able to fix our problems as well.

As a note; there is a similar generation check in the [kubectl rollout status](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/polymorphichelpers/rollout_status.go#L75) command,
so it's a somewhat conventional step in the readiness check procedure, which is good.

File: pkg/kube/ready.go [hunk 2]
```diff
@@ -89,13 +89,6 @@ type ReadyChecker struct {
 // IsReady will fetch the latest state of the object from the server prior to
 // performing readiness checks, and it will return any error encountered.
 func (c *ReadyChecker) IsReady(ctx context.Context, v *resource.Info) (bool, error) {
-	var (
-		// This defaults to true, otherwise we get to a point where
-		// things will always return false unless one of the objects
-		// that manages pods has been hit
-		ok  = true
-		err error
-	)
```
Comment (scottrigby) [inline pkg/kube/ready.go:98]: This was interesting. Several of us have talked about this and it's hard to grok what `ok = true` does here.

Connected with @sudermanjr who connected with @joejulian about this. Joe worked to split ready out from wait from Helm 2 to Helm 3, and seems this was not really noticed during that work. This appears to be a carry over from helm v2.

What I would like to know is, does this PR work without this change? Is anyone available to try? If so, I'd clean this up as a separate PR so it could be reverted on it's own if needed later.

**Review by scottrigby — COMMENTED** [review]
Other than the question about removing var setting at the top, this PR looks lgtm 💯 
Thanks @muang0  for the PR and thanks to everyone who reviewed and tested so far.
If anyone has time to look at that question, that's the only thing giving me pause to approve yet.

File: pkg/kube/ready.go [hunk 3]
```diff
@@ -272,6 +284,16 @@ func (c *ReadyChecker) volumeReady(v *corev1.PersistentVolumeClaim) bool {
 }
 
 func (c *ReadyChecker) deploymentReady(rs *appsv1.ReplicaSet, dep *appsv1.Deployment) bool {
+	// Verify the replicaset readiness
+	if !c.replicaSetReady(rs) {
+		return false
+	}
+	// Verify the generation observed by the deployment controller matches the spec generation
+	if dep.Status.ObservedGeneration != dep.ObjectMeta.Generation {
+		c.log("Deployment is not ready: %s/%s. observedGeneration (%s) does not match spec generation (%s).", dep.Namespace, dep.Name, dep.Status.ObservedGeneration, dep.ObjectMeta.Generation)
```
Comment (bjosv) [inline pkg/kube/ready.go:293]:
```suggestion
		c.log("Deployment is not ready: %s/%s. observedGeneration (%d) does not match spec generation (%d).", dep.Namespace, dep.Name, dep.Status.ObservedGeneration, dep.ObjectMeta.Generation)
```

File: pkg/kube/ready.go [hunk 4]
```diff
@@ -281,6 +303,12 @@ func (c *ReadyChecker) deploymentReady(rs *appsv1.ReplicaSet, dep *appsv1.Deploy
 }
 
 func (c *ReadyChecker) daemonSetReady(ds *appsv1.DaemonSet) bool {
+	// Verify the generation observed by the daemonSet controller matches the spec generation
+	if ds.Status.ObservedGeneration != ds.ObjectMeta.Generation {
+		c.log("DaemonSet is not ready: %s/%s. observedGeneration (%s) does not match spec generation (%s).", ds.Namespace, ds.Name, ds.Status.ObservedGeneration, ds.ObjectMeta.Generation)
```
Comment (bjosv) [inline pkg/kube/ready.go:308]:
```suggestion
		c.log("DaemonSet is not ready: %s/%s. observedGeneration (%d) does not match spec generation (%d).", ds.Namespace, ds.Name, ds.Status.ObservedGeneration, ds.ObjectMeta.Generation)
```

File: pkg/kube/ready.go [hunk 5]
```diff
@@ -351,18 +379,18 @@ func (c *ReadyChecker) crdReady(crd apiextv1.CustomResourceDefinition) bool {
 }
 
 func (c *ReadyChecker) statefulSetReady(sts *appsv1.StatefulSet) bool {
+	// Verify the generation observed by the statefulSet controller matches the spec generation
+	if sts.Status.ObservedGeneration != sts.ObjectMeta.Generation {
+		c.log("Statefulset is not ready: %s/%s. observedGeneration (%s) does not match spec generation (%s).", sts.Namespace, sts.Name, sts.Status.ObservedGeneration, sts.ObjectMeta.Generation)
```
Comment (bjosv) [inline pkg/kube/ready.go:384]:
```suggestion
		c.log("Statefulset is not ready: %s/%s. observedGeneration (%d) does not match spec generation (%d).", sts.Namespace, sts.Name, sts.Status.ObservedGeneration, sts.ObjectMeta.Generation)
```

File: pkg/kube/ready.go [hunk 6]
```diff
@@ -403,6 +431,24 @@ func (c *ReadyChecker) statefulSetReady(sts *appsv1.StatefulSet) bool {
 	return true
 }
 
+func (c *ReadyChecker) replicationControllerReady(rc *corev1.ReplicationController) bool {
+	// Verify the generation observed by the replicationController controller matches the spec generation
+	if rc.Status.ObservedGeneration != rc.ObjectMeta.Generation {
+		c.log("ReplicationController is not ready: %s/%s. observedGeneration (%s) does not match spec generation (%s).", rc.Namespace, rc.Name, rc.Status.ObservedGeneration, rc.ObjectMeta.Generation)
```
Comment (bjosv) [inline pkg/kube/ready.go:437]:
```suggestion
		c.log("ReplicationController is not ready: %s/%s. observedGeneration (%d) does not match spec generation (%d).", rc.Namespace, rc.Name, rc.Status.ObservedGeneration, rc.ObjectMeta.Generation)
```

File: pkg/kube/ready.go [hunk 7]
```diff
@@ -403,6 +431,24 @@ func (c *ReadyChecker) statefulSetReady(sts *appsv1.StatefulSet) bool {
...
+		return false
+	}
+	return true
+}
+
+func (c *ReadyChecker) replicaSetReady(rs *appsv1.ReplicaSet) bool {
+	// Verify the generation observed by the replicaSet controller matches the spec generation
+	if rs.Status.ObservedGeneration != rs.ObjectMeta.Generation {
+		c.log("ReplicaSet is not ready: %s/%s. observedGeneration (%s) does not match spec generation (%s).", rs.Namespace, rs.Name, rs.Status.ObservedGeneration, rs.ObjectMeta.Generation)
```
Comment (bjosv) [inline pkg/kube/ready.go:446]:
```suggestion
		c.log("ReplicaSet is not ready: %s/%s. observedGeneration (%d) does not match spec generation (%d).", rs.Namespace, rs.Name, rs.Status.ObservedGeneration, rs.ObjectMeta.Generation)
```

**Review by bjosv — CHANGES_REQUESTED** [review]
Small nit regarding debug log formatting which makes it a bit more readable (int64).

File: pkg/kube/ready.go (hunk 2 above)
Comment (bjosv) [reply pkg/kube/ready.go:98]: The PR works without this change when I tested with the affected handling of ReplicaSets and ReplicationController,
but of course the code looks a bit weirder..
So fixing that in a separate PR should be ok.

**Comment by Dentrax** [comment]
Kind ping @muang0, can you please fix the reviews once you have a bandwidth? Thanks!

**Comment by Dentrax** [comment]
Is there any possibility to push forward this feature in the near future? :eyes:

**Comment by Dentrax** [comment]
@bjosv ping! 😊

**Comment by bjosv** [comment]
@Dentrax I'm not sure what I can do since I'm neither the submitter nor a project member,
but I also would love to have it merged..even without my last review comments :blush:

**Comment by Dentrax** [comment]
Oh... Sorry, I meant to ping @muang0. 🙈 Sorry for inconvenience.

**Comment by bjosv** [comment]
No worries, I'm just happy to see some action here.
Unfortunately it seem that muang0 has not been active on GitHub since September, but we hope for the best and that everything is ok.

**Comment by void-spark** [comment]
Quick question, I got here following a thread starting with a mention of this occurring with 1 pod.
Following the comments I don't think that is the main trigger, but is the mentioned race condition more likely with replica count set at 1? Just trying to diagnose, and I don't have access to much logs of the environment.

File: pkg/kube/ready.go (hunk 2 above)
Comment (muang0) [reply pkg/kube/ready.go:98]: Wouldn't it be easier to club this change in with this PR rather than two separate PRs?

Echoing @bjosv's thoughts- feels weird to use those vars just for the [*corev1.ReplicationController, *extensionsv1beta1.ReplicaSet, *appsv1beta2.ReplicaSet, *appsv1.ReplicaSet] checks

@scottrigby

**Comment by muang0** [comment]
Been🕵️‍♀️ for a while, lot going on in my 🌎 last 🗓🗓🗓🗓🗓🗓; starting to 🌥⛅️ more lately

**Review by bjosv — APPROVED** [review]

**Comment by RemusBizu** [comment]
We are also ran into this issue. When can this be merged? Thanks

**Review by joejulian — CHANGES_REQUESTED** [review]
Only the one change requested then this is good to go. I tested it out on my own CI pipeline and it worked perfectly.

**Comment by joejulian** [comment]
... and, of course, CI needs to pass.

**Comment by stefanmcshane** [comment]
@muang0 can I get write permissions to your repository so that we can revert this final change and get the bug merged in? Thanks

**Comment by muang0** [comment]
Thanks for reaching out. I'm planning my next haircut then I'd love to talk :)

**Comment by muang0** [comment]
Still waiting on the planned haircut. I've got a full head of hair, BUT I'm used to shaving it mysefl so this one's no biggie. Let's see if the !downers have any suggestions.

**Comment by muang0** [comment]
@stefanmcshane added you as contributor on the project-> thanks for raising this concern. Looks like just a couple minor things are needed here.

**Comment by stefanmcshane** [comment]
@joejulian Can you re-review with the changes corrected?

**Review by joejulian — APPROVED** [review]

**Comment by stefanmcshane** [comment]
Hi @joejulian @mattfarina can we get this merged?

**Review by mattfarina — APPROVED** [review]
