### PR TITLE
fix post install hook deletion due to before-hook-creation policy

### LINKED ISSUE #6879: Deletion Policy before-hook-creation does not work as expected
The deletion policy `before-hook-creation` does not work when the pod in question is in some "running" state. For example plain `Running` but also `ContainerCannotRun` when the cluster blocks the execution for some reason like enforced nonRoot.

Whenever another `helm test RELEASE` is issued, the command fails with the message `Error: warning: Hook test [...]/test-abborted-hook.yaml failed: object is being deleted: pods "rel-test-abort" already exists

Steps to reproduce:
1. add this test to any chart and install the chart.
```
apiVersion: v1
kind: Pod
metadata:
  name: "rel-test-abort"
  annotations:
    "helm.sh/hook": test-success
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  containers:
    - name: test
      image: "alpine"
      command: ['sh']
      args:
        - -c
        - "sleep 60s"
  restartPolicy: Never
```

2. run `helm test [RELNAME]` and hit `CTRL`+`C` before the test succeeded

3. run `helm test [RELNAME]` again and observe that it fails with "resource already exists"

Expected behaviour: Helm deletes the present resource before creating the new one as it is defined in the docs for the deletion policy `before-hook-creation`

Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.0-rc.2", GitCommit:"82ea5aa774661cc6557cb57293571d06f94aff0c", GitTreeState:"clean", GoVersion:"go1.13.3"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:16:09Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
on prem

### PR DESCRIPTION
**Pull request by zak905**
closes #6879 

**What this PR does / why we need it**:
This PR fixes a bug/issue when applying an install to a chart that has hooks with `"helm.sh/hook-delete-policy": before-hook-creation`. If the hook resources (pod or job) take time to terminate or have finalizers,  then the release will fail with a message like:

```
Error: failed post-install: warning: Hook post-install testing-hooks-chart/templates/pod.yaml failed: object is being deleted: pods "random-pod" already exists
```

**Special notes for your reviewer**:

I added some example manifests on how to reproduce this issue in my last comment on the issue

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by sudermanjr — APPROVED** [review]
I was able to reproduce the original issue, and then test this PR locally with the expected results.

@zak905 you will need to sign your commit in order to agree to the DCO as per the [contributing guide](https://github.com/helm/helm/blob/main/CONTRIBUTING.md#sign-your-work). You should be able to `git commit --amend -s` to do this.

**Comment by zak905** [comment]
Thanks @sudermanjr. commit signed now.

**Review by technosophos — APPROVED** [review]
This looks like a safe change, abides by the compatibility guidelines, and solves the issue. So LGTM.

**Comment by zak905** [comment]
@technosophos thanks. Just to let you know that I have made an additional change since you approved. The change fixes a failing test.

**Comment by brtknr** [comment]
Any movement on this?

**Comment by zak905** [comment]
I have squashed the commits into one, and rebased against upstream. @technosophos any chance getting this merged soon ?

**Comment by scottrigby** [comment]
@zak905 are you able to re-run the CI?

**Comment by zak905** [comment]
hi @scottrigby, I was not able to re-run the CI manually due to lack of permissions

ci-helm

so I tried to rebase against the main branch, which seems to trigger the CI

**Comment by ruromgar** [comment]
hi! coming here from [this issue](https://github.com/helm/helm/issues/6879). It's closed, but the bug is still there, so I came here and noticed this hasn't been merged yet. The CI is currently failing because of the `AZURE_STORAGE_CONNECTION_STRING` variable not being set - can we re-run it? @scottrigby @zak905

**Comment by zak905** [comment]
hi @ruromgar, thanks for pointing out that `AZURE_STORAGE_CONNECTION_STRING` was not set. I have set the two missing en variables (AZURE_STORAGE_CONNECTION_STRING and AZURE_STORAGE_CONTAINER_NAME) to some dummy values from my Circle CI account and I have relaunched the build, and it is passing (because the deploy is skipped unless the merge is in the main branch and tags). I talked to the project maintainers few weeks ago, and they are interested in merging this. Hopefully soon.

**Comment by ruromgar** [comment]
brilliant, @zak905! let's see if the original approvers, @technosophos and @sudermanjr, are still ok with this fix :)

File: pkg/action/hooks.go [hunk 1]
```diff
@@ -135,6 +136,13 @@ func (cfg *Configuration) deleteHookByPolicy(h *release.Hook, policy release.Hoo
 		if len(errs) > 0 {
 			return errors.New(joinErrors(errs))
 		}
+
+		//wait for resources until they are deleted to avoid conflicts
+		if kubeClient, ok := cfg.KubeClient.(kube.InterfaceExt); ok {
+			if err := kubeClient.WaitForDelete(resources, timeout); err != nil {
+				return err
+			}
+		}
```
Comment (mattfarina) [inline pkg/action/hooks.go:145]: On line 135, `cfg.KubeClient.Delete(resources)` is executed. It looks like this is trying to delete the resources twice. Shouldn't the code only do this once?

**Review by mattfarina — CHANGES_REQUESTED** [review]

File: pkg/action/hooks.go (hunk 1 above)
Comment (zak905) [reply pkg/action/hooks.go:145]: Hi @mattfarina, `WaitForDelete` does not do any deletion, it waits for resources to be deleted (in case the deletion takes time, like the case of volumes...etc).

**Comment by hprotzek** [comment]
@zak905 @mattfarina Anything I can help here. We are struggling with that bug and had to implement custom cleanup logic which makes everything quite complicated in our setup. If we can get this working, would be really great :-)

**Comment by zak905** [comment]
Hi @hprotzek, thank you but the PR is ready and tested as well. As you can see from the activity, it has changed the milestone several times. I am not familiar with how Helm release cycle works, but it seems like the PRs are merged following a FIFO scheme, and if the PR is not merged within the milestone period, it is postponed to the next one. I see that the 3.14 [milestone](https://github.com/helm/helm/milestone/135) in due only by 17 January, so the best case scenario is that it gets merged before then, and it's not guaranteed:) things are rather slow, and not all the planned PRs get merged. It's a pitty because this fix is quite in demand

**Review by joejulian — APPROVED** [review]

**Comment by joejulian** [comment]
Since this has two approvals and @mattfarina's CR was addressed, I'm going to go ahead and merge this.

**Comment by zak905** [comment]
Great, thanks @joejulian

**Comment by brtknr** [comment]
Been following this for a while and glad its finally merged, which release will this be packaged under?

**Comment by joejulian** [comment]
> Been following this for a while and glad its finally merged, which release will this be packaged under?

3.14.0. You can see that under "milestone", which is accurate for things that _are_ merged.
