### PR TITLE
chore: fix typo of public field

### LINKED ISSUE #31420: Fix typo in Package.InsecureSkipTLSverify
See #31418.

That would be a breaking change, so this would probably have to wait for v5. Do you want to open an issue or change this to a TODO comment?

_Originally posted by @TerryHowe in https://github.com/helm/helm/pull/31418#pullrequestreview-3376714015_

### PR DESCRIPTION
**Pull request by tisonkun**
**What this PR does / why we need it**:

Typically, we shall not change the public field name even if there is a typo. However, given that we're preparing for v4 release it may be a chance that we can fix it anyway.

This closes #31420.

**Special notes for your reviewer**:

**If applicable**:
- [x] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by TerryHowe — CHANGES_REQUESTED** [review]
That would be a breaking change, so this would probably have to wait for v5. Do you want to open an issue or change this to a TODO comment?

**Comment by tisonkun** [comment]
> That would be a breaking change, so this would probably have to wait for v5. Do you want to open an issue or change this to a TODO comment?

This is possible. Although, we don't cut the formal v4 release so I'd like to see if there is still a chance to have this patch included.

**Comment by TerryHowe** [comment]
> > That would be a breaking change, so this would probably have to wait for v5. Do you want to open an issue or change this to a TODO comment?
> 
> This is possible. Although, we don't cut the formal v4 release so I'd like to see if there is still a chance to have this patch included.

Breaking changes stopped when the beta was cut.

**Comment by mattfarina** [comment]
We can technically still make a change like this. We tend to avoid them. I just checked the docs on this and there is nothing in the documented process to block it.

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Comment by TerryHowe** [comment]
I'm good with it then

**Comment by tisonkun** [comment]
Thanks for your information and follow up @mattfarina @TerryHowe . IIRC helm 4.0 will [be released in mid Nov.](https://helm.sh/blog/path-to-helm-v4/)

Do you know any active maintainer who can review and get this patch merged?

File: pkg/action/package.go [hunk 1]
```diff
@@ -57,7 +57,7 @@ type Package struct {
 	CertFile              string
 	KeyFile               string
 	CaFile                string
-	InsecureSkipTLSverify bool
+	InsecureSkipTLSVerify bool
```
Comment (mattfarina) [inline pkg/action/package.go:60]: This property with this casing is used on numerous structs. It should be changed everywhere so that we are consistent.

**Review by mattfarina — DISMISSED** [review]
While I like this change, I think Helm needs to be consistent. The other places this property is named in the actions package needs to be updated along with this one.

**Comment by tisonkun** [comment]
@mattfarina All `TLSverify` find and replace now - 90d01915f9c210c7179fd2f9c34edab04619b204

**Comment by benoittgt** [comment]
LGTM

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Review by scottrigby — DISMISSED** [review]
LGTM :+1:

The only other places I see that could use this change are only variables in pkg/manager.go, which we can always make a PR after v4 release: 

```
% LC_ALL=C grep -Eni 'sverify' pkg/downloader/manager.go

318:		churl, username, password, insecureskiptlsverify, passcredentialsall, caFile, certFile, keyFile, err := m.findChartURL(dep.Name, dep.Version, dep.Repository, repos)
343:				getter.WithInsecureSkipVerifyTLS(insecureskiptlsverify),
728:func (m *Manager) findChartURL(name, version, repoURL string, repos map[string]*repo.ChartRepository) (url, username, password string, insecureskiptlsverify, passcredentialsall bool, caFile, certFile, keyFile string, err error) {
758:			insecureskiptlsverify = cr.Config.InsecureSkipTLSVerify
```

**Review by gjenkins8 — DISMISSED** [review]

**Comment by tisonkun** [comment]
@scottrigby Thanks for your findings.

Although they are all local variables that won't hurt the public API, I push 4576a81a00db475980aebeb5aed2502b2f755017 to fix the instance you found.

Shall we trigger the CI again and merge it now?

**Review by TerryHowe — APPROVED** [review]
/lgtm

Tests pass for me.

**Review by sabre1041 — APPROVED** [review]
LGTM

**Review by scottrigby — APPROVED** [review]
