### PR TITLE
fix(tiller): provide filename when YAML is bad

### LINKED ISSUE #957: helm install should report which template file caused an error
If a yaml template has an issue when deployed  to k8s, helm install will print something like:

 yaml: line 27: mapping values are not allowed in this context

It would be really helpful if the name of the template was printed as well, so you can figure out what needs to be fixed

### PR DESCRIPTION
**Pull request by technosophos**
This makes the template system less tolerant in the name of detecting
YAML parse errors before things are sent to Kubernetes. It returns a
more detailed error message when a template creates a manifest which is
not valid YAML.

Closes #957

### CODE REVIEW

**Comment by technosophos** [comment]
The failed build was a matter of a timeout while fetching a package. CircleCI fixed itself.

File: cmd/tiller/release_server.go [hunk 1]
```diff
@@ -218,10 +219,16 @@ func (s *releaseServer) engine(ch *chart.Chart) environment.Engine {
...
 		return nil, err
 	}
 
-	return s.performRelease(rel, req)
+	res, err := s.performRelease(rel, req)
+	if err != nil {
+		log.Printf("Failed install perform step: %s", err)
+		return nil, err
+	}
+	return res, nil
```
Comment (adamreese) [inline cmd/tiller/release_server.go]: nitty...
```
res, err := s.performRelease(rel, req)
 	if err != nil {
 		log.Printf("Failed install perform step: %s", err)
 	}
 	return res, err
```

Comment (technosophos) [inline cmd/tiller/release_server.go]: fixed
