### PR TITLE
fix: reinstall previously uninstalled chart with --keep-history

### LINKED ISSUE #11553: helm uninstall with --keep-history then upgrade --install results in UPGRADE FAILED "chartname" has no deployed releases
Output of `helm version`:
```
Version:"v3.10.2"
GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58"
GitTreeState:"clean"
GoVersion:"go1.19.3"
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:28:30Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.15-eks-fb459a0", GitCommit:"be82fa628e60d024275efaa239bfe53a9119c2d9", GitTreeState:"clean", BuildDate:"2022-10-24T20:33:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

Context:

I'm creating a dashboard where I want to preserve history for a helm chart.

This would allow me to know when a chart was first installed (after potential uninstalls) using the helm history command.

Reproduce Steps:

```
# initial install
helm -n xyz upgrade --install devactions devactions
# uninstall
helm -n xyz uninstall devactions --keep-history
# install again
helm -n xyz upgrade --install devactions devactions
```

> Error: UPGRADE FAILED: "devactions" has no deployed releases

I can only reinstall if I drop the instance without `--keep-history`.

### PR DESCRIPTION
**Pull request by alex-petrov-vt**
**What this PR does / why we need it**:

Before, if a chart was uninstalled using the `--keep-history` flag, the next
attempt to upgrade/install the chart would result in an error.

This PR fixes that by correctly checking if the last release of the chart
stored in history has been uninstalled and running the install with the
`--replace` flag if that's the case.

Closes #11553 

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

File: cmd/helm/upgrade.go [hunk 1]
```diff
@@ -96,7 +97,8 @@ func newUpgradeCmd(cfg *action.Configuration, out io.Writer) *cobra.Command {
 				// If a release does not exist, install it.
 				histClient := action.NewHistory(cfg)
 				histClient.Max = 1
-				if _, err := histClient.Run(args[0]); err == driver.ErrReleaseNotFound {
+				rel, err := histClient.Run(args[0])
+				if err == driver.ErrReleaseNotFound || (len(rel) > 0 && rel[len(rel)-1].Info.Status == release.StatusUninstalled) {
```
Comment (yxxhero) [inline cmd/helm/upgrade.go:101]: DRY?

File: cmd/helm/upgrade.go [hunk 2]
```diff
@@ -118,6 +120,9 @@ func newUpgradeCmd(cfg *action.Configuration, out io.Writer) *cobra.Command {
 					instClient.SubNotes = client.SubNotes
 					instClient.Description = client.Description
 					instClient.DependencyUpdate = client.DependencyUpdate
+					if len(rel) > 0 && rel[len(rel)-1].Info.Status == release.StatusUninstalled {
```
Comment (yxxhero) [inline cmd/helm/upgrade.go:123]: len(rel) > 0 && rel[len(rel)-1].Info.Status == release.StatusUninstalled

DRY?

**Review by joejulian — APPROVED** [review]
I think this makes sense, but since it's a behavior change we should get another approval.

**Review by mattfarina — APPROVED** [review]
