### PR TITLE
fix(pkg/cli): ensure correct configuration from kubeconfig file

### LINKED ISSUE #7539: Helm v3 getting current-context wrong
If I run: kubectl config current-context - I get the correct cluster.
My KUBECONFIG=/home/klavs/.kube/microk8s:/home/klavs/.kube/t-boss-ca:/home/klavs/.kube/p-boa-kube-ca

but helm picks the wrong cluster. Thats VERY dangerous - when your kubectl config current-context says you're working on a different cluster (and my PS1 shows that as the active one as well)..

If I run helm - pointing to the cluster config file I want it to select like this - it works:
KUBECONFIG=/home/klavs/.kube/t-boss-ca helm ls

### PR DESCRIPTION
**Pull request by adamreese**
Bind Helm flags to Kubernetes configuration loader to get a merged
config with kubeconfig.

Fixes: #7539

### CODE REVIEW

File: pkg/cli/environment.go [hunk 1]
```diff
@@ -107,42 +111,27 @@ func (s *EnvSettings) EnvVars() map[string]string {
...
 		"HELM_NAMESPACE":         s.Namespace(),
-		"HELM_KUBECONTEXT":       s.KubeContext,
-		"HELM_KUBETOKEN":         s.KubeToken,
-		"HELM_KUBEAPISERVER":     s.KubeAPIServer,
-	}
 
+		// broken, these are populated from helm flags and not kubeconfig.
+		"HELM_KUBECONTEXT":   s.KubeContext,
+		"HELM_KUBETOKEN":     s.KubeToken,
+		"HELM_KUBEAPISERVER": s.KubeAPIServer,
```
Comment (adamreese) [inline pkg/cli/environment.go:118]: Not sure what to do with this

Comment (technosophos) [reply pkg/cli/environment.go:118]: Same... I don't understand their purpose in the first place. I guess leaving them alone is the safest bet.

**Review by technosophos — APPROVED** [review]
LGTM. cobra.OnInitialize is GREAT

**Review by technosophos — APPROVED** [review]
Re-reviewed with the changes to the unit tests.
