### PR TITLE
Fix filenames in tarball created on windows

### LINKED ISSUE #3764: Windows back slash carry to file name after unzip
Output of `helm version`:

`Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}`

When use `helm package ./blah` command on windows, and then unpack (use `tar`) the `tgz` file under linux, I see

image

That is, the black slashs that come from windows become the file names.

### PR DESCRIPTION
**Pull request by muehlburger**
This fixes #3764.

### CODE REVIEW

File: pkg/chartutil/save.go [hunk 1]
```diff
@@ -204,6 +205,7 @@ func writeTarContents(out *tar.Writer, c *chart.Chart, prefix string) error {
 // writeToTar writes a single file to a tar archive.
 func writeToTar(out *tar.Writer, name string, body []byte) error {
 	// TODO: Do we need to create dummy parent directory names if none exist?
+	name = strings.Replace(name, "\\", "/", -1)
```
Comment (technosophos) [inline pkg/chartutil/save.go]: I think you want to use `filepath.ToSlash`/`filepath.FromSlash` here.

**Comment by muehlburger** [comment]
I refactored the code.

**Review by bacongobbler — APPROVED** [review]
