### PR TITLE
fix typo in load_plugins.go

### LINKED ISSUE #12855: why don't helm  pass --insecure-skip-tls-verify into plugin?
Output of `helm version`:  
helm v3.14.2  

Output of `kubectl version`:  

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

why don't helm  pass --insecure-skip-tls-verify into plugin?

see: https://github.com/helm/helm/pull/10944/files  maybe it's a typo?

### PR DESCRIPTION
**Pull request by yxxhero**
**What this PR does / why we need it**:
fix: https://github.com/helm/helm/issues/12855

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by yxxhero** [comment]
see: https://github.com/helm/helm/issues/12855

**Review by gjenkins8 — APPROVED** [review]

**Comment by yxxhero** [comment]
origin PR: https://github.com/helm/helm/pull/10944

File: cmd/helm/load_plugins.go [hunk 1]
```diff
@@ -154,7 +154,7 @@ func callPluginExecutable(pluginName string, main string, argv []string, out io.
 func manuallyProcessArgs(args []string) ([]string, []string) {
 	known := []string{}
 	unknown := []string{}
-	kvargs := []string{"--kube-context", "--namespace", "-n", "--kubeconfig", "--kube-apiserver", "--kube-token", "--kube-as-user", "--kube-as-group", "--kube-ca-file", "--registry-config", "--repository-cache", "--repository-config", "--insecure-skip-tls-verify", "--tls-server-name"}
+	kvargs := []string{"--kube-context", "--namespace", "-n", "--kubeconfig", "--kube-apiserver", "--kube-token", "--kube-as-user", "--kube-as-group", "--kube-ca-file", "--registry-config", "--repository-cache", "--repository-config", "--kube-insecure-skip-tls-verify", "--kube-tls-server-name"}
```
Comment (mattfarina) [inline cmd/helm/load_plugins.go:157]: It appears there is both a [`--kube-insecure-skip-tls-verify`](https://github.com/helm/helm/blob/098eed2c07c548e15fa383e11e507486ab3cb410/pkg/cli/environment.go#L150) and a [`--insecure-skip-tls-verify`](https://github.com/helm/helm/blob/098eed2c07c548e15fa383e11e507486ab3cb410/cmd/helm/push.go#L97) flag.

Can both be listed in this slice?

Comment (yxxhero) [reply cmd/helm/load_plugins.go:157]: @mattfarina I think not. `--insecure-skip-tls-verify` There is no corresponding environment variable

**Comment by yxxhero** [comment]
@joejulian ping

**Review by mattfarina — APPROVED** [review]

**Comment by mattfarina** [comment]
Merging with one approval since this is an XS, which is allowed.
