### PR TITLE
Delete old deps after chart deps are updated

### LINKED ISSUE #2788: 'helm dependency update' deletes charts it can't replace (v2.5.1)
I ran `helm dependency update` while `helm serve` wasn't running. helm decided the best thing to do was delete all the subcharts, even though it could not download new versions! Afterwards the 'charts' folder was empty.

I would have expect either:
- no subcharts would be updated if a download error occured, or 
- only charts for which a replacement had been downloaded would be deleted

```
$ helm dependency update drupal-efs
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Deleting outdated charts
Saving 3 charts
Downloading mysql-efs from repo http://127.0.0.1:8879/charts
Error: could not download http://127.0.0.1:8879/charts/mysql-efs-0.1.8.tgz: Get http://127.0.0.1:8879/charts/mysql-efs-0.1.8.tgz: dial tcp 127.0.0.1:8879: getsockopt: connection refused
```

```
Client: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
```

### PR DESCRIPTION
**Pull request by nebril**
This change changes the order of operations in
pkg/downloader.Manager.downloadAll

Old charts are moved to tmp directory which is restored in case any
dependency update fails. Otherwise tmp dir is deleted.

fixes #2788

### CODE REVIEW

File: pkg/downloader/manager.go [hunk 1]
```diff
@@ -206,6 +206,7 @@ func (m *Manager) downloadAll(deps []*chartutil.Dependency) error {
 	}
 
 	destPath := filepath.Join(m.ChartPath, "charts")
+	tmpPath := filepath.Join(m.ChartPath, "tmpcharts")
```
Comment (bacongobbler) [inline pkg/downloader/manager.go]: minor nitpick, but a common pattern would be to name the directory `charts.tmp`. I wouldn't consider this a blocker, but just a passing note :)

**Review by bacongobbler — APPROVED** [review]

**Comment by bacongobbler** [comment]
Is this still considered a work in progress? The code looks complete to me.

File: pkg/downloader/manager.go (hunk 1 above)
Comment (bacongobbler) [inline pkg/downloader/manager.go]: Something also to consider. Would it be better to use [`os.TempDir()`](https://golang.org/pkg/os/#TempDir) instead since we don't actually do anything with this directory?

Comment (bacongobbler) [inline pkg/downloader/manager.go]: Sorry, I meant [`ioutil.TempDir("", "helmcharts")`](https://golang.org/pkg/io/ioutil/#TempDir).

**Comment by jascott1** [comment]
I tested and found it to be functional (not deleting before chart retrieval).

File: pkg/downloader/manager.go [hunk 2]
```diff
@@ -216,22 +217,25 @@ func (m *Manager) downloadAll(deps []*chartutil.Dependency) error {
...
+	if err := os.Rename(destPath, tmpPath); err != nil {
+		return fmt.Errorf("Unable to move current charts to tmp dir: %v", err)
+	}
+
+	if err := os.MkdirAll(destPath, 0755); err != nil {
+		return err
 	}
 
 	fmt.Fprintf(m.Out, "Saving %d charts\n", len(deps))
+	var saveError error
```
Comment (jascott1) [inline pkg/downloader/manager.go]: nit: Consider custom error type

**Review by jascott1 — APPROVED** [review]
Minor nit but looks good.

File: pkg/downloader/manager.go (hunk 1 above)
Comment (nebril) [inline pkg/downloader/manager.go]: TempDir creates the directory, I use rename on existing charts dir so I don't need to move all its contents.

I think concurrent `dep up` calls would break anyway as we move old charts dir and if one of the commands fail to download we would replace existing state with new chart - possibly during other `dep up` download, which would probably fail miserably. Making tmp dir names random would not help here.

Comment (nebril) [inline pkg/downloader/manager.go]: If we want to make it safe for concurrent calls we should think about introducing some kind of lock file which would make commands tamper with chart dir sequentially.

**Comment by thomastaylor312** [comment]
I'll merge this because @nebril can't merge it due to some missing permissions
