### PR TITLE
fix(registry): address anonymous pull issue

### LINKED ISSUE #12423: helm 3.13.0 helm pull fails with 401 unauthorized
helm pull on oci artifact fails with 401 unauthorized error with 3.13.0. The chart is hosted on azure container registry and anonymous pull is enabled on this repository. The same command worked with previous helm version 3.12.3.

Command: `helm pull oci://xxxxxxxx.azurecr.io/charts/xxxxx --version xxxxxxx --untar`

Error Response: `Error: unexpected status from HEAD request to https://xxxxxxxxxxx.azurecr.io/v2/charts/xxxxxxxxxx/manifests/xxxxxxxx: 401 Unauthorized`

Output of `helm version`:
version.BuildInfo{Version:"v3.13.0", GitCommit:"825e86f6a7a38cef1112bfa606e4127a706749b1", GitTreeState:"clean", GoVersion:"go1.20.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6", GitCommit:"11902a838028edef305dfe2f96be929bc4d114d8", GitTreeState:"clean", BuildDate:"2023-06-19T16:11:29Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

### PR DESCRIPTION
**Pull request by hiddeco**
**What this PR does / why we need it**:

The assumption that either a username and/or password OR an error is returned appears to be wrong, and results in an error later on which looks something like the following:

```
failed to authorize: failed to fetch anonymous token: unexpected status
from GET request to https://auth.docker.io/token?scope=repository%3AXXX%2FYYY%3Apull&service=registry.docker.io:
401 Unauthorized
```

To mitigate this, confirm we actually have one of the values before setting the `Authorization` header.

Should fix #12423

**Special notes for your reviewer**:

This could (and should) really have more test coverage, but this is beyond the time I have available at present.

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

File: pkg/registry/client.go [hunk 1]
```diff
@@ -105,10 +105,11 @@ func NewClient(options ...ClientOption) (*Client, error) {
 			if err != nil {
 				return nil, errors.New("unable to retrieve credentials")
```
Comment (hiddeco) [inline pkg/registry/client.go:106]: Not directly related to this issue, but I am wondering if swallowing the error over doing `fmt.Errorf("unable to retrieve credentials: %w, err)` is the best thing to do?

Comment (mattfarina) [reply pkg/registry/client.go:106]: We shouldn't swallow the error.

**Review by mattfarina — APPROVED** [review]

**Comment by mattfarina** [comment]
Note, this still needs a second maintainer to approve.

File: pkg/registry/client.go (hunk 1 above)
Comment (hiddeco) [reply pkg/registry/client.go:106]: I'll fill a separate PR to address this to allow you to move on with this quickly.

File: pkg/registry/client.go [hunk 2]
```diff
@@ -105,11 +105,13 @@ func NewClient(options ...ClientOption) (*Client, error) {
...
 			}
-			// A blank returned username and password value is a bearer token
-			if username == "" && password != "" {
-				headers.Set("Authorization", fmt.Sprintf("Bearer %s", password))
-			} else {
-				headers.Set("Authorization", fmt.Sprintf("Basic %s", basicAuth(username, password)))
+			if username != "" || password != "" {
```
Comment (gjenkins8) [inline pkg/registry/client.go:108]: To me, this logic could be most plainly written as:

```
if password != "" {
    if username != "" {
        headers.Set("Authorization", fmt.Sprintf("Basic %s", basicAuth(username, password)))
    } else {
       // Without a username, we assume this is a bearer token.
       headers.Set("Authorization", fmt.Sprintf("Bearer %s", password))
    }
}
```

(but I am nit-picking, and fixing this bug is priority)

**Comment by joejulian** [comment]
Sorry for the push... Hit the wrong repo. Consider pulling in https://github.com/helm/helm/commit/b3c3a973443fdab4756f594ffebaeb329e105f33 which makes it testable and adds unit tests.

**Comment by hiddeco** [comment]
@joejulian have applied your patch with some minor tweaks, think this should be good to go now.

**Review by joejulian — APPROVED** [review]

**Review by mattfarina — APPROVED** [review]

**Comment by nikolaigut** [comment]
Is it possible to release this fix?

**Comment by glasser** [comment]
Is there a planned patch release for this PR?

**Comment by nikolaigut** [comment]
> Is there a planned patch release for this PR?

Yes, the release is planned in the Milestone 3.13.1 (https://github.com/helm/helm/milestone/134).
