### PR TITLE
fix(helm): correctly convert types on --set flag

### LINKED ISSUE #1449: --set option not parsing as boolean
Original issue is on the kubernetes/charts repo: https://github.com/kubernetes/charts/issues/138

The output of the manifest and computed values is correct, however, a conditional in the template to create a PVC is not being parsed correctly because it creates the PVC even if I set the value of persistence.enabled to false on the command line using the --set flag.

```
$ helm version
Client: &version.Version{SemVer:"v2.0.0-beta.1", GitCommit:"58be8c9fce50f0657425443b83307ba91789b794", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.0.0-beta.1", GitCommit:"05c04bccae63c6392ec0cb0e27790650167279f0", GitTreeState:"clean"}
```

### PR DESCRIPTION
**Pull request by michelleN**
fixes #1449

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/helm/1451)

### CODE REVIEW

File: cmd/helm/install.go [hunk 1]
```diff
@@ -285,12 +286,32 @@ func (v *values) Set(data string) error {
 	return nil
 }
 
+func typedVal(val string) interface{} {
+	if val == "true" {
```
Comment (prydonius) [inline cmd/helm/install.go]: How about
```
if iv, err := strconv.ParseBool(val) {
  return iv
}
```
as this will also parse TRUE, True, t, 1, etc.
https://golang.org/pkg/strconv/#ParseBool. But if we want to parse 1 as an integer we'd need to move this below.

Comment (prydonius) [inline cmd/helm/install.go]: However, I'm also okay enforcing people to use `true` and `false` so we don't need to worry about order issues.

File: cmd/helm/install.go [hunk 2]
```diff
@@ -285,12 +286,32 @@ func (v *values) Set(data string) error {
...
+		return true
+	}
+
+	if val == "false" {
+		return false
+	}
+
+	if iv, err := strconv.ParseInt(val, 10, 64); err == nil {
```
Comment (prydonius) [inline cmd/helm/install.go]: Technically we may not need to parse integers, since in templating, a string and integer will generally be printed the same. The only case would be if a template function needed an integer to perform integer operations, but I haven't really seen that usecase.

File: cmd/helm/install.go (hunk 1 above)
Comment (technosophos) [inline cmd/helm/install.go]: My feeling is that we should treat 0 and 1 as integers. But we probably should `string.ToLower()` val before comparing it.

File: cmd/helm/install.go (hunk 2 above)
Comment (technosophos) [inline cmd/helm/install.go]: The YAML converter seemed to quote these, which then forced them to be interpreted as strings. So I think we need this in order to avoid the issue people are seeing with the strict schema enforcement in Kube 1.4.

Comment (prydonius) [inline cmd/helm/install.go]: @technosophos I think the issue was more that people were using the quote function for integers. As far as I know, a simple `{{.Values.replicas}}` won't add quotes if it's a string.

File: cmd/helm/install.go [hunk 3]
```diff
@@ -285,12 +286,32 @@ func (v *values) Set(data string) error {
 	return nil
 }
 
+func typedVal(val string) interface{} {
+	if strings.ToLower(val) == "true" {
+		return true
+	}
+
+	if strings.ToLower(val) == "false" {
```
Comment (fibonacci1729) [inline cmd/helm/install.go]: Same as above.
