### PR TITLE
fix: Use server-side apply for object create during update

### LINKED ISSUE #31516: Helm 4 ignores Server-Side Apply approach for new resources in a helm release and then can't update the release due to conflicts
### What happened?

`Helm4` uses `operation: Update` in `managedFields` for new resources in helm releases. It may lead to a problem that helm can't update such releases without `--force-conflicts` in next updates.

At the same time, k8s doc says this:
```
The field management record consists of basic information about the managing entity itself, plus details about the fields being managed and the relevant operation (Apply or Update). If the request that last changed that field was a Server-Side Apply patch then the value of operation is Apply; otherwise, it is Update.
```

### What did you expect to happen?

Operation for new resources in `managedFields` should be `Apply` and next updates complete without error and needing to use `--force-conflicts`

### How can we reproduce it (as minimally and precisely as possible)?

1) Create `Chart.yaml`:
```yaml
apiVersion: v2
version: 1.0.0
name: update-instead-apply
```
2) Create the following deployment.yaml in `templates` folder:
```yaml
{{- $i := 1 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ $i }}
  labels:
    app: {{ $.Release.Name }}-{{ $i }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-{{ $i }}
  template:
    metadata:
      name: {{ $.Release.Name }}-{{ $i }}
      labels:
        app: {{ $.Release.Name }}-{{ $i }}
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
---
{{- if $.Values.deployment2 }}
{{- $i := 2 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ $i }}
  labels:
    app: {{ $.Release.Name }}-{{ $i }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-{{ $i }}
  template:
    metadata:
      name: {{ $.Release.Name }}-{{ $i }}
      labels:
        app: {{ $.Release.Name }}-{{ $i }}
    spec:
      containers:
        - name: bash
          image: bash
          imagePullPolicy: IfNotPresent
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
            - bash
            - -cex
            - |-
              trap 'exit 0' SIGINT SIGTERM
              while true; do
                sleep 1
              done
      restartPolicy: Always
{{- end }}
---
```

3) Run the following command to install the helm chart:
```shell
helm upgrade -i -n default test . --server-side=true --wait --timeout 15m --debug
```

4) Check `managedFields` for first deployment:
```shell
╰─ kubectl get deploy -n default test-1 --show-managed-fields -o yaml | grep -A1 "manager: helm"
    manager: helm
    operation: Apply
```

5) Enable second deployment and upgrade the release:
```shell
helm upgrade -i -n default test . --server-side=true --wait --timeout 15m --debug --set deployment2=true
```

6) Check `managedFields` for both deployments:
```shell
╰─ kubectl get deploy -n default test-1 --show-managed-fields -o yaml | grep -A1 "manager: helm"                 
    manager: helm
    operation: Apply
╰─ kubectl get deploy -n default test-2 --show-managed-fields -o yaml | grep -A1 "manager: helm"
    manager: helm
    operation: Update
```

7) Run update again and get conflict:
```
╰─ helm upgrade -i -n default test . --server-side=true --wait --timeout 15m --debug --set deployment2=true
level=DEBUG msg="number of dependencies in the chart" dependencies=0
level=INFO msg="WARN upgrade failed name=test error=\"conflict occurred while applying object default/test-2 apps/v1, Kind=Deployment: Apply failed with 1 conflict: conflict with \\\"helm\\\" using apps/v1: .spec.template.spec.containers[name=\\\"bash\\\"].env[name=\\\"HOSTNAME\\\"].valueFrom.fieldRef\""
Error: UPGRADE FAILED: conflict occurred while applying object default/test-2 apps/v1, Kind=Deployment: Apply failed with 1 conflict: conflict with "helm" using apps/v1: .spec.template.spec.containers[name="bash"].env[name="HOSTNAME"].valueFrom.fieldRef
```

### Helm version

<details>

```console
╰─ helm version
version.BuildInfo{Version:"v4.0.0", GitCommit:"99cd1964357c793351be481d55abbe21c6b2f4ec", GitTreeState:"clean", GoVersion:"go1.25.3", KubeClientVersion:"v1.34"}
```
</details>

### Kubernetes version

<details>

```console
╰─ kubectl version
Client Version: v1.34.2
Kustomize Version: v5.7.1
Server Version: v1.28.15+k3s1
Warning: version difference between client (1.34) and server (1.28) exceeds the supported minor version skew of +/-1
```

</details>

Also tested on `v1.34.1`

### PR DESCRIPTION
**Pull request by gjenkins8**
**What this PR does / why we need it**:
It was missed during server-side apply development that the Kube client "update" method also creates resources.
Fix this creation to use server-side apply based methods (if server-side apply enabled)

fixes: #31516

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by Noksa — COMMENTED** [review]
`createApplyFunc` is not used

File: pkg/kube/client.go [hunk 1]
```diff
@@ -512,7 +525,7 @@ func (c *Client) BuildTable(reader io.Reader, validate bool) (ResourceList, erro
 		transformRequests)
 }
 
-func (c *Client) update(originals, targets ResourceList, updateApplyFunc UpdateApplyFunc) (*Result, error) {
+func (c *Client) update(originals, targets ResourceList, createApplyFunc CreateApplyFunc, updateApplyFunc UpdateApplyFunc) (*Result, error) {
```
Comment (Noksa) [inline pkg/kube/client.go:528]: `createResource` should be replaced by `createApplyFunc` in the function to make the fix work :-)

**Review by Noksa — CHANGES_REQUESTED** [review]

File: pkg/kube/client.go [hunk 2]
```diff
@@ -268,6 +271,36 @@ func ClientCreateOptionFieldValidationDirective(fieldValidationDirective FieldVa
...
+			logger := c.Logger().With(
+				slog.String("namespace", target.Namespace),
+				slog.String("name", target.Name),
+				slog.String("gvk", target.Mapping.GroupVersionKind.String()))
+			if err != nil {
+				logger.Debug("Error patching resource", slog.Any("error", err))
+				return err
+			}
+
+			logger.Debug("Patched resource")
```
Comment (Noksa) [inline pkg/kube/client.go]: I'd suggest to rename it to `Created resource` since it is `create` operation

**Review by Noksa — APPROVED** [review]
LGTM

**Review by mattfarina — APPROVED** [review]
lgtm
