### PR TITLE
Ingress v1 template

### LINKED ISSUE #9485: Ingress syntax mismatch, helm 3.5.3 and kubernetes 19.x
Output of `helm version`: 
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}

Output of `kubectl version`:
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
minikube version: v1.13.1

Helm documentation, supported kubernetes version:
https://helm.sh/docs/topics/version_skew/

While deploying a helm chart to a local minikube cluster, ingress seems to have an outdated syntax in <CHART-NAME>/templates/ingress.yaml, resulting in following error message:
"Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend]"

Beside this i was also required to change the following part in <CHART-NAME>/templates/ingress.yaml
(at row 5)
from:
```yaml
apiVersion: networking.k8s.io/v1beta1
```
to:
```yaml
apiVersion: networking.k8s.io/v1
```

However, changes according to the following tip:
https://stackoverflow.com/a/64126069/517457
Referencing:
https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

And changing in <CHART-NAME>/templates/ingress.yaml, does acctually make the above helm install error go away.
(starting at row 33)
from:
```yaml
paths:
          {{- range .paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
```

to:
```yaml
paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
```

### PR DESCRIPTION
**Pull request by sagikazarmark**
**What this PR does / why we need it**:

Improve ingress template to add support for new ingress features added in Kubernetes 1.18 and 1.19:

- `networking.k8s.io/v1` support
- `ingressClassName` field support

**Special notes for your reviewer**:

### CODE REVIEW

File: pkg/chartutil/create.go [hunk 1]
```diff
@@ -147,16 +147,15 @@ service:
 
 ingress:
   enabled: false
+  className:
```
Comment (adrianliechti) [inline pkg/chartutil/create.go:150]: would it be an idea to # this?
it's optional (because of ingress default class)

do you prefer to keep the annotation hint for kubernetes.io/ingress.class anyway?

Comment (sagikazarmark) [reply pkg/chartutil/create.go:150]: > would it be an idea to # this?

It has the same effect, but I think it's better this way.

> do you prefer to keep the annotation hint for kubernetes.io/ingress.class anyway?

That's an interesting question. I don't mind keeping it.

Comment (adrianliechti) [reply pkg/chartutil/create.go:150]: when comparing to serviceaccount -> name, this might be another approach for the sake of consistency:  
same effect - but includes note for the customer.

```
# If not set, the default ingress class is used
className: ""
```

File: pkg/chartutil/create.go [hunk 2]
```diff
@@ -147,16 +147,15 @@ service:
...
     # kubernetes.io/ingress.class: nginx
     # kubernetes.io/tls-acme: "true"
   hosts:
     - host: chart-example.local
       paths:
-      - path: /
-        backend:
-          serviceName: chart-example.local
-          servicePort: 80
+        - path: /
```
Comment (mab) [inline pkg/chartutil/create.go:157]: indentation seems to be incorrect.

Comment (sagikazarmark) [reply pkg/chartutil/create.go:157]: Why? What's wrong with it?

Comment (adrianliechti) [reply pkg/chartutil/create.go:157]: in most of the case node's children are intended by two characters (see hosts -> host).
on paths -> path it was not; márk fixed that (also on other parts of the file). it looks good for me

**Review by mab — APPROVED** [review]

File: pkg/chartutil/create.go (hunk 1 above)
Comment (sagikazarmark) [reply pkg/chartutil/create.go]: Updated the default to string. Thanks!

**Comment by sagikazarmark** [comment]
@bacongobbler do you think this fits into the 3.6 milestone?

**Review by bacongobbler — APPROVED** [review]
LGTM. Needs another maintainer to sign off on the changes as per the contributing policy.

**Review by dunglas — APPROVED** [review]

**Comment by sagikazarmark** [comment]
Today is the tentative date for RC1. Since this is a feature change, it should be merged before RC1 is tagged.

Also, the workflow run needs approval so that tests can be run by the CI.

**Comment by bacongobbler** [comment]
I've gone ahead and approved the workflow. You'll have to reach out to the other core maintainers and find someone with enough time on their hands to review this.

**Comment by sagikazarmark** [comment]
Thanks @bacongobbler !

**Review by technosophos — APPROVED** [review]
I am not a fan of the trend of making create's logic increasingly complicated. It was never my intent that the default chart would be anything other than a bare-bones scaffold. I am worried that with version-specific code, we are going to start seeing templates here that are so complicated that nobody will be able to maintain them or understand what they do. As a default experience, that is bad.

That said... we can't remove the ingress code during Helm 3's lifecycle. So apparently we _need_ to add this kind of logic. So I am approving this.
