### PR TITLE
fix(lint): Lint error message for valid names

### LINKED ISSUE #8876: Incorrect regex in linting error message
The lint correctly identifies an invalid name because of uppercase in the name. Howevere, the error message is incorrect as it specifies the wrong regex expression. It should be `^[a-z0-9]([-a-z0-9]*[a-z0-9])?(.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$`

```console
❯ helm lint mychart-3.0.0.tgz 
==> Linting mychart-3.0.0.tgz
[ERROR] templates/configmap.yaml: object name does not conform to Kubernetes naming requirements: "appName-v1": invalid metadata name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not longer than 253
[ERROR] templates/deployment.yaml: object name does not conform to Kubernetes naming requirements: "appName-v1": invalid metadata name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not longer than 253
[ERROR] templates/service.yaml: object name does not conform to Kubernetes naming requirements: "appName-v1": invalid metadata name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not longer than 253

Error: 1 chart(s) linted, 1 chart(s) failed
```
-----
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-07-04T15:01:15Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS

### PR DESCRIPTION
**Pull request by hickeyma**
**What this PR does / why we need it**:

The lint error message for valid names is incorrectly showing the regex as follows:
`invalid metadata name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not longer than 253`

It should read as:
`invalid metadata name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 253`

Closes #8876 

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

File: pkg/chartutil/validate_name.go [hunk 1]
```diff
@@ -39,11 +39,11 @@ var (
 	errMissingName = errors.New("no name provided")
 
 	// errInvalidName indicates that an invalid release name was provided
-	errInvalidName = errors.New("invalid release name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not longer than 53")
+	errInvalidName = errors.New("invalid release name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not be longer than 53")
 
 	// errInvalidKubernetesName indicates that the name does not meet the Kubernetes
 	// restrictions on metadata names.
-	errInvalidKubernetesName = errors.New("invalid metadata name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not longer than 253")
+	errInvalidKubernetesName = errors.New("invalid metadata name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 253")
```
Comment (mattfarina) [inline pkg/chartutil/validate_name.go:46]: Why did you change the structure so much? Wouldn't removing the `A-Z` have been enough? That would have left us with `^(([a-z0-9][-a-z0-9_.]*)?[a-z0-9])+$`. Am I missing something?

File: pkg/chartutil/validate_name.go [hunk 2]
```diff
@@ -39,11 +39,11 @@ var (
 	errMissingName = errors.New("no name provided")
 
 	// errInvalidName indicates that an invalid release name was provided
-	errInvalidName = errors.New("invalid release name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not longer than 53")
+	errInvalidName = errors.New("invalid release name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not be longer than 53")
```
Comment (mattfarina) [inline pkg/chartutil/validate_name.go:42]: Don't the uppercase letters need to be removed from the regex here as well?

File: pkg/chartutil/validate_name.go (hunk 1 above)
Comment (hickeyma) [reply pkg/chartutil/validate_name.go:46]: because that is the actual regex now

File: pkg/chartutil/validate_name.go (hunk 2 above)
Comment (hickeyma) [reply pkg/chartutil/validate_name.go:42]: Shoot, meant to add that also when updating it. Good catch, thanks

File: pkg/chartutil/validate_name.go (hunk 1 above)
Comment (mattfarina) [reply pkg/chartutil/validate_name.go:46]: @hickeyma Do you mean the actual regex the k8s uses? If so, do you have a reference pointer?

**Comment by mattfarina** [comment]
Moving to 3.4.1 as `errInvalidName` needs to be tweaked.

File: pkg/chartutil/validate_name.go (hunk 1 above)
Comment (hickeyma) [reply pkg/chartutil/validate_name.go]: Good idea, using the pattern directly now.

File: pkg/chartutil/validate_name.go (hunk 2 above)
Comment (hickeyma) [reply pkg/chartutil/validate_name.go]: Updated

**Comment by hickeyma** [comment]
Updated and ready for review again @mattfarina

**Review by bacongobbler — APPROVED** [review]

**Review by mattfarina — APPROVED** [review]
lgtm

**Comment by hickeyma** [comment]
Thanks for the reviews @mattfarina @bacongobbler
