### PR TITLE
Fail message is now the same as the required message.

### LINKED ISSUE #8973: Helm function 'fail' should not fail when doing 'helm lint'
When executing `helm lint` directives such as this fail the linting:

```yaml
failure: {{ fail "this is a failure!" }}
```

The same problem was already fixed for the `required` function: https://github.com/helm/helm/pull/4221
An issue had already been written on `failure` but was closed due to inactivity: https://github.com/helm/helm/issues/3026

In order to lint charts using `fail` this needs to be fixed.

Reference: https://helm.sh/docs/chart_template_guide/function_list/#fail

### PR DESCRIPTION
**Pull request by wizbit**
closes #8973 Helm function 'fail' should not fail when doing 'helm lint'

Signed-off-by: Marcus Speight <marcus.speight@hotmail.co.uk>

**What this PR does / why we need it**:
The fail function output does not match the required function output.

e.g.
`{{ required "This is an error" .notExist }}` produces `Error: execution error at (example/templates/required.yaml:1:3): This is an error`
`{{ fail "This is an error" }}` produces `Error: template: example/templates/fail.yaml:1:3: executing "example/templates/service.yaml" at <fail "This is an error">: error calling fail: This is an error`

This PR makes the fail message identical to the required message.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

File: pkg/engine/engine_test.go [hunk 1]
```diff
@@ -286,6 +286,23 @@ func TestExecErrors(t *testing.T) {
...
 }
 
+func TestFailErrors(t *testing.T) {
+	vals := chartutil.Values{"Values": map[string]interface{}{}}
+
+	failtpl := `{{ fail "This is an error" }}`
+	tplsFailed := map[string]renderable{
+		"failtpl": {tpl: failtpl, vals: vals},
+	}
+	_, err := new(Engine).render(tplsFailed)
```
Comment (bacongobbler) [inline pkg/engine/engine_test.go:296]: can you also add a test when `LintMode` is enabled?

**Review by bacongobbler — CHANGES_REQUESTED** [review]

File: pkg/engine/engine_test.go (hunk 1 above)
Comment (wizbit) [reply pkg/engine/engine_test.go:296]: Done

**Comment by thernstig** [comment]
This does not close #8973. #8973 is about `helm lint` failing charts with the `fail` directive.

**Comment by bacongobbler** [comment]
That's exactly what this PR fixes, @thernstig. If the engine is in `LintMode` (i.e. `helm lint`), `fail` will no longer fail. The test case disproves your assumption.

If you're referring to another issue, can you please present your case in the form of a test similar to what @wizbit provided in this PR?

**Review by bacongobbler — APPROVED** [review]
LGTM. Thanks for fixing this.

Will need another maintainer's approval before we can merge.

**Comment by thernstig** [comment]
@bacongobbler any chance you could another maintainer to approve this? :)

**Review by hickeyma — APPROVED** [review]
LGTM, thanks @wizbit for the fix.
