### PR TITLE
fix(kube): use correct object type in watch

### LINKED ISSUE #3902: 'helm test' never returns with 2.9.2-rc3
Running `helm test` with Helm 2.9.2-rc3 never returns. Tests pass but the command hangs. I tested with `stable/mongodb-replicaset` and `incubator/keycloak`.

**With Helm 2.9.3-rc3:**
```
$ helm test messy-whale                                                                                                            
RUNNING: keycloak-messy-whale-test
```

**With Helm 2.8.2:**
```
$ helm test messy-whale                                                                                                            
RUNNING: keycloak-messy-whale-test
PASSED: keycloak-messy-whale-test
$
```

Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.9.0-rc3", GitCommit:"60abcdca41f544caaecb224acbfb92aee11e1f6e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0-rc3", GitCommit:"60abcdca41f544caaecb224acbfb92aee11e1f6e", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:14:31Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.6-gke.0", GitCommit:"cb151369f60073317da686a6ce7de36abe2bda8d", GitTreeState:"clean", BuildDate:"2018-03-21T19:01:20Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

`GKE`

### PR DESCRIPTION
**Pull request by adamreese**
fixes #3902

### CODE REVIEW

File: pkg/kube/client.go [hunk 1]
```diff
@@ -686,12 +685,27 @@ func (c *Client) watchPodUntilComplete(timeout time.Duration, info *resource.Inf
...
 
 	return err
 }
 
+func isPodComplete(event watch.Event) (bool, error) {
+	o, ok := event.Object.(*core.Pod)
+	if !ok {
+		return true, fmt.Errorf("expected a *core.Pod, got %T", event.Object)
+	}
+	if event.Type == watch.Deleted {
```
Comment (bacongobbler) [inline pkg/kube/client.go]: is it possible to re-call `conditions.PodCompleted` after we've done the type checking? e.g.

```
func isPodComplete(event watch.Event) (bool, error) {
	o, ok := event.Object.(*core.Pod)
	if !ok {
		return true, fmt.Errorf("expected a *core.Pod, got %T", event.Object)
	}
	return conditions.PodCompleted(e)
}
```

From first glance, that seems to be the only difference here between `isPodComplete` and `conditions.PodCompleted`. Is there something else I'm missing? :)

**Review by bacongobbler — APPROVED** [review]
Left a comment about the code itself, but with or without that refactor the code LGTM. :+1:

File: pkg/kube/client.go (hunk 1 above)
Comment (bacongobbler) [reply pkg/kube/client.go]: gotcha. lgtm then!
