### PR TITLE
Fix rollback for missing resources

### LINKED ISSUE #13437: Failure in pre-upgrade when a manifest is removed makes it impossible to roll back
If a chart used to contain a manifest like a ConfigMap that is no longer present in the next version of the chart and the upgrade fails during pre-upgrade, `helm rollback` will fail spuriously.

A manifest may no longer be present in a new version of the chart for a number of reasons: Merging RoleBindings, combining two Deployments of one container per pod into one Deployment of two containers per pod, etc.

To reproduce create a chart which installs a ConfigMap upon installation, contains nothing during upgrade except a pre-upgrade hook that will fail like so:

```yaml
{{- if .Release.IsInstall -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg
data:
  foo: bar
{{ end -}}
{{- if .Release.IsUpgrade -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "failurecauser"
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: never
          image: "busybox:latest"
          args:
            - "/bin/sh"
            - "-c"
            - "false"
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 0
{{ end -}}
```

Upon installation, the ConfigMap is created as expected. Upon upgrade, the ConfigMap would _eventually_ be removed, but as the pre-upgrade hook fails, Helm never gets a chance to remove the ConfigMap.

When it comes time to rollback (either via `helm rollback` or via `--atomic` used during the failing `helm upgrade`) Helm walks the list of manifests in the target (the initial deployment which contained only the ConfigMap), finds that it exists in the cluster *and then checks its state in the last deployed version* where it is absent and fails with:

```
rollback.go:65: 2024-11-12 10:01:59.033172463 +0100 CET m=+0.253517049 [debug] preparing rollback of test
rollback.go:131: 2024-11-12 10:01:59.180766777 +0100 CET m=+0.401111391 [debug] rolling back test (current: v2, target: v1)
rollback.go:72: 2024-11-12 10:01:59.244344963 +0100 CET m=+0.464689544 [debug] creating rolled back release for test
rollback.go:78: 2024-11-12 10:01:59.391610987 +0100 CET m=+0.611955586 [debug] performing rollback of test
client.go:393: 2024-11-12 10:01:59.538573362 +0100 CET m=+0.758917920 [debug] checking 1 resources for changes
rollback.go:195: 2024-11-12 10:01:59.60209464 +0100 CET m=+0.822439231 [debug] warning: Rollback "test" failed: no ConfigMap with the name "cfg" found
Error: no ConfigMap with the name "cfg" found
helm.go:86: 2024-11-12 10:01:59.753177208 +0100 CET m=+0.973521792 [debug] no ConfigMap with the name "cfg" found
```

The error message is somewhat misleading as it suggests that the ConfigMap is not found _on the cluster_, where it is clearly there. Where it is not found is the Secret that represents that last deployment where it really was absent (or would have been, had Helm ever made it that far). The log message is produced here: 

https://github.com/helm/helm/blob/5a5449dc42be07001fd5771d56429132984ab3ab/pkg/kube/client.go#L418-L422

Has the manifest been successfully removed in the preceding upgrade, this wouldn't fail due to 

https://github.com/helm/helm/blob/5a5449dc42be07001fd5771d56429132984ab3ab/pkg/kube/client.go#L399-L411

Line 401 shows care given to a Manifest being absent on the cluster, but no similar logic for a Manifest being absent from the release deemed to be the original. Of course, if `helm upgrade` is used instead of `helm rollback`, this specific problem doesn't occur, but only because the original release is determined to be the last _successful_ one instead of the live one. Had the failure occurred at post-upgrade instead and we were rolling back more than one revision, the same issue would present itself.

Just like how Helm does not fail on a Manifest having been deleted on the cluster and instead quickly recreates it, if a Manifest is not found in the original release but does find it on the cluster, I think Helm should handle that gracefully.

Otherwise, `--atomic` and `helm rollback` are broken in the presence of removed Manifests and potentially failing pre-upgrade hooks.

Possibly duplicates #12388, but I think this way to reproduce the issue is clearer.

### PR DESCRIPTION
**Pull request by fmuyassarov**
**What this PR does / why we need it**:
Fix rollback for missing resources.
Fixes: https://github.com/helm/helm/issues/13437 

How to test:

Build the helm binary
```
$ make build
$ helm version
  version.BuildInfo{Version:"v4.0+unreleased", GitCommit:"f82e2b3c50d346948ce42e6a4f1348dee29aba31", GitTreeState:"dirty", GoVersion:"go1.24.7", KubeClientVersion:"v1.34"}
```
A quick test can be performed by creating a following charts directory:
```sh
├── v1
│   ├── Chart.yaml
│   ├── templates
│   │   ├── configmap.yaml
│   │   └── failure-hook.yaml
│   └── values.yaml
└── v2
    ├── Chart.yaml
    ├── templates
    │   └── failure-hook.yaml
    └── values.yaml
```

```YAML
{{- if .Release.IsInstall }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg
data:
  foo: bar
{{- end }}
```
```YAML
{{- if .Release.IsUpgrade }}
apiVersion: batch/v1
kind: Job
metadata:
  name: failurecauser
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: never
          image: busybox:latest
          args: ["/bin/sh", "-c", "false"]
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 0
{{- end }}
```

```shell
helm install test ./v1
NAME: test
LAST DEPLOYED: Wed Oct 22 12:34:41 2025
NAMESPACE: default
STATUS: deployed
REVISION: 1
DESCRIPTION: Install complete
TEST SUITE: None
```
```sh
helm upgrade test ./v2
^CRelease test has been cancelled.
level=WARN msg="upgrade failed" name=test error="context canceled"
Error: UPGRADE FAILED: context canceled
```
```sh
helm list -A
NAME	NAMESPACE	REVISION	UPDATED                              	STATUS	CHART              	APP VERSION
test	default  	2       	2025-10-22 12:35:55.186407 +0300 EEST	failed	helm-bug-demo-2.0.0	1.0
```
```sh
helm rollback test 1
Rollback was a success! Happy Helming!
```
```sh
helm list -A
NAME	NAMESPACE	REVISION	UPDATED                              	STATUS  	CHART              	APP VERSION
test	default  	3       	2025-10-22 12:37:00.757802 +0300 EEST	deployed	helm-bug-demo-1.0.0	1.0
```
**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [ ] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by kashifest — APPROVED** [review]
Lgtm. It would be nice to have people with review rights to review this long standing fix

File: pkg/kube/client.go [hunk 1]
```diff
@@ -532,7 +532,32 @@ func (c *Client) update(originals, targets ResourceList, updateApplyFunc UpdateA
 		original := originals.Get(target)
 		if original == nil {
 			kind := target.Mapping.GroupVersionKind.Kind
-			return fmt.Errorf("original object %s with the name %q not found", kind, target.Name)
+
+			slog.Debug("resource exists on cluster but not in original release, using cluster state as baseline",
```
Comment (benoittgt) [inline pkg/kube/client.go]: Giving the new behavior we should maybe warn about this instead of only printing on debug.

**Comment by benoittgt** [comment]
Hello @fmuyassarov 

I’ve tested the patch and it works as expected. I’ve quickly tried to find what could go wrong with this new handling, and so far the patch looks correct.
Maybe we’re missing a test that reflects what you’re fixing?

<details>
 <summary>Scenario for my test</summary>

```sh
❯ md charts
❯ cd charts
❯ helm version
version.BuildInfo{Version:"v3.19.0", GitCommit:"3d8990f0836691f0229297773f3524598f46bda6", GitTreeState:"clean", GoVersion:"go1.24.7"}

❯ helm create v1
❯ vi v1/templates/configmap.yaml
❯ vi v1/templates/failure-hook.yaml
❯ rm -f v1/templates/deployment.yaml v1/templates/service.yaml v1/templates/ingress.yaml v1/templates/hpa.yaml v1/templates/serviceaccount.yaml
❯ cp -r v1 v2
❯ rm -f v2/templates/configmap.yaml
❯ tree
.
├── v1
│   ├── Chart.yaml
│   ├── charts
│   ├── templates
│   │   ├── _helpers.tpl
│   │   ├── configmap.yaml
│   │   ├── failure-hook.yaml
│   │   ├── httproute.yaml
│   │   ├── NOTES.txt
│   │   └── tests
│   │       └── test-connection.yaml
│   └── values.yaml
└── v2
    ├── Chart.yaml
    ├── charts
    ├── templates
    │   ├── _helpers.tpl
    │   ├── failure-hook.yaml
    │   ├── httproute.yaml
    │   ├── NOTES.txt
    │   └── tests
    │       └── test-connection.yaml
    └── values.yaml

9 directories, 15 files
❯ helm install test ./v1
NAME: test
LAST DEPLOYED: Fri Oct 31 17:55:50 2025
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=v1,app.kubernetes.io/instance=test" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT

❯ helm upgrade test ./v2
Error: UPGRADE FAILED: pre-upgrade hooks failed: 1 error occurred:
        * job failurecauser failed: BackoffLimitExceeded


❯ helm rollback test 1
Error: no ConfigMap with the name "cfg" found

❯ alias helm=/Users/benoit.tigeot/projects/helm/bin/helm
❯ helm version
version.BuildInfo{Version:"v4.0+unreleased", GitCommit:"6c5fe2d91fd51ab2c528ca69eb48bec2d7cad8fe", GitTreeState:"clean", GoVersion:"go1.24.0", KubeClientVersion:"v1.34"}
❯ helm rollback test 1
Rollback was a success! Happy Helming! 😏

❯ helm history test
REVISION UPDATED                         STATUS          CHART           APP VERSION     DESCRIPTION
1               Fri Oct 31 17:55:50 2025        superseded      v1-0.1.0        1.16.0          Install complete
2               Fri Oct 31 17:55:56 2025        superseded      v1-0.1.0        1.16.0          Upgrade "test" failed: pre-upgrade hooks failed: 1 error occurr...
3               Fri Oct 31 17:56:11 2025        failed          v1-0.1.0        1.16.0          Rollback "test" failed: no ConfigMap with the name "cfg" found
4               Fri Oct 31 17:57:41 2025        deployed        v1-0.1.0        1.16.0          Rollback to 1
```

</details>

File: pkg/kube/client_test.go [hunk 2]
```diff
@@ -412,7 +412,7 @@ func TestUpdate(t *testing.T) {
 				"/namespaces/default/pods/forbidden:GET",
 				"/namespaces/default/pods/forbidden:DELETE",
 			),
-			ExpectedError: "failed to delete resource forbidden:",
+			ExpectedError: "failed to delete resource namespace=default, name=forbidden, kind=Pod:",
 		},
 	}
```
Comment (benoittgt) [inline pkg/kube/client_test.go:435]: I think we are missing an extra-test that should fail without your patch.

Comment (fmuyassarov) [reply pkg/kube/client_test.go:435]: Indeed. Should be covered now.

File: pkg/kube/client.go (hunk 1 above)
Comment (fmuyassarov) [reply pkg/kube/client.go]: Makes sense. Updated it.

**Comment by fmuyassarov** [comment]
> Hello @fmuyassarov
> 
> I’ve tested the patch and it works as expected. I’ve quickly tried to find what could go wrong with this new handling, and so far the patch looks correct. Maybe we’re missing a test that reflects what you’re fixing?
> Scenario for my test

Thanks for the review @benoittgt . 
I've addressed your comments. PTAL.

**Comment by benoittgt** [comment]
@fmuyassarov it seems the push force didn't work. I don't see your [changes](https://github.com/helm/helm/compare/6c5fe2d91fd51ab2c528ca69eb48bec2d7cad8fe..cee7c0e30d0b42eb57428b3e05e39fd27549ec15).

**Comment by fmuyassarov** [comment]
> @fmuyassarov it seems the push force didn't work. I don't see your [changes](https://github.com/helm/helm/compare/6c5fe2d91fd51ab2c528ca69eb48bec2d7cad8fe..cee7c0e30d0b42eb57428b3e05e39fd27549ec15).

Sorry @benoittgt , somehow missed those changes. Should be fixed now.

**Comment by benoittgt** [comment]
Thanks @fmuyassarov. I think the changes are correct. LGTM.

But now we need another approvals. @gjenkins8 @robertsirc maybe ?

**Review by TerryHowe — DISMISSED** [review]
/lgtm

**Comment by TerryHowe** [comment]
Tests pass for me.

**Comment by fmuyassarov** [comment]
ping @mattfarina

**Comment by fmuyassarov** [comment]
Hi @mattfarina, do you have updates on this?

**Review by banjoh — APPROVED** [review]

**Review by banjoh — DISMISSED** [review]

File: pkg/kube/client.go [hunk 3]
```diff
@@ -531,14 +525,39 @@ func (c *Client) update(originals, targets ResourceList, updateApplyFunc UpdateA
...
 		if original == nil {
 			kind := target.Mapping.GroupVersionKind.Kind
-			return fmt.Errorf("original object %s with the name %q not found", kind, target.Name)
+
+			slog.Warn("resource exists on cluster but not in original release, using cluster state as baseline",
+				"namespace", target.Namespace, "name", target.Name, "kind", kind)
+
+			currentObj, err := helper.Get(target.Namespace, target.Name)
+			if err != nil {
+				return fmt.Errorf("failed to get current resource state: %w", err)
```
Comment (TerryHowe) [inline pkg/kube/client.go]: I think this error doesn't give context for the problem. Maybe the original error here? `return fmt.Errorf("original object %s with the name %q not found", kind, target.Name)`

Comment (fmuyassarov) [reply pkg/kube/client.go]: Hi @TerryHowe, I can fix that. I just want to confirm whether a force push would remove the existing approval. If it’s not a big deal, I can submit a follow-up change; otherwise, I’ll fix it right away.

Comment (TerryHowe) [reply pkg/kube/client.go]: Go for the change. I think this is close. It'd be nice to have @gjenkins8 take on this.

Comment (fmuyassarov) [reply pkg/kube/client.go]: Fixed.

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Comment by fmuyassarov** [comment]
@TerryHowe are we missing something else to merge this?

**Comment by TerryHowe** [comment]
> @TerryHowe are we missing something else to merge this?

I was hoping someone else would look at it. There were changes since @banjoh approval.

**Review by banjoh — APPROVED** [review]

**Comment by scottrigby** [comment]
Based on being able to reproduce this issue and that this PR fixes it, I believe this PR is a bug fix not a new feature. See https://github.com/helm/helm/issues/13437#issuecomment-3751274529

**Comment by abdullah-arif-swe** [comment]
Is this commit also supposed to be in version 4.11? I don't see the commit there: https://github.com/helm/helm/commits/v4.1.1/pkg/kube

image
