### PR TITLE
fix(lint): prevent segmentation violation on only comment yaml in multidoc

### LINKED ISSUE #31544: SIGSEGV when running `helm lint` on traefik chart
### What happened?

Panic when linting traefik helm chart with Helm v4.0.0 but when using Helm v3, it works as expected.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1fda40f]

goroutine 1 [running]:
helm.sh/helm/v4/pkg/chart/v2/lint/rules.validateCrdAPIVersion(0xc000b338f0?)
        helm.sh/helm/v4/pkg/chart/v2/lint/rules/crds.go:102 +0xf
helm.sh/helm/v4/pkg/chart/v2/lint/rules.Crds(0xc000b32270)
        helm.sh/helm/v4/pkg/chart/v2/lint/rules/crds.go:83 +0x765
helm.sh/helm/v4/pkg/chart/v2/lint.RunAll({0x7ffe337a3356?, 0xa?}, 0xc000b321b0, {0xc000b2cbd0, 0x7}, {0xc0002d9888, 0x2, 0x0?})
        helm.sh/helm/v4/pkg/chart/v2/lint/lint.go:68 +0x1e5
helm.sh/helm/v4/pkg/action.lintChart({0x7ffe337a3356, 0x1}, 0xc000b321b0, {0xc000b2cbd0, 0x7}, 0x0, 0x0)
        helm.sh/helm/v4/pkg/action/lint.go:129 +0x776
helm.sh/helm/v4/pkg/action.(*Lint).Run(0xc0003e7710, {0xc0002d9ba0, 0x1, 0x2?}, 0xc000b321b0)
        helm.sh/helm/v4/pkg/action/lint.go:63 +0xe5
helm.sh/helm/v4/pkg/cmd.newLintCmd.func1(0xc00011b300?, {0xc0009f4300?, 0x4?, 0x2763033?})
        helm.sh/helm/v4/pkg/cmd/lint.go:93 +0x2bf
github.com/spf13/cobra.(*Command).execute(0xc000978c08, {0xc0009f42d0, 0x1, 0x1})
        github.com/spf13/cobra@v1.10.1/command.go:1015 +0xb02
github.com/spf13/cobra.(*Command).ExecuteC(0xc000432308)
        github.com/spf13/cobra@v1.10.1/command.go:1148 +0x465
github.com/spf13/cobra.(*Command).Execute(0x2caa700?)
        github.com/spf13/cobra@v1.10.1/command.go:1071 +0x13
main.main()
        helm.sh/helm/v4/cmd/helm/helm.go:43 +0x159
```

Ref: https://github.com/traefik/traefik-helm-chart/issues/1568

### What did you expect to happen?

A valid result when running helm lint for the traefik chart like
```
helm lint .
==> Linting .

1 chart(s) linted, 0 chart(s) failed
```

### How can we reproduce it (as minimally and precisely as possible)?

1. git clone https://github.com/traefik/traefik-helm-chart.git
2. cd traefik-helm-chart/traefik
3. helm lint .

### Helm version

```console
version.BuildInfo{Version:"v4.0.0", GitCommit:"99cd1964357c793351be481d55abbe21c6b2f4ec", GitTreeState:"clean", GoVersion:"go1.25.3", KubeClientVersion:"v1.34"}
```

### Kubernetes version

```console
Client Version: v1.34.2
Kustomize Version: v5.7.1
```

### PR DESCRIPTION
**Pull request by benoittgt**
Fixes: https://github.com/helm/helm/issues/31544, #31571, https://github.com/helm/helm/issues/31588

**What this PR does / why we need it**:

During testing with the [chart provided](https://github.com/traefik/traefik-helm-chart/traefik), I added some logs. Yaml was `nil` and error `too`.

It is because of this https://github.com/traefik/traefik-helm-chart/blob/5d03b0ccf87ea2f64d9473ad365671f1972f3af2/traefik/crds/gateway-standard-install.yaml#L1-L18

We should continue if the yaml parsing is nil.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains user facing changes (the `docs needed` label should be applied if so)
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by TerryHowe — COMMENTED** [review]
Tests pass for me, I think that is a flake.

**Comment by benoittgt** [comment]
Let's rerun

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Review by banjoh — APPROVED** [review]
LGTM

File: internal/chart/v3/lint/rules/crds.go [hunk 1]
```diff
@@ -80,8 +80,10 @@ func Crds(linter *support.Linter) {
 				return
 			}
 
-			linter.RunLinterRule(support.ErrorSev, fpath, validateCrdAPIVersion(yamlStruct))
-			linter.RunLinterRule(support.ErrorSev, fpath, validateCrdKind(yamlStruct))
+			if yamlStruct != nil {
```
Comment (benoittgt) [inline internal/chart/v3/lint/rules/crds.go:83]: We do similar check in https://github.com/helm/helm/blob/00e12b847758203e791dc95163361b68059e5927/pkg/chart/v2/lint/rules/template.go#L192

**Review by gjenkins8 — APPROVED** [review]

**Comment by benoittgt** [comment]
@gjenkins8 I tested with dev-v3 and the issue is not present:

```sh
❯ make build && bin/helm lint traefik-helm-chart/traefik --debug
make: Nothing to be done for `build'.
==> Linting traefik-helm-chart/traefik

1 chart(s) linted, 0 chart(s) failed
❯ bin/helm version
version.BuildInfo{Version:"v3.19+unreleased", GitCommit:"795460535b3264a0ff5193c5e007c401b607927f", GitTreeState:"dirty", GoVersion:"go1.24.0"}
```

**Review by mattfarina — APPROVED** [review]
