### PR TITLE
Extra hint in the error when failing to open a chart file.

### LINKED ISSUE #5296: helm template: Error: gzip: invalid header
Output of `helm version`:
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.11-gke.1", GitCommit:"5c4fddf874319c9825581cc9ab1d0f0cf51e1dc9", GitTreeState:"clean", BuildDate:"2018-11-30T16:18:58Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

```
% helm template values.yaml                                        
Error: gzip: invalid header
```

Adding `--debug` does not add any additional output.

This is a user error on my part, but I am left wishing greatly for improved feedback from the tool. The error message is *super* confusing for me as an end user (even though I understand why it is).

Maybe instead of `Error: gzip: invalid header` we could say something like "values.yaml does not appear to be a valid chart"

Thoughts?

### PR DESCRIPTION
**Pull request by jordansissel**
Fixes #5296

**What this PR does / why we need it**: Adds additional hinting for a errors when invalid files are given as a chart parameter.

**Special notes for your reviewer**:

**If applicable**:
- [x] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

File: pkg/chartutil/load.go [hunk 1]
```diff
@@ -255,7 +255,13 @@ func LoadFile(name string) (*chart.Chart, error) {
 	}
 	defer raw.Close()
 
-	return LoadArchive(raw)
+	c, err := LoadArchive(raw)
+	if err != nil {
+		if err.Error() == "gzip: invalid header" {
```
Comment (bacongobbler) [inline pkg/chartutil/load.go]: I'm not sure we can safely assume that the error `gzip: invalid header` means we are reading from an uncompressed file. We could also be reading a corrupt gzipped archive.

Is there some way you could try to improve the error checking either here or in `LoadArchive`?

**Comment by jordansissel** [comment]
There’s a lot of errors I can imagine, but most of them are unpredictable
strings (no checked exceptions like java has, for example), so it’s unclear
how to proceed.

For the user experience I am trying to improve: when a user mistakenly uses
a values file in a command line parameter where a chart was expected, the
current release says “gzip: invalid header” with no hints as to why. Even
strace leaves me without answers — I asked myself “why is it reading my
values file as a gzip?” and got nowhere with that question.

I think other error conditions are out of scope.

**Comment by bacongobbler** [comment]
> no checked exceptions like java has, for example

You can check `if err == gzip.ErrHeader` to achieve the same thing in this case.

What about using `http.DetectContentType` to sniff the content type?

```
// Only the first 512 bytes are used to sniff the content type.
buffer := make([]byte, 512)
n, err := raw.Read(buffer)
if err != nil {
	return err
}

// reset the read buffer for LoadArchive
raw.Seek(0, 0)

// TODO: Will need to check if application/gzip is actually the right content type returned by DetectContentType
if contentType := http.DetectContentType(buffer[:n]); contentType != "application/gzip" {
    return nil, fmt.Errorf("file '%s' does not appear to be a gzipped archive", name, err)
}

c, err := LoadArchive(raw)
...
```

**Comment by jordansissel** [comment]
+1 your proposals. I haven't made time to update the PR based on the feedback yet.

**Comment by bacongobbler** [comment]
ping

**Comment by jordansissel** [comment]
I have not made time to improve this PR based on feedback.

**Comment by jordansissel** [comment]
I've picked up working on this again. Next step is to try and do the content type detection as you proposed to see what kind of extra hints we can offer.

**Comment by jordansissel** [comment]
I still have some testing to do, but here's the current state (note, I have `{redacted}` some text to make it quicker to read:

```
# Passing a yaml file where a chart was expected:
% ~/projects/helm/bin/helm template values.yml .         
Error: file '{redacted}/values.yml' seems to be a YAML file, but I expected a gzipped archive

# Passing something neither yaml nor a chart:
% ~/projects/helm/bin/helm template README.md .
Error: file '{redacted}/README.md' does not appear to be a gzipped archive; got 'text/plain; charset
=utf-8'
```

This isn't ready to review yet as I'd like to explore writing tests for this.

File: pkg/chartutil/load.go [hunk 2]
```diff
@@ -255,7 +256,46 @@ func LoadFile(name string) (*chart.Chart, error) {
...
+	defer raw.Seek(0, 0) // reset read offset to allow archive loading to proceed.
+
+	// Check the file format to give us a chance to provide the user with more actionable feedback.
+	buffer := make([]byte, 512)
+	_, err := raw.Read(buffer)
+	if err != nil && err != io.EOF {
+		return fmt.Errorf("file '%s' cannot be read: %s", name, err)
+	}
+	if contentType := http.DetectContentType(buffer); contentType != "application/x-gzip" {
+		// TODO: Is there a way to reliably test if a file content is YAML? ghodss/yaml accepts a wide
```
Comment (jordansissel) [inline pkg/chartutil/load.go]: Note for posterity: I originally tried using `ghodss/yaml`'s Unmarshal, but this accepts nearly every file I tried without error (Makefile, ~/.zshrc, etc), so I gave up and used file suffix checks instead.

**Comment by jordansissel** [comment]
Alrighty, CI checks are passing and this code is ready for review. 

@bacongobbler lemme know if you need anything else on this PR.

**Comment by jordansissel** [comment]
Anything I can help with to move this forward?

**Comment by bridgetkromhout** [comment]
Hi, @jordansissel! Fancy meeting you here! 😃Thank you for putting this time in; this is really helpful. This looks good according to @bacongobbler - we will merge it after we test manually and open an issue to add some unit tests to cover it. Would you like that issue? And would you want to port it to the https://github.com/helm/helm/tree/dev-v3 branch, for Helm 3, which is imminent?

**Comment by jordansissel** [comment]
Hello friend!

I’m open to adding tests. I haven’t touched helm 3 yet, so this is as good
a reason as any to start wandering in they direction — so, yes on porting
you helm 3 ;)

I’m on PTO this week, but will look into this sometime in October.

For porting, would you prefer I open a separate PR, or wait until v3 lands
in master?

**Review by bacongobbler — APPROVED** [review]
Works as advertised! LGTM

Tested using the following:

```
><> ./bin/helm fetch stable/wordpress
><> ./bin/helm fetch stable/wordpress --untar
><> touch hello.txt
><> touch values.yaml
><> tar czf hello.tgz hello.txt 
><> ./bin/helm template wordpress-7.0.1.tgz > /dev/null
><> echo $?
0
><> ./bin/helm template ./wordpress/ > /dev/null
><> echo $?
0
><> ./bin/helm template hello.txt 
Error: file '/home/bacongobbler/code/go/src/k8s.io/helm/hello.txt' does not appear to be a gzipped archive; got 'application/octet-stream'
><> ./bin/helm template values.yaml 
Error: file '/home/bacongobbler/code/go/src/k8s.io/helm/values.yaml' seems to be a YAML file, but I expected a gzipped archive
><> ./bin/helm template hello.tgz 
Error: chart illegally contains empty path
```

**Comment by bacongobbler** [comment]
Feel free to add unit tests in a follow-up PR (or, if you plan to port it over, in the PR for Helm 3). Thanks @jordansissel for your patience!

**Comment by hickeyma** [comment]
Port created: #6613
