### PR TITLE
fix(dependencyBuild): prevent race condition in concurrent helm dependency

### LINKED ISSUE #13110: Concurrent `helm dependency build` fail due to race condition
We're building and templating a lot of Helm charts in parallel, when some of them share a subchart using symlinks it's possible the build fails due to a race condition: Both build try to download to the same location, one of them finishes first and deletes the file and then the second build crashes as the file is missing:

```
Error: Error rendering ops/k8s/ingress-nginx-public/Chart.yaml: Error running 'helm dependency build --repository-config /tmp/tmpnb8ufin2.yaml ops/k8s/ingress-nginx-public/charts/ingress-nginx':
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "f6d59f60" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading ingress-nginx from repo https://kubernetes.github.io/ingress-nginx
Save error occurred:  could not download https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-4.10.1/ingress-nginx-4.10.1.tgz: open ops/k8s/ingress-nginx-public/charts/ingress-nginx/tmpcharts/ingress-nginx-4.10.1.tgz3661314739: no such file or directory
Error: could not download https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-4.10.1/ingress-nginx-4.10.1.tgz: open ops/k8s/ingress-nginx-public/charts/ingress-nginx/tmpcharts/ingress-nginx-4.10.1.tgz3661314739: no such file or directory
```

Output of `helm version`:
>version.BuildInfo{Version:"v3.14.3", GitCommit:"f03cc04caaa8f6d7c3e67cf918929150cf6f3f12", GitTreeState:"clean", GoVersion:"go1.22.1"}

### PR DESCRIPTION
**Pull request by idsulik**
closes #13110

**What this PR does / why we need it**:
it fixes this issue by adding a suffix to the `tmpcharts` directory so each instance can have its own directory
> building and templating a lot of Helm charts in parallel, when some of them share a subchart using symlinks it's possible the build fails due to a race condition

### CODE REVIEW

File: pkg/downloader/manager.go [hunk 1]
```diff
@@ -246,7 +246,7 @@ func (m *Manager) downloadAll(deps []*chart.Dependency) error {
 	}
 
 	destPath := filepath.Join(m.ChartPath, "charts")
-	tmpPath := filepath.Join(m.ChartPath, "tmpcharts")
+	tmpPath := filepath.Join(m.ChartPath, fmt.Sprintf("tmpcharts-%d", os.Getpid()))
```
Comment (mattfarina) [inline pkg/downloader/manager.go:249]: While this generally works, there are some tests to make sure we don't leave the _tmpcharts_ directory behind. The tests need to be updated to ensure the directory under the new name isn't left behind. You can find these by searching for _tmpcharts_ in the codebase. One example is in the test `TestDependencyUpdateCmd_DoNotDeleteOldChartsOnError`.

Can you please make sure the tests are updated for this change.

**Review by mattfarina — CHANGES_REQUESTED** [review]

File: pkg/downloader/manager.go (hunk 1 above)
Comment (idsulik) [reply pkg/downloader/manager.go:249]: Thanks for pointing that out, fixed it

**Review by mattfarina — APPROVED** [review]
I tested that the PID across both is consistent, even with `-race` and that this fails when things aren't handled properly. This looks good.

**Comment by mattfarina** [comment]
Since this is XS in size, a single maintainer approval is all that's required to merge.

**Comment by hanikesn** [comment]
Thank you @idsulik!
