### PR TITLE
Tolerate temporary errors from etcdserver

### LINKED ISSUE #7637: helm upgrade --atomic etcdserver: leader changed
Output of `helm version`:
```
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:34:02Z", GoVersion:"go1.13.
6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:24:46Z", GoVersion:"go1.13.
6", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): `Baremetal`

Problem:
```
uninstall.go:129: [debug] purge requested for xxx
Error: release xxx failed, and has been uninstalled due to atomic being set: rpc error: code = Unavailable desc = etcdserver: leader changed
helm.go:75: [debug] rpc error: code = Unavailable desc = etcdserver: leader changed
release xxx failed, and has been uninstalled due to atomic being set
```

I think it started somewhere between helm 3.0.2 and 3.1.0

### LINKED ISSUE #9502: helm upgrade --wait command failded because of `etcdserver: leader changed`
I used `--wait` option during helm upgrade but found while waiting for the deployment ready, once a failure return from k8s api happened, helm will exit immidiately. 

Since a chart may contain various of resources, it is not so good to exit immidiately once a failure API calling happened while waiting for them to be ready

I think there should be some retrys while calling APIs since network APIs are designed to fail. 

logs attached:

wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: core/cdf-apiserver. 0 out of 1 expected pods are ready
Error: etcdserver: leader changed
helm.go:94: [debug] etcdserver: leader changed

Output of `helm version`:
v3.3.0

Output of `kubectl version`:
v1.20.4

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
kubeadm

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

There are cases when the etcdserver is temporarily unavailable and the
errors that we get back from kube-apiserver reflect that error. It looks
like we bail out immediately when these errors happen currently. We
should retry until timeout is reached when this sort of errors happen.

Fixes #9502 
Fixes #7637

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

**Special notes for your reviewer**:

With this patch, temporary errors like the etcdserver leader changes are not treated as terminal. We continue to retry until the specified timeout.

Note that there are things that can be done on the k8s side, discussion is going on there as well:
https://github.com/kubernetes/kubernetes/issues/112152

**If applicable**:
- This PR does not change any functionality, so no updates to the documentation
- Currently there aren't any unit tests in this package, but i added one for just the new method `isServiceUnavailable`
- No changes to functionality, so no incompatibilities

### CODE REVIEW

**Comment by dims** [comment]
weird failure in the CI job

```
#!/bin/bash -eo pipefail
make test-style
GO111MODULE=on golangci-lint run
WARN [linters context] structcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649. 
cmd/helm/helm.go:37:2: "helm.sh/helm/v3/pkg/storage/driver" imported but not used (typecheck)
	"helm.sh/helm/v3/pkg/storage/driver"
	^
pkg/action/uninstall_test.go:25:2: "helm.sh/helm/v3/pkg/kube/fake" imported but not used as kubefake (typecheck)
	kubefake "helm.sh/helm/v3/pkg/kube/fake"
	^
pkg/action/upgrade_test.go:30:2: "helm.sh/helm/v3/pkg/kube/fake" imported but not used as kubefake (typecheck)
	kubefake "helm.sh/helm/v3/pkg/kube/fake"
	^
make: *** [Makefile:116: test-style] Error 1

Exited with code exit status 2
CircleCI received exit code 2
```

**Comment by dims** [comment]
@hickeyma this is ready now!

**Comment by mattfarina** [comment]
@dims thanks for looking into the issues here.

I the Kubernetes API supposed to be a leaky abstraction? Are clients expected to work with etcd? I'm asking about intent and mid-term intent. I'm wondering whether this code is something we will need to maintain long term or if this is a short term situation.

**Comment by dims** [comment]
@mattfarina we'll need a KEP in upstream, i've requested some folks who were pushing for this earlier to do more in 1.27 cycle (not 1.26), So until that KEP is discussed/reviewed/approved we will need this.

we'll also need this until versions of kubernetes supported by helm has the old style leaky abstraction.

**Review by technosophos — APPROVED** [review]
This seems to be the appropriate stop-gap for this error.

File: pkg/kube/wait.go [hunk 1]
```diff
@@ -54,6 +72,9 @@ func (w *waiter) waitForResources(created ResourceList) error {
 		for _, v := range created {
 			ready, err := w.c.IsReady(ctx, v)
 			if !ready || err != nil {
+				if isServiceUnavailable(err) {
```
Comment (hakuna-matatah) [inline pkg/kube/wait.go:75]: There might be a situation where etcd doesn't recover forever or for  `x` amount of time (which may or may not be not tolerable for different customers using helm) and we end up waiting on this loop forever or `x` amount of time  because of this logic. What do you think ?
Shall we limit the number of retry attempts based on time factor and give up after that ?

Comment (hakuna-matatah) [reply pkg/kube/wait.go:75]: Never mind - I see that timeout is already set above - https://github.com/helm/helm/blob/ebc79fa807f29b984e090f0071b640f7347937cf/pkg/kube/wait.go#L68-L69

Comment (dims) [reply pkg/kube/wait.go:75]: yep.

**Review by hickeyma — APPROVED** [review]
Thanks @dims for tracking these issues down and providing this interim solution. It will be helpful to users.

**Comment by dims** [comment]
thanks @hickeyma !

**Comment by cenkalti** [comment]
Hey @technosophos @hickeyma. Unfortunately, this fix does not solve the issue. Can you take a look at my new fix? https://github.com/helm/helm/pull/11426

**Comment by sruthiwander** [comment]
@dims Can this be backported to 3.9 please?

**Comment by dims** [comment]
@sruthiwander not this one! it was reverted, you will need https://github.com/helm/helm/pull/11426
