### PR TITLE
fix(tiller): allow 3rd party APIs

### LINKED ISSUE #1468: Helm choking with third party resources.
Hello! Super excited by this work, and am experimenting with it both in a personal and a professional capacity. However, Helm doesn't seem to be able to deploy third party resources, though `$ kubectl` can. Steps to reproduce are below:

```
$ # This is the only thing in the templates directory
$ cat templates/40-howden-io.certificate.yml 

---
apiVersion: "stable.k8s.psg.io/v1"
kind: "Certificate"
metadata:
  name: "howden-io"
  namespace: "howden-io"
spec:
  domain: "howden.io"
  email: "[REMOVED]"
  provider: "route53"
  secretName: "tls-howden-io"

# See
$ ls templates/
40-howden-io.certificate.yml  NOTES.txt

# Helm doesn't seem to like this third party resource
$ helm install . --name=howden-io
Error: release howden-io failed: unable to decode "": no kind "Certificate" is registered for version "stable.k8s.psg.io/v1"

# kubectl handles the certificate OK
$ kubectl apply -f templates/40-howden-io.certificate.yml 
certificate "howden-io" created

# Helm also doesn't like the deletion of the certificate
$ helm delete --purge howden-io
Error: deletion error count 2: no objects visited; unable to decode "": no kind "Certificate" is registered for version "stable.k8s.psg.io/v1"

```

Note: Mildly edited for content, clarity. Versions and things:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:42:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
Client: &version.Version{SemVer:"v2.0.0-beta.1", GitCommit:"05c04bccae63c6392ec0cb0e27790650167279f0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.0.0-beta.1", GitCommit:"05c04bccae63c6392ec0cb0e27790650167279f0", GitTreeState:"clean"}
```

The third party resource in question

```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  description: A specification of a Let's Encrypt Certificate to manage.
  kind: ThirdPartyResource
  metadata:
    creationTimestamp: [REMOVED]
    name: certificate.stable.k8s.psg.io
    resourceVersion: " [REMOVED]"
    selfLink: /apis/extensions/v1beta1/thirdpartyresources/certificate.stable.k8s.psg.io
    uid: [REMOVED]
  versions:
  - name: v1
kind: List
metadata: {}
```

### LINKED ISSUE #1472: bug: Tests fail if tmp dir is on different block device than source dir
It looks like there are symlinks that are created between source testdata files and a temp dir. Symbolic links cannot be created across block devices, so if `tmp/` is on a different block device than `$GOPATH/src/k8s.io/helm`, the tests will fail like this:

```
--- FAIL: TestRepoIndexCmd (0.00s)
	repo_index_test.go:39: link testdata/testcharts/compressedchart-0.1.0.tgz /tmp/helm-872511156/compressedchart-0.1.0.tgz: invalid cross-device link
```

### PR DESCRIPTION
**Pull request by technosophos**
This feature has been disabled in the past because simply enabling the
feature causes the Kubernetes library to make requests to a server.
Thus, running any tests that use the 'pkg/kube' library has required
running a kube API server.

This patch makes it possible to selectively activate 3rdParty API
support, and then disables that support during testing.

Future versions of the Kubernetes library appear to make it easier to
configure and mock this behavior, so this is most likely a stop-gap
measure. (Famous last words.)

Closes #1468 

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/helm/1473)

### CODE REVIEW

**Comment by technosophos** [comment]
I don't know if there is the possibility that this will break backwards compatibility. My manual testing did not turn up anything strange on Kubernetes 1.4.

File: pkg/kube/client.go [hunk 1]
```diff
@@ -275,10 +275,16 @@ func (c *Client) WatchUntilReady(namespace string, reader io.Reader) error {
...
 }
 
-const includeThirdPartyAPIs = false
+// IncludeThirdPartyAPIs indicates whether to load "dynamic" APIs.
+//
+// This requires additional calls to the Kubernetes API server, and these calls
+// are not supported by all versions. Additionally, during testing, initializing
+// a client will still attempt to contact a live server. In these situations,
+// this flag may need to be disabled.
+var IncludeThirdPartyAPIs = true
```
Comment (adamreese) [inline pkg/kube/client.go]: What do you think about adding this as a field on `Client`?  That would remove the global var and the hacky init() call.

**Comment by technosophos** [comment]
Good idea, @adamreese. I rewrote it that way.
