### PR TITLE
fix: write index.yaml file atomically

### LINKED ISSUE #7988: `index.yaml` are not written atomically
`index.yaml` files, as generated by `helm repo index`, are not written atomically. As a result files can be half-written when helm or another client reads them.

This is an example of a custom YAML scanner breaking because of a half-written file:
```
/<redacted>/path/to/scanner.py", line 319, in scan_index
"could not find expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
in "<unicode string>", line 3497, column 5:
appVersi
^
could not find expected ':'
in "<unicode string>", line 3497, column 13:
appVersi
^
```

### PR DESCRIPTION
**Pull request by rabadin**
This refactors the already-existing `AtomicWriteFile` utility
to a central location and uses it to write index files
atomically.
This is done to avoid having half-written index files break
client requests.

Drive-bys:
  - Add test for AtomicWriteFile.
  - Add test IndexFile.WriteFile.

Closes #7988

### CODE REVIEW

**Comment by technosophos** [comment]
Is there an issue or existing proposal attached to this?

**Comment by rabadin** [comment]
@technosophos Thanks for looking at this! No, I didn't file an issue because I thought the problem was fairly transparent: it's the usual problem when clients access a half-written file and break. I'm happy to file an issue if that helps. Please let me know if you need me to do this or if this PR and its description is enough.

**Comment by technosophos** [comment]
Yeah -- please file an issue and link to it. We're trying to get a little better at our bookkeeping.

**Comment by rabadin** [comment]
@technosophos Sure; that's done now (see #7954).

File: internal/fileutil/fileutil.go [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+
+	if err := tempFile.Close(); err != nil {
+		return err
+	}
+
+	if err := os.Chmod(tempName, mode); err != nil {
+		return err
+	}
+
+	return os.Rename(tempName, filename)
```
Comment (bacongobbler) [inline internal/fileutil/fileutil.go:48]: Can you use `RenameWithFallback` in pkg `internal/third_party/dep/fs` instead? Otherwise this will result in the same cross-device errors seen in #2998 and #7987.

**Review by bacongobbler — CHANGES_REQUESTED** [review]

**Comment by bacongobbler** [comment]
You may also want to remove `atomicWriteFile` in favour of this package, which was introduced in #7720.

File: internal/fileutil/fileutil.go (hunk 1 above)
Comment (rabadin) [reply internal/fileutil/fileutil.go:48]: Good point. Done.

**Review by bacongobbler — APPROVED** [review]
needs another maintainer's approval before merging, but this looks good to me!

fixes #7988 
fixes #7987

**Review by technosophos — APPROVED** [review]
Looks great.

**Comment by technosophos** [comment]
I believe it was #7988 that this was supposed to correct, so I am taking the liberty of updating the original issue post, and then I am merging this for 3.3.0

**Comment by technosophos** [comment]
Based on #7987, I have marked this for inclusion on 3.2.1 instead of 3.3.0, as it is a bug fix by that definition.
