### PR TITLE
harmonize URL reference resolving

### LINKED ISSUE #11472: Helm pull fails if repo URL contains Azure Blob SAS token
<!-- If you need help or think you have found a bug, please help us with your issue by entering the following information (otherwise you can delete this text): -->

Output of `helm version`:
```
version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.19.1"}
```

Output of `kubectl version`:
Not applicable 

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Helm repo on Azure Blob with SAS token


We use Azure Blob as Helm repo.
To authenticate we issue SAS tokens with required permissions.
This works perfectly fine if you add the Helm repo
```
$ helm repo add test 'https://testhelmrepos.blob.core.windows.net/test/upstream/?sp=rl&st=2022-10-26T06:27:46Z&se=2022-10-26T14:27:46Z&spr=https&sv=2021-06-08&sr=c&sig=6AFsNmWcqdm25UeIzOyvfoqPLk3iJjPClu6J6C93rOk%3D'

$ helm repo list
NAME                            URL                                                                                                                                                                                                                                                                                                                                 
test                            https://testhelmrepos.blob.core.windows.net/test/upstream/?sp=rl&st=2022-10-26T06:27:46Z&se=2022-10-26T14:27:46Z&spr=https&sv=2021-06-08&sr=c&sig=6AFsNmWcqdm25UeIzOyvfoqPLk3iJjPClu6J6C93rOk%3D
```

You can also pull charts by referencing the added Helm repo
```
$ helm pull --destination /tmp/test --version 12.0.3 test/nginx
```

What does not work is pulling the Helm chart by providing the repo URL containing the SAS token:
```
$ helm pull --destination /tmp/test --version 12.0.3 --repo 'https://testhelmrepos.blob.core.windows.net/test/upstream/?sp=rl&st=2022-10-26T06:27:46Z&se=2022-10-26T14:27:46Z&spr=https&sv=2021-06-08&sr=c&sig=6AFsNmWcqdm25UeIzOyvfoqPLk3iJjPClu6J6C93rOk%3D' nginx
Error: failed to fetch https://testhelmrepos.blob.core.windows.net/test/upstream/nginx-12.0.3.tgz : 404 The specified resource does not exist.
```

You can clearly see in the error that the SAS token is missing from the contructed URL.
If you use `curl` with the correct URL it just works.
```
$ curl -O 'https://testhelmrepos.blob.core.windows.net/test/upstream/?sp=rl&st=2022-10-26T06:27:46Z&se=2022-10-26T14:27:46Z&spr=https&sv=2021-06-08&sr=c&sig=6AFsNmWcqdm25UeIzOyvfoqPLk3iJjPClu6J6C93rOk%3D/nginx-12.0.3.tgz'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   408  100   408    0     0    968      0 --:--:-- --:--:-- --:--:--   987
$  ls nginx-12.0.3.tgz
nginx-12.0.3.tgz
```

### PR DESCRIPTION
**Pull request by phil9909**
**What this PR does / why we need it**:

Fixes https://github.com/helm/helm/issues/11472

TL;DR

Currently helm behaves differently when doing:

```bash
helm repo add test 'https://example.com?query'
helm pull test/test
```

versus

```bash
helm pull --repo 'https://example.com?query' test
```

(the later case drops the `?query` while the former preserves it)

This PR makes sure both cases use the same code for url "reference resolving" to ensure consistent behavior even in the future.

I also refactored the `TestResolveReferenceURL` test into a table test.

**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

On backwards compatibility; In theory someone could rely on helm dropping the query parameters.

### CODE REVIEW

File: pkg/downloader/chart_downloader.go [hunk 1]
```diff
@@ -294,32 +294,13 @@ func (c *ChartDownloader) ResolveChartVersion(ref, version string) (*url.URL, er
...
-			return repoURL, err
-		}
-		q := repoURL.Query()
-		// We need a trailing slash for ResolveReference to work, but make sure there isn't already one
-		repoURL.RawPath = strings.TrimSuffix(repoURL.RawPath, "/") + "/"
-		repoURL.Path = strings.TrimSuffix(repoURL.Path, "/") + "/"
-		u = repoURL.ResolveReference(u)
-		u.RawQuery = q.Encode()
-		// TODO add user-agent
-		if _, err := getter.NewHTTPGetter(getter.WithURL(rc.URL)); err != nil {
```
Comment (phil9909) [inline pkg/downloader/chart_downloader.go:315]: `NewHTTPGetter` can never return an error and seems to have no side effects, so I did not copy it over to `ResolveReferenceURL`, Might be a leftover from some refactoring.

**Review by mattfarina — APPROVED** [review]
Note, this needs approval from a second maintainer before it can be merged.

**Comment by mattfarina** [comment]
Note to future reviewers... for our purposes the query string on the base is the one that needs to be preserved. This is because access keys and other information is put on to the base for access to the repo. The normal Go handling is to preserve the query from the URI passed in when resolving. That makes sense for the default Go behavior.

**Review by scottrigby — APPROVED** [review]
Thanks for this PR @phil9909 👍 fixes #11472, and nice cleanup

**Comment by phil9909** [comment]
Anything missing for this to be merged?

It has two approvals, no conflicts and all checks have passed.
