### PR TITLE
fix(tiller): ensure only the parent NOTES is used

### LINKED ISSUE #1407: Dependent chart NOTES.txt sometimes gets rendered instead of the parent's
The logic for rendering the notes finds the first template ending in `NOTES.txt` (https://github.com/kubernetes/helm/blob/master/cmd/tiller/release_server.go#L673). Sometimes, it picks up the dependent chart's NOTES.txt, but it should always use the parent chart's NOTES.txt.

For example, when trying to install WordPress:

```
$ helm install stable/wordpress --namespace wp
NAME: wiggly-seal
LAST DEPLOYED: Tue Oct 18 16:11:34 2016
NAMESPACE: wp
STATUS: DEPLOYED

RESOURCES:
==> extensions/Deployment
NAME                    DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
wiggly-seal-wordpress   1         1         1            0           0s
wiggly-seal-mariadb   1         1         1         0         0s

==> v1/PersistentVolumeClaim
NAME                  STATUS    VOLUME    CAPACITY   ACCESSMODES   AGE
wiggly-seal-mariadb   Pending                                      1s
wiggly-seal-wordpress-wordpress   Pending                                 0s
wiggly-seal-wordpress-apache   Pending                                 0s

==> v1/Service
NAME                  CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
wiggly-seal-mariadb   10.103.242.118   <none>        3306/TCP   1s
wiggly-seal-wordpress   10.103.251.176   <pending>   80/TCP,443/TCP   1s

==> v1/Secret
NAME                  TYPE      DATA      AGE
wiggly-seal-mariadb   Opaque    2         0s
wiggly-seal-wordpress   Opaque    2         0s


NOTES:
MariaDB can be accessed via port 3306 on the following DNS name from within your cluster:
wiggly-seal-mariadb.wp.svc.cluster.local

To connect to your database run the following command:

   kubectl run wiggly-seal-mariadb-client --rm --tty -i --image bitnami/mariadb --command -- mysql -h wiggly-seal-mariadb
```

### PR DESCRIPTION
**Pull request by prydonius**
fixes #1407

cc @vaikas-google @technosophos @adamreese

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/helm/1409)

### CODE REVIEW

File: cmd/tiller/release_server.go [hunk 1]
```diff
@@ -678,7 +679,10 @@ func (s *releaseServer) renderResources(ch *chart.Chart, values chartutil.Values
 	notes := ""
 	for k, v := range files {
 		if strings.HasSuffix(k, notesFileSuffix) {
-			notes = v
+			// Only apply the notes if it belongs to the parent chart
+			if k == filepath.Join(ch.Metadata.Name, notesFileSuffix) {
```
Comment (prydonius) [inline cmd/tiller/release_server.go]: I think you were right, it is `$NAME/templates/NOTES.txt` when running tiller for real, but in the tests it's `$NAME/NOTES.txt`. Not sure why it was like that in the tests, but I should have checked it when running tiller at the time D:
