### PR TITLE
fix(helm): make repo index not require repo_url

### LINKED ISSUE #1111: "helm repo index" requires the hosted repo url to be provided
The "index.yaml" for a chart repository, currently contains in the full **url** for each chart, however the "repo_url" is already available in the "repositories.yaml" for the given repository.

The repo_url is required by the "helm repo index" command to create the index.yaml

Having the full url for each chart:
- Prevents portability of the repository
- It is not always clear where a "private" repository will be hosted when indexing it
- DNS lookup may expose the repository at a different URL
- Relocation or replication of the repository is not possible without re-indexing
- Generally, it is less flexible to duplicate the host repo url in the repo index metadata

Other software packaging and repository solutions, for example "yum" do not hard-code the host repo url in the repository metadata.

### Current behaviour
`$ helm repo index test_repo`
`Error: This command needs 2 arguments: path to a directory, url of chart repository`
`$ head test_repo/index.yaml`
`alpine-0.1.0:`
`  name: alpine`
`  url: http://localhost:8879/charts/alpine-0.1.0.tgz`

### Wanted Behaviour:
`$ helm repo index test_repo`
`$ head test_repo/index.yaml`
`alpine-0.1.0:`
`  name: alpine`
`  url: alpine-0.1.0.tgz`

- "repo index" does not require the host repo_url, to index the repo
- chart fetching logic should support relative URLs for the chart url field in the index.yaml

### PR DESCRIPTION
**Pull request by joe2far**
fixes #1111

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/helm/1112)

### CODE REVIEW

File: cmd/helm/repo.go [hunk 1]
```diff
@@ -107,16 +107,20 @@ func runRepoRemove(cmd *cobra.Command, args []string) error {
...
+	if err := checkArgsLength(1, len(args), "path to a directory"); err != nil {
 		return err
 	}
 
 	path, err := filepath.Abs(args[0])
 	if err != nil {
 		return err
 	}
+	url := ""
+	if len(args) == 2 {
```
Comment (michelleN) [inline cmd/helm/repo.go]: In the scenario, there will never be a second argument, so we'll never meet this criteria.

**Comment by michelleN** [comment]
@joe2far - thanks for this. It simplifies the index nicely!

File: cmd/helm/repo.go (hunk 1 above)
Comment (technosophos) [inline cmd/helm/repo.go]: This should be allowed, right? We do want to be able to pass a base URL in. It's the earlier part of limiting to only 1 arg that we want to avoid.

Comment (joe2far) [inline cmd/helm/repo.go]: Yes, didn't realise it was limited to 1 argument above in checkArgs function.

I still want to allow the "repo_url" to be provided, but want to make it optional..
Updating the PR. now...

Comment (joe2far) [inline cmd/helm/repo.go]: Yes, didn't realise it was limited to 1 argument, above in checkArgs function.

I still want to allow the "repo_url" to be provided, but want to make it optional..
Updating the PR. now...

**Comment by technosophos** [comment]
Yeah, that looks much better to me.

**Comment by michelleN** [comment]
looks good

File: cmd/helm/repo.go (hunk 1 above)
Comment (michelleN) [inline cmd/helm/repo.go]: thanks. looks good.

**Comment by michelleN** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/1112)*

**Comment by michelleN** [comment]
*[cmd/helm/repo.go, line 119 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/1112#-KQ5qo9b0wdE8Z3Xeqxq-r1-119:-KQRULSxRl8sXayasgP9:b-uz0iwn) ([raw file](https://github.com/kubernetes/helm/blob/680254681efceb19de7d0cb0e6dbf3a32be0db78/cmd/helm/repo.go#L119)):*
<details><summary><i>Previously, michelleN (Michelle Noorali) wrote…</i></summary>
> thanks. looks good.
</details>
OK (think I have to type this for REVIEWABLE)

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/1112)*

**Comment by michelleN** [comment]
LGTM

**Comment by michelleN** [comment]
*[cmd/helm/repo.go, line 119 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/1112#-KQ5qo9b0wdE8Z3Xeqxq-r1-119:-KQRVEvf0oytVB_iXE65:bb6ywmx) ([raw file](https://github.com/kubernetes/helm/blob/680254681efceb19de7d0cb0e6dbf3a32be0db78/cmd/helm/repo.go#L119)):*
<details><summary><i>Previously, michelleN (Michelle Noorali) wrote…</i></summary>
> OK (think I have to type this for REVIEWABLE)
</details>
LGTM

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/1112)*

**Comment by michelleN** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/1112#-:-KQRVnDrcKVDFn_vBmsb:bnfp4nl)*

**Comment by michelleN** [comment]
*[cmd/helm/repo.go, line 119 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/1112#-KQ5qo9b0wdE8Z3Xeqxq-r1-119:-KQRWWeLh63N1UhQra8M:bb6ywmx) ([raw file](https://github.com/kubernetes/helm/blob/680254681efceb19de7d0cb0e6dbf3a32be0db78/cmd/helm/repo.go#L119)):*
<details><summary><i>Previously, michelleN (Michelle Noorali) wrote…</i></summary>
> LGTM
</details>
LGTM

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/helm/1112)*
