### PR TITLE
fix: preserve vendor suffixes in KubeVersion.GitVersion

### LINKED ISSUE #31423: Helm 3.19.0: .Capabilities.KubeVersion.GitVersion renders incorrectly
### What happened?

when using a simple template:

```yaml
kubeVersionGitVersion: {{ .Capabilities.KubeVersion.GitVersion }}
```

when rendering the above with Helm 3.19.0 with `--kube-version v1.33.4-gke.1245000`, we get:

```
❯ helm template --show-only templates/foo.yaml --kube-version v1.33.4-gke.1245000 test ../chart
---
# Source: foo/templates/foo.yaml
kubeVersionGitVersion: v1.33.4
```

### What did you expect to happen?

With Helm 3.18.6, we get:

```
❯ helm template --show-only templates/foo.yaml --kube-version v1.33.4-gke.1245000 test ../chart
---
# Source: foo/templates/foo.yaml
kubeVersionGitVersion: v1.33.4-gke.1245000
```

which is the expected result

The Istio CNI Helm Chart relies on the full `GitVersion` to detect if it's a GKE cluster: https://github.com/istio/istio/blob/d238f77182476b6a83da60d6cac98f886948df77/manifests/charts/istio-cni/templates/daemonset.yaml#L8C25-L8C61

I suspect this may be related to https://github.com/helm/helm/pull/31091

### How can we reproduce it (as minimally and precisely as possible)?

provided above, very easy to reproduce

### Helm version

<details>

```console
$ helm version
version.BuildInfo{Version:"v3.19.0", GitCommit:"3d8990f0836691f0229297773f3524598f46bda6", GitTreeState:"clean", GoVersion:"go1.25.1"}
```
</details>

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.33.4-gke.1245000
Kubecolor Version: v0.5.0
```

</details>

### PR DESCRIPTION
**Pull request by benoittgt**
**What this PR does / why we need it**:

Helm 3.19.0 introduced a regression where vendor-specific suffixes (e.g., -gke.1245000, -eks-4096722, +) are stripped from `.Capabilities.KubeVersion.GitVersion`, breaking charts that detect managed Kubernetes platforms (https://github.com/helm/helm/issues/31423).

The root cause was using `k8sversion.ParseGeneric().String()` which intentionally discards vendor suffixes. It is good thing for comparaison but no when return the full `GitVersion`. The fix preserves the original version string while still using `ParseGeneric()` for validation and Major/Minor extraction.

I am not super happy with the fix, especially with `String()`, but I was not able to find easier path.

Fixes #31423
Related to #31063, #31078

**Special notes for your reviewer**:

Script I used to check the behavior:

```sh
#!/bin/bash
set -e

make build

mkdir -p /tmp/test-chart/templates
cat > /tmp/test-chart/Chart.yaml <<EOF
apiVersion: v2
name: test-chart
version: 0.1.0
kubeVersion: ">= 1.21.0"
EOF

cat > /tmp/test-chart/templates/test.yaml <<'EOF'
version: {{ .Capabilities.KubeVersion.Version }}
EOF

./bin/helm template /tmp/test-chart --kube-version v1.33.4-gke.1245000 | grep -q "version: v1.33.4-gke.1245000" || {
  echo "FAIL: GKE suffix not preserved"
  exit 1
}

./bin/helm template /tmp/test-chart --kube-version 1.28+ | grep -q "version: v1.28+" || {
  echo "FAIL: + not preserved"
  exit 1
}

rm -rf /tmp/test-chart
echo "Looks good!"
```

Tiny increase in coverage 🐜 :
```
ok      helm.sh/helm/v4/pkg/chart/common        0.333s  coverage: 76.5% of statements
ok      helm.sh/helm/v4/pkg/chart/common        0.389s  coverage: 77.0% of statements
```

**If applicable**:
- [ ] this PR contains user facing changes (the `docs needed` label should be applied if so). Not sure it needs to be documented
- [x] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

File: pkg/chart/common/capabilities.go [hunk 1]
```diff
@@ -70,15 +73,22 @@ func (capabilities *Capabilities) Copy() *Capabilities {
...
+	Major             string // Kubernetes major version
+	Minor             string // Kubernetes minor version
 }
 
-// String implements fmt.Stringer
-func (kv *KubeVersion) String() string { return kv.Version }
+// String implements fmt.Stringer.
+// Returns the normalized version for constraint checking.
+func (kv *KubeVersion) String() string {
+	if kv.normalizedVersion != "" {
```
Comment (benoittgt) [inline pkg/chart/common/capabilities.go:85]: That’s the part I’m the least convinced about. But at least is backward compatible and produce something relevant.

**Review by robertsirc — APPROVED** [review]
LGTM

**Review by TerryHowe — APPROVED** [review]
/lgtm

Full tests pass for me

**Review by sabre1041 — APPROVED** [review]
LGTM

**Comment by benoittgt** [comment]
I have two approvals. Is it possible to merge @sabre1041 ?
