### PR TITLE
Preparation for api cleanup.

### LINKED ISSUE #255: dm fails to query escape deployment and manifest names
Deployment names, in particular, cause problems when not query escaped, since they default to type names in several cases. Making this a P1, even though dm will be replaced by helm soon, since the bug might propagate to helm if not corrected here.

### LINKED ISSUE #258: Regex not passed by client or read by server from URL
There are 4 related bugs in the regex based filtering of template names:
* dm doesn't pass a regex to the server for command `templates`. 
* The default regex in dm is an empty string, not an expression that matches everything.
* The route path for ListRegistryTypesHandlerFunc doesn't admit a regex.
* ListRegistryTypesHandlerFunc calls getPathVariable to look for the regex instead of getting from the query string.

### PR DESCRIPTION
**Pull request by jackgr**
Fixes #255. Fixes #258.

This PR also makes 3 additional changes in preparation for api cleanup:
- Removes the unnecessary use of download urls for computing type instances.
- Moves the construction of a template from a type name to the expander package.
- Moves metadata retrieval to the sever.

With these changes, the client no longer needs to fetch download urls for any purpose other than file download requests.

/cc @michelleN

### CODE REVIEW

**Comment by jackgr** [comment]
This PR also makes two additional changes in preparation for api cleanup:
* Removes the unnecessary use of download urls for computing type instances.
* Moves the construction of a template from a type name to the expander package.

File: dm/dm.go [hunk 1]
```diff
@@ -166,9 +166,19 @@ func execute() {
 	switch args[0] {
 	case "templates":
 		path := fmt.Sprintf("registries/%s/types", *templateRegistry)
+		if *regexString != "" {
```
Comment (vaikas-google) [inline dm/dm.go]: I'm fine with this change, but I thought we were working on the new client and all these client side changes are throwaway code?

File: expandybird/expander/expander.go [hunk 2]
```diff
@@ -46,6 +46,30 @@ func NewExpander(binary string) Expander {
 	return &expander{binary}
 }
 
+// NewTemplateFromType creates and returns a new template whose content
+// is a YAML marshaled resource assembled from the supplied arguments.
+func NewTemplateFromType(name, typeName string, properties map[string]interface{}) (*common.Template, error) {
```
Comment (vaikas-google) [inline expandybird/expander/expander.go]: Wouldn't this be more appropriate in the util/* something instead of expander?

File: dm/dm.go (hunk 1 above)
Comment (jackgr) [inline dm/dm.go]: I'm not sure how much content they have yet to pull from the client, so until we know they're done pulling content from it, I think it makes sense to make it work correctly. It was an easy change, so made sense to do it, especially to make sure the server handles the regex in the query string correctly.

File: expandybird/expander/expander.go (hunk 2 above)
Comment (jackgr) [inline expandybird/expander/expander.go]: Well, all of the other NewTemplateFrom... methods are in this package, in fact in this file. One could argue that the whole set of methods could go into a package used by clients. I'd buy that argument. However, unless/until we do that, this is right place for all NewTemplateFrom... methods.

Comment (vaikas-google) [inline expandybird/expander/expander.go]: Yeah, I should've made it clear, I don't think they belong in this package at all :) Could you open an issue to move them out of here and I can clean that up?

**Comment by vaikas-google** [comment]
Looks like tests are failing, other than that LGTM (with the creation of the issue mentioned above).

File: expandybird/expander/expander.go (hunk 2 above)
Comment (jackgr) [inline expandybird/expander/expander.go]: Great suggestion. Created #261.

**Comment by jackgr** [comment]
@vaikas-google yes, I saw the test failures. They don't repro in my environment, and aren't in the vicinity of anything changed in this PR. If anything, they might be related to the reported expandybird failures (#209, #227, #228).
