### PR TITLE
fix(helm): add dry-run flag for init

### LINKED ISSUE #1417: Support for the tiller image to be managed by Kube Admins
As a Kubernetes cluster admin, we would like to manage the deployment and lifecycle of the tiller image to ensure that we control the version of dm backend for our users. 

We are the only one with write access to the `kube-system` namespace and therefore our k8s users are getting errors when trying to run helm init.

For this reason, we would like to get official manifest files for the deployment and service object. 

This will ensure that we can keep using our current kube-system namespace deployment logic and align the delivery process of kube-system service with the other kubernetes components.

### PR DESCRIPTION
**Pull request by technosophos**
This adds a --dry-run flag to init, and causes the manifest file for
Tiller to be emitted on --debug. Together, this means you can do a
'helm init --dry-run --debug' and dump the Tiller manifest much as you
can with 'helm install --dry-run --debug'.

This does not require a server round-trip.

Closes #1417

### CODE REVIEW

**Comment by technosophos** [comment]
Example: 

```console
⇒  helm init --dry-run --debug                                                                                              1 ↵
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helm
        name: tiller
    spec:
      containers:
      - image: gcr.io/kubernetes-helm/tiller:v2.0.0-beta.1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /liveness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        name: tiller
        ports:
        - containerPort: 44134
          name: tiller
        readinessProbe:
          httpGet:
            path: /readiness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        resources: {}
      serviceAccountName: ""
      volumes: null
status: {}
```

Will this work for you, @djsly?

**Comment by djsly** [comment]
That's pretty helpful indeed. Prevents me from doing a real init to export the manifest. 

After I import this, how can I ensure that other users with `kube-system` access won't alter the manifest by doing a subsequent `helm init` ? 

Will the client be smart enough to detect the deployment object is already present ? will a newer client force the running tiller to be updated ?

**Comment by technosophos** [comment]
On `helm init`, the client checks to see if there is already a `helm-deployment` deployment in the `kube-system` namespace. If so, it does not attempt to install, and `init` _only_ does its local configuration.

**Comment by djsly** [comment]
ok I like the `for the time being` statement :) 
I would like to manage the version of tiller that gets deployed as we release a cluster version to the user with a set of docker images running inside the `kube-system`. 

My only concern was that I had Helm user who told me that sometimes they download the latest heml and they are forced to align the tiller image. If you are saying that this enforcement right now is a  manual step. I'm happy with this.

**Comment by djsly** [comment]
LTGM

File: cmd/helm/init_test.go [hunk 1]
```diff
@@ -87,7 +89,7 @@ func TestInitCmd_clientOnly(t *testing.T) {
 	fake := testclient.Fake{}
 	cmd := &initCmd{out: &buf, home: helmpath.Home(home), kubeClient: fake.Extensions(), clientOnly: true}
 	if err := cmd.run(); err != nil {
-		t.Errorf("expected error: %v", err)
+		t.Errorf("unexpected error: %v", err)
```
Comment (adamreese) [inline cmd/helm/init_test.go]: expect the unexpected
