### PR TITLE
fix(engine): change template naming

### LINKED ISSUE #933: Dependent chart template helpers are not evaluated
I was setting up a chart that used a MariaDB chart and created a `name` function in `./templates/_helpers.tpl` and `./charts/mariadb/templates/_helpers.tpl`. When doing a dry-run install I found that the MariaDB chart would ignore the definition of `name` in it's helpers and use the parent's instead. This was a weird side-effect, and since functions are not namespaced it would be easy to accidentally override.

After digging into it further though, I renamed `name` in MariaDB's helper to `mariadbName` and that caused this error:
```
Error: render error in "templates/mariadb-svc.yaml": template: templates/mariadb-svc.yaml:4:19: executing "templates/mariadb-svc.yaml" at <{{template "mariadbN...>: template "mariadbName" not defined
```

So it seems that MariaDB's helpers are not being evaluated. Any ideas?

### PR DESCRIPTION
**Pull request by technosophos**
Template paths were relative to the chart that contained them, which
meant that all templates were named 'template/SOMETHING'. This made it
trivially easy to hit namespace collisions as in #933.

Template path names are essentially opaque strings so this patch simply
changes them to be qualified by parent chart.

Closes #933

### CODE REVIEW

**Comment by technosophos** [comment]
Just to be clear on what's happening here:

- Templates are stored as name/value pairs, with relative path as the name, and the template as the value
- In the past, the path was relative to the chart, so all paths were `template/SOMTHING`
- This re-constructs the full path to the template, so you'll get `foo/template/SOMETHING` or `foo/charts/bar/template/SOMETHING`

Really, the names of templates are used for only three things:

- Populating the {{.Template.Name}} field
- debugging
- internal Go naming

So this change won't have much of an impact on end users, other than avoiding the problem @prydonius reported.

File: pkg/engine/engine.go [hunk 1]
```diff
@@ -170,11 +172,19 @@ func recAllTpls(c *chart.Chart, templates map[string]renderable, parentVals char
 		}
 	}
 
+	newParentId := c.Metadata.Name
+	if parentId != "" {
+		// We artificially reconstruct the chart path to child templates. This
+		// creates a namespaced filename that can be used to track down the source
+		// of a particular template declaration.
+		newParentId = parentId + "/charts/" + newParentId
```
Comment (prydonius) [inline pkg/engine/engine.go]: should this use `filepath.Join`?

**Comment by prydonius** [comment]
Just tested and this does indeed fix the issue in #933, awesome!

File: pkg/engine/engine_test.go [hunk 2]
```diff
@@ -288,19 +290,19 @@ global:
...
 		t.Errorf("Unexpected outer: %q", out[outerpath])
 	}
 
-	if out[innerpath] != "Old time is still a-flyin'" {
+	if out["top/charts/herrick/"+innerpath] != "Old time is still a-flyin'" {
 		t.Errorf("Unexpected inner: %q", out[innerpath])
 	}
 
-	if out[deepestpath] != "And this same flower that smiles to-day" {
+	if out["top/charts/herrick/charts/deepest/"+deepestpath] != "And this same flower that smiles to-day" {
```
Comment (prydonius) [inline pkg/engine/engine_test.go]: Perhaps `deepestpath` could be named `inner.tpl` or `outer.tpl` to have a test that ensures collisions don't occur? Or it could even be a separate test.

Comment (technosophos) [inline pkg/engine/engine_test.go]: Good idea.

**Comment by technosophos** [comment]
Okay, all of the issues and changes @prydonius suggested are now committed.

File: pkg/engine/engine_test.go [hunk 3]
```diff
@@ -220,10 +222,12 @@ func TestRenderDependency(t *testing.T) {
 func TestRenderNestedValues(t *testing.T) {
 	e := New()
 
-	innerpath := "charts/inner/templates/inner.tpl"
+	innerpath := "templates/inner.tpl"
 	outerpath := "templates/outer.tpl"
-	deepestpath := "charts/inner/charts/deepest/templates/deepest.tpl"
-	checkrelease := "charts/inner/charts/deepest/templates/release.tpl"
+	//deepestpath := "templates/deepest.tpl"
```
Comment (adamreese) [inline pkg/engine/engine_test.go]: Should this comment be left in?

Comment (technosophos) [inline pkg/engine/engine_test.go]: Removed. I'll merge as soon as CircleCI passes
