### PR TITLE
fix "Chart.lock is out of sync with Chart.yaml"

### LINKED ISSUE #7101: Error: Chart.lock is out of sync with Chart.yaml when using dependencies and version ranges
Output of `helm version`:
```
$ helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

This is what I am experiencing, easily recreated as below:
```
 $ helm create 1
Creating 1
 $ helm create 2
Creating 2
 $ vim 2/Chart.yaml
```
and add to the chart:
```
dependencies:
- name: 1
  repository: file://../1
  version: ^0.1.0
- name: mysql
  condition: mysql.enabled
  repository: https://kubernetes-charts.storage.googleapis.com
  version: ^1.4.0
- name: redis
  condition: redis.enabled
  repository: https://kubernetes-charts.storage.googleapis.com
  version: ^3.0.0
```

and then:
```
 $ helm dep up 2
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 3 charts
Downloading mysql from repo https://kubernetes-charts.storage.googleapis.com
Downloading redis from repo https://kubernetes-charts.storage.googleapis.com
Deleting outdated charts
 $ helm dep build 2
Error: Chart.lock is out of sync with Chart.yaml
```

Any ideas?

### PR DESCRIPTION
**Pull request by zwwhdls**
fixed #7101

I have found that downloadAll() might overwrite version in Chart.lock.

It's because this function will download a specific version of chart to dir "charts/" and then the specific version will overwrite the version in Chart.lock.

My solution is recalculate lock digest after downloadAll().

### CODE REVIEW

**Comment by bacongobbler** [comment]
Hi! Can you write a test to confirm this behaviour? Thanks!

**Comment by zwwhdls** [comment]
@bacongobbler Hi, I added a test case for this issue.

File: pkg/downloader/manager_test.go [hunk 1]
```diff
@@ -181,6 +181,74 @@ func TestGetRepoNames(t *testing.T) {
 	}
 }
 
+func TestUpdate_BeforeBuild(t *testing.T) {
```
Comment (hickeyma) [inline pkg/downloader/manager_test.go]: Rename as `TestUpdateBeforeBuild` to follow test name continuity

**Review by hickeyma — CHANGES_REQUESTED** [review]
Looking good @zwwhdls. Small nit before merge.

**Comment by zwwhdls** [comment]
@hickeyma Hi, I have renamed the testcase already.

**Review by hickeyma — APPROVED** [review]
LGTM, thanks @zwwhdls
