### PR TITLE
Fix URL with encoded path support for ChartDownloader

### LINKED ISSUE #9977: Can't use repo URLs that contain URL-encoded characters (e.g., Gitlab)
Output of `helm version`:
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Vagrant/Libvirt/LVM, repo hosted on Gitlab

Thank you for Helm! We're using it with a Gitlab repo and I had a problem because it looks like Helm decodes any URL-encoding in the repo URL. For example, my project on gitlab is https://gitlab.com/api/v4/projects/acnodal%2FEGO/packages/helm/stable . The "%2F" is significant to Gitlab, it's not the same as "/". 

The "helm repo add" and "helm repo update" commands succeed, and I can search the repo and find packages, but an install command fails:

```
$ helm install --debug --namespace purelb --version=v0.3.2-ego20 ego ego/purelb
install.go:159: [debug] Original chart version: "v0.3.2-ego20"                                            
Error: failed to fetch https://gitlab.com/api/v4/projects/acnodal/EGO/packages/helm/stable/charts/purelb-v0.3.2-ego20.tgz : 404 Not Found                                                                            
helm.go:84: [debug] failed to fetch https://gitlab.com/api/v4/projects/acnodal/EGO/packages/helm/stable/charts/purelb-v0.3.2-ego20.tgz : 404 Not Found
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).get                                                                                                                                                                                 /home/circleci/helm.sh/helm/pkg/getter/httpgetter.go:73
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).Get                                                                                                                                                                                 /home/circleci/helm.sh/helm/pkg/getter/httpgetter.go:41                                           
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
        /home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:97
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
        /home/circleci/helm.sh/helm/pkg/action/install.go:667
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:171
main.newInstallCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/install.go:117
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:83
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
```
Note that the original "/acnodal%2FEGO/" in the URL has become "/acnodal/EGO/" which is not the same URL. This causes Gitlab to return a 404.

### PR DESCRIPTION
**Pull request by sathieu**
**What this PR does / why we need it**:

When the repo url contains URL-encoded parts, and doesn't end with `/`, relative downloads are not properly resolved.

Example, with  current main (3d1bc72827e4edef273fb3d8d8ded2a25fa6f39d):

```shell
$ bin/helm repo add kubitus-ingress-operator https://gitlab.com/api/v4/projects/kubitus-project%2Fkubitus-ingress-operator/packages/helm/stable
"kubitus-ingress-operator" has been added to your repositories

$ show.go:173: [debug] Original chart version: ""
Error: failed to fetch https://gitlab.com/api/v4/projects/kubitus-project/kubitus-ingress-operator/packages/helm/stable/charts/kubitus-ingress-operator-v0.2.0.tgz : 404 Not Found
helm.go:81: [debug] failed to fetch https://gitlab.com/api/v4/projects/kubitus-project/kubitus-ingress-operator/packages/helm/stable/charts/kubitus-ingress-operator-v0.2.0.tgz : 404 Not Found
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).get
        /home/circleci/helm.sh/helm/pkg/getter/httpgetter.go:73
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).Get
        /home/circleci/helm.sh/helm/pkg/getter/httpgetter.go:41
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
        /home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:99
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
        /home/circleci/helm.sh/helm/pkg/action/install.go:675
main.runShow
        /home/circleci/helm.sh/helm/cmd/helm/show.go:179
main.newShowCmd.func4
        /home/circleci/helm.sh/helm/cmd/helm/show.go:116
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374
```

As you can see, `%2F` was replaced by `/` which leads to `404 Not found`.

We this patch applied, it works:

```
$ bin/helm show chart  kubitus-ingress-operator/kubitus-ingress-operator --debug
show.go:195: [debug] Original chart version: ""
apiVersion: v2
appVersion: main
dependencies:
- condition: metacontroller.enabled
  name: metacontroller
  repository: ""
description: Kubitus Ingress Operator
home: https://gitlab.com/kubitus-project/kubitus-ingress-operator
name: kubitus-ingress-operator
sources:
- https://gitlab.com/kubitus-project/kubitus-ingress-operator
type: application
version: v0.2.0
```
**Special notes for your reviewer**:

Fixes: #9977.

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains unit tests
- [x] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by sathieu** [comment]
@cndoit18 Please review this one (split out of #9763).

File: pkg/downloader/chart_downloader.go [hunk 1]
```diff
@@ -262,6 +262,7 @@ func (c *ChartDownloader) ResolveChartVersion(ref, version string) (*url.URL, er
 		}
 		q := repoURL.Query()
 		// We need a trailing slash for ResolveReference to work, but make sure there isn't already one
+		repoURL.RawPath = strings.TrimSuffix(repoURL.RawPath, "/") + "/"
```
Comment (cndoit18) [inline pkg/downloader/chart_downloader.go:265]: https://github.com/helm/helm/pull/9763#discussion_r644001942

**Review by cndoit18 — CHANGES_REQUESTED** [review]

File: pkg/downloader/chart_downloader.go (hunk 1 above)
Comment (sathieu) [reply pkg/downloader/chart_downloader.go:265]: This doesn't work (when the URL has a query string):

```
    chart_downloader_test.go:79: reference, querystring repo: expected http://example.com/alpine-1.2.3.tgz?key=value, got http://example.com/alpine-1.2.3.tgz?key=value%2F
```

```diff
diff --git a/pkg/downloader/chart_downloader.go b/pkg/downloader/chart_downloader.go
index 6134c0e6..bb1ba90a 100644
--- a/pkg/downloader/chart_downloader.go
+++ b/pkg/downloader/chart_downloader.go
@@ -256,14 +256,12 @@ func (c *ChartDownloader) ResolveChartVersion(ref, version string) (*url.URL, er
 
        // If the URL is relative (no scheme), prepend the chart repo's base URL
        if !u.IsAbs() {
-               repoURL, err := url.Parse(rc.URL)
+               // We need a trailing slash for ResolveReference to work, but make sure there isn't already one
+               repoURL, err := url.Parse(strings.TrimSuffix(rc.URL, "/") + "/")
                if err != nil {
                        return repoURL, err
                }
                q := repoURL.Query()
-               // We need a trailing slash for ResolveReference to work, but make sure there isn't already one
-               repoURL.RawPath = strings.TrimSuffix(repoURL.RawPath, "/") + "/"
-               repoURL.Path = strings.TrimSuffix(repoURL.Path, "/") + "/"
                u = repoURL.ResolveReference(u)
                u.RawQuery = q.Encode()
                // TODO add user-agent
```

**Comment by sathieu** [comment]
@mattfarina Please review this other fix about encoded slashes (similar to PR #9822).

**Comment by acnodal-tc** [comment]
LGTM. Thank you for the fix!

File: pkg/downloader/chart_downloader.go (hunk 1 above)
Comment (sathieu) [reply pkg/downloader/chart_downloader.go:270]: @cndoit18 Please review again...

**Comment by sathieu** [comment]
@hickeyma Please review :pray:.

**Comment by sathieu** [comment]
@cndoit18 @bacongobbler Please review again. I've rebased and fixed conflicts.

**Comment by sathieu** [comment]
@cndoit18 @bacongobbler Could you please take some time to review this PR?

**Comment by sathieu** [comment]
This PR is now 10 months old. Could it be added to the [3.9 milestone](https://github.com/helm/helm/milestone/116) to ensure it is reviewed? :pray:

**Comment by sathieu** [comment]
This PR is now 1 year old. Any chance to get it reviewed and hopefully merged 🍀 ?

**Review by hickeyma — APPROVED** [review]
LGTM, thanks @sathieu

**Comment by hickeyma** [comment]
This will need another Helm maintainer to review before merging.

**Comment by sathieu** [comment]
Thanks @hickeyma Would you please ping an available maintainer?

**Review by mattfarina — APPROVED** [review]
