### PR TITLE
fix(show): restore comments from raw values

### LINKED ISSUE #6354: Helm 3: helm inspect values does not show comments
Output of `helm version`:
version.BuildInfo{Version:"v3.0.0-beta.2", GitCommit:"26c7338408f8db593f93cd7c963ad56f67f662d4", GitTreeState:"clean", GoVersion:"go1.12.9"}

Output of `kubectl version`: N/A
Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

The new `helm show values` (was `helm inspect`) outputs the parsed values.yaml of the chart with comments stripped out. This is a problem for helm charts that rely heavily on comments to document the exposed options (instead of repeating that information in the README). 

I think default behavior should be the same as `helm inspect` and dump the values.yaml file verbatim. There's definitely value in presenting the parsed/stripped values as it does now, but this should probably be exposed with a flag (e.g. `--stripped`, `--parsed`, or `--no-comments`).

### PR DESCRIPTION
**Pull request by bacongobbler**
`helm show values` was reading the values as marshaled from `loader.Load`, which stripped the original comments from the values file. This PR restores the `RawValues` field to `chart.Chart` to restore `helm show values`'s previous behaviour to render the raw values file, comments and all.

closes #6354

### CODE REVIEW

**Comment by bacongobbler** [comment]
Slating this for 3.0.0 as this was a code regression introduced in Helm 3 that users had come to expect.

**Comment by bacongobbler** [comment]
Gonna pull out 7e43089 into a separate PR; it doesn't actually affect the behaviour and should be slated as a 3.1 feature.

**Comment by bacongobbler** [comment]
done; moved to #6845

**Comment by bacongobbler** [comment]
@adamreese and I paired on this one in the afternoon. While this does restore prior functionality, there has to be a better way to avoid re-introducing the `RawValues` object back to the chart. Will sleep on this and see if we can tackle this feature in a different way, likely to do with refactoring how the `Files` field works instead.

**Comment by bacongobbler** [comment]
Okay, after thinking it over last night, we're trying a new approach by loading the raw files in memory.

The problem with this new approach is that the raw files will be stored in the secret once we create the release. We could scrub it from memory during a save, though that seems a bit of a hack.

Additionally, because the `Raw` field is made public, the field can be modified after we call `LoadDir`. That doesn't seem like a good design from the SDK's point of view. It should be read-only after loading the chart.

@mattfarina suggested we could use an alternative YAML parser that preserves comments, though those libraries are currently unstable and could introduce other issues down the road.

If anyone has alternatives, I'm all ears at this point.

**Comment by bacongobbler** [comment]
hack uploaded to demonstrate a possible workaround.

**Comment by bacongobbler** [comment]
manually testing this seems to work as expected: `helm show values` display the values as expected, and the `.Raw` field is not saved during `helm install` as part of the release metadata.

```
helm create foo
helm install foo ./foo
kubectl get secret sh.helm.release.v1.foo.v1 -o jsonpath='{.data.release}' | base64 -d | base64 -d | gunzip
```

**Review by hickeyma — APPROVED** [review]
LGTM, thanks @bacongobbler

**Comment by hickeyma** [comment]
@bacongobbler It might be worth other maintainers to take a look before merging?

**Comment by bacongobbler** [comment]
Yeah. I'd like to get @adamreese's review on this one before merging as we discussed possible paths forward here.

**Comment by mattfarina** [comment]
@bacongobbler Can you resolve the conflict that's now come up here.

File: pkg/chart/loader/load.go [hunk 1]
```diff
@@ -74,6 +74,7 @@ func LoadFiles(files []*BufferedFile) (*chart.Chart, error) {
 	subcharts := make(map[string][]*BufferedFile)
 
 	for _, f := range files {
+		c.Raw = append(c.Raw, &chart.File{Name: f.Name, Data: f.Data})
```
Comment (mattfarina) [inline pkg/chart/loader/load.go]: It looks like all of the `Raw` files will be stored on the release object (by default a secret). This is going to cause them to balloon in size and we will run into storage space problems.

What happened to the change that deleted `Raw` from the release object?

**Review by mattfarina — CHANGES_REQUESTED** [review]

File: pkg/chart/loader/load.go (hunk 1 above)
Comment (hickeyma) [reply pkg/chart/loader/load.go]: When I tested this manually, I did not see `Raw` field stored.

**Comment by bacongobbler** [comment]
conflicts resolved.

**Review by mattfarina — APPROVED** [review]
