### PR TITLE
fix(helm): improve --set parser

### LINKED ISSUE #1540: Install Command: Unable to Escape Periods in Keys
The install command splits keys on every period, preventing assignment of a key containing the period character. A [RegEx Split](https://golang.org/pkg/regexp/#Regexp.Split) might be a good option to allow for these escaped characters.

- https://github.com/kubernetes/helm/blob/6b222cdc0fc7d94ce22a265d3a3580cc7afd3cab/cmd/helm/install.go#L271

e.g. yaml
```
...
    annotations:
{{ toYaml .Values.annotations | indent 6 }}
```

e.g. command
`--set annotations.iam\.amazonaws\.com/role=k8s-logger`

Result:
```
annotations:
    iam:
        amazonaws:
            com/role: k8s-logger
```

Expected:
```
annotations:
    iam.amazonaws.com/role: k8s-logger
```

### LINKED ISSUE #1556: helm CLI incorrectly splits on commas even when quoted
When using the `helm` command and overriding values using `--set`, if the key value contains a comma, the value is halted there.

I'm assuming the entire argument is being split on commas, regardless of escaping or quotes.

Testing:
```
$ helm install kubernetes-charts/mysql --set mysqlUser="test_mysqluser,blah,dee,dah" --dry-run --debug | grep test_mysqluser
```
RETURNS
```
          value: "test_mysqluser"
```

### LINKED ISSUE #1558: impossible to set string values on the command line that look like floats
I have a template which contains this:
```
{{.Values.image.repository}}:{{.Values.image.tag}}
```
trying to do `helm install --set image.tag=20161115.1` yields this:
```
hub.global.cloud.sap/monsoon/monsoon-dashboard:2.0161116e+07
```

trying to do `helm install --set 'image.tag="20161115.1"'` yields this:
```
hub.global.cloud.sap/monsoon/monsoon-dashboard:"20161115.1"
```

I think the problem lies in [cmd.helm.typedVal](https://github.com/kubernetes/helm/blob/62df1ad3588e8d4791423aec19d46bc383438c4f/cmd/helm/install.go#L293).

Seems to to me as it stands passing a string that looks like a float via cli args is not possible atm.

### PR DESCRIPTION
**Pull request by technosophos**
This replaces the old `--set` parser with a brand new one. This also changes
the internal algorithm from duplicating YAML to merging YAML, which
might solve a problem one user reported in chat, but which was never
captured in an issue because it is difficult to reproduce.

Closes #1540
Closes #1556 
Closes #1558

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/helm/1576)

### CODE REVIEW

**Comment by technosophos** [comment]
You should be able to do things like this now:

```console
$ helm install docs/examples/alpine -f _scratch/foo.yaml --set=foobar.bar=baz,imagePullPolicy=always,ver=20161115.1,port=1234,foostr=foo\\,pair
NAME: intentional-puffin
LAST DEPLOYED: Mon Nov 21 19:38:50 2016
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Pod
NAME                           READY     STATUS              RESTARTS   AGE
intentional-puffin-my-alpine   0/1       ContainerCreating   0          6m


$  helm get values intentional-puffin
foobar:
  bar: baz
  foo: bar
foostr: foo,pair
imagePullPolicy: always
port: 1234
ver: "20161115.1"
```

Note that we have to use `\\` because shell interprets the first one, and Helm interprets the second.

File: cmd/helm/strvals/parser.go [hunk 1]
```diff
@@ -0,0 +1,166 @@
...
+	t.parse()
+	return nil
+}
+
+// parser is a simple parser that takes a strvals line and parses it into a
+// map representation.
+type parser struct {
+	sc      *bytes.Buffer
+	data    map[string]interface{}
+	carryOn bool
```
Comment (technosophos) [inline cmd/helm/strvals/parser.go]: remove me

**Comment by technosophos** [comment]
Based on @adamreese 's feedback, also added support for lists:

```
$ helm install --set foo={1,2,3},bar={a,b,c} mychart
```

**Comment by technosophos** [comment]
Cherry-picking to 2.0.1
