### PR TITLE
fix(tiller): show failed YAML

### LINKED ISSUE #1499: feat: Show broken YAML on `--debug`
Right now, if there is a YAML syntax error, the result is:

```
helm install --dry-run --debug ./mychart                  1 ↵
SERVER: "localhost:44134"
CHART PATH: /Users/mattbutcher/Code/Go/src/k8s.io/helm/_scratch/mychart
Error: YAML parse error on mychart/templates/configmap.yaml: error converting YAML to JSON: yaml: line 7: did not find expected key
```

It would be nice to find a way to also show the broken YAML.

### PR DESCRIPTION
**Pull request by technosophos**
When an install fails and --dry-run is set, return the broken YAML for
the user to debug.

Closes #1499

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/helm/1546)

### CODE REVIEW

**Comment by technosophos** [comment]
⇒  helm install --dry-run --debug ./broken
SERVER: "localhost:44134"
CHART PATH: /Users/mattbutcher/Code/Go/src/k8s.io/helm/_scratch/broken
Error: YAML parse error on broken/templates/deployment.yaml: error converting YAML to JSON: yaml: line 35: did not find expected key

---
# Source: broken/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: incindiary-tap-broken
  labels:
    chart: "broken-0.1.0"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: incindiary-tap-broken
    spec:
      containers:
      - name: broken

File: pkg/tiller/release_server.go [hunk 1]
```diff
@@ -595,7 +595,14 @@ func (s *ReleaseServer) InstallRelease(c ctx.Context, req *services.InstallRelea
 	rel, err := s.prepareRelease(req)
 	if err != nil {
 		log.Printf("Failed install prepare step: %s", err)
-		return nil, err
+		res := &services.InstallReleaseResponse{Release: rel}
+
+		// On dry run, append the manifest contents to a failed release. This is
+		// a stop-gap until we can revisit an error backchannel post-2.0.
+		if req.DryRun && strings.HasPrefix(err.Error(), "YAML parse error") {
```
Comment (prydonius) [inline pkg/tiller/release_server.go]: Wouldn't it make more sense to do this only if the debug flag is provided instead?

Comment (technosophos) [inline pkg/tiller/release_server.go]: There is no debug flag on the server-side. Only DryRun gets passed to the server. And since we're API frozen right now, it's the only flag I have to work with.

Comment (prydonius) [inline pkg/tiller/release_server.go]: Ah, thanks for the explanation - makes sense!
