### PR TITLE
fix(helm): fix rollback documentation

### LINKED ISSUE #1708: Incorrect doc for `helm rollback --help`
```bash
helm rollback <release_name>
Error: This command needs 2 arguments: release name, revision number
```

```bash
helm rollback --help
This command rolls back a release to the previous revision.
The argument of the rollback command is the name of a release.

Usage:
  helm rollback [RELEASE] [flags]

Flags:
      --dry-run    simulate a rollback
      --no-hooks   prevent hooks from running during rollback

Global Flags:
      --debug                 enable verbose output
      --home string           location of your Helm config. Overrides $HELM_HOME (default "$HOME/.helm")
      --host string           address of tiller. Overrides $HELM_HOST
      --kube-context string   name of the kubeconfig context to use
```

```bash
helm version
Client: &version.Version{SemVer:"v2.1.0", GitCommit:"b7b648456ba15d3d190bb84b36a4bc9c41067cf3", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.1.0", GitCommit:"b7b648456ba15d3d190bb84b36a4bc9c41067cf3", GitTreeState:"clean"}
```

### PR DESCRIPTION
**Pull request by technosophos**
Closes #1708

### CODE REVIEW

File: cmd/helm/rollback.go [hunk 1]
```diff
@@ -48,7 +50,7 @@ func newRollbackCmd(c helm.Interface, out io.Writer) *cobra.Command {
 	}
 
 	cmd := &cobra.Command{
-		Use:               "rollback [RELEASE]",
+		Use:               "rollback [flags] [RELEASE] [RELEASE]",
```
Comment (michelleN) [inline cmd/helm/rollback.go]: that second argument should be version number or release number

Comment (technosophos) [inline cmd/helm/rollback.go]: Yes, it should. :-(

Comment (technosophos) [inline cmd/helm/rollback.go]: Fixed
