### PR TITLE
Throw an error from jobReady() if the job exceeds its BackoffLimit

### LINKED ISSUE #9285: --wait-for-jobs does not fails if job failed
Output of `helm version`: 
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-11-25T13:19:56Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

I have this template:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: backend-tests-job
  labels:
    app-name: tests
    app-service: backend-tests
spec:
  backoffLimit: 0
  template:
    metadata:
      name: backend-tests
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}

      containers:
      - name: tests
        image: {{.Values.image.repository}}/{{ .Values.appName }}:{{ .Values.appVersion }}
        imagePullPolicy: Always
        command: ["/usr/bin/make"]
        args: ["test", "PYTEST_ARGS=${ARGS}", "VERSION=${VERSION}"]
        env:
          - name: ARGS
            value: {{ .Values.pytestArgs | quote }}
          - name: GG_VERSION
            value: {{ .Values.version | quote }}
        resources:
            {{- toYaml .Values.resources | nindent 12 }}

```

I installs it with this command:
`helm install CHART --wait-for-jobs --wait --timeout 10m`

Sometimes job failed (because of tests, yeap :) ), does not restart (because of backoffLimit: 0) and then helm just... waits. 
I think that helm should not wait if job failed without any other restarts

### PR DESCRIPTION
**Pull request by jeffrosenberg**
Closes #9285

Signed-off-by: Rosenberg, Jeff <jeff.rosenberg@icfnext.com>

**What this PR does / why we need it**:

As noted in #9285, if `--wait-for-jobs` is specified, and a job exceeds its backoff limit, Helm will always wait for the full timeout before failing, even though there is no chance of its succeeding. This PR modifies the `jobReady()` function to return an error. Based on the comments on [k8s.io/apimachinery/pkg/util/wait#PollImmediateUntil](https://github.com/kubernetes/apimachinery/blob/a644435e2c133d990b624858d9c01985d7f59adf/pkg/util/wait/wait.go#L526), it appears that returning an error should stop that function from polling.

**Special notes for your reviewer**:

I've updated the tests in `ready_test.go`, but there is no test coverage in `client_test.go` to validate that this works as expected. Ideally this would have a test in `client_test.go`, but [these comments](https://github.com/helm/helm/blob/281380f31ccb8eb0c86c84daf8bcbbd2f82dc820/pkg/kube/client_test.go#L185-L194) indicate that there haven't been tests for waits since the feature was introduced.

**If applicable**:
- [ ] this PR contains documentation
- [X] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by jeffrosenberg** [comment]
In local testing, this speeds up how quickly we fail, but not yet to the extent I'd like. This still waits for all deployments to be ready, and then once the failed job is the last thing we're waiting for, it fails immediately rather than spinning on the failed job until reaching the timeout. That's still a significant improvement, but I'd love to figure out if there's a way to fail the install immediately on job failure.

File: pkg/kube/ready.go [hunk 1]
```diff
@@ -222,16 +225,17 @@ func (c *ReadyChecker) isPodReady(pod *corev1.Pod) bool {
 	return false
 }
 
-func (c *ReadyChecker) jobReady(job *batchv1.Job) bool {
+func (c *ReadyChecker) jobReady(job *batchv1.Job) (bool, error) {
 	if job.Status.Failed > *job.Spec.BackoffLimit {
 		c.log("Job is failed: %s/%s", job.GetNamespace(), job.GetName())
-		return false
+		// If a job is failed, it can't recover, so throw an error
+		return false, fmt.Errorf("job is failed: %s/%s", job.GetNamespace(), job.GetName())
```
Comment (zonggen) [inline pkg/kube/ready.go:232]: Please make the message consistent as the `c.log("Job is failed: %s/%s", job.GetNamespace(), job.GetName())`
```suggestion
		return false, fmt.Errorf("Job is failed: %s/%s", job.GetNamespace(), job.GetName())
```

**Comment by zonggen** [comment]
> This still waits for all deployments to be ready, and then once the failed job is the last thing we're waiting for

Yes because the ResourceList ordering: https://github.com/helm/helm/blob/main/pkg/kube/wait.go#L54

I think this PR is sane and able to fix the original issue.

**Comment by jeffrosenberg** [comment]
Thanks for the review @zonggen; FYI, I've resolved the merge conflict.

**Review by joejulian — APPROVED** [review]
lgtm, but I'm not an approver.

**Comment by stuartdrennan** [comment]
End user test

[chart.zip](https://github.com/helm/helm/files/9830443/chart.zip)


Job:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "sleep(30) && print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 0
```

### Baseline Test
Released Helm version 3.9.1

```
helm install d . --wait-for-jobs --wait --debug --timeout 60s

client.go:128: [debug] creating 1 resource(s)
wait.go:48: [debug] beginning wait for 1 resources with timeout of 1m0s
ready.go:231: [debug] Job is not completed: default/pi
ready.go:231: [debug] Job is not completed: default/pi
ready.go:231: [debug] Job is not completed: default/pi
ready.go:231: [debug] Job is not completed: default/pi
ready.go:231: [debug] Job is not completed: default/pi
ready.go:231: [debug] Job is not completed: default/pi
ready.go:231: [debug] Job is not completed: default/pi
ready.go:231: [debug] Job is not completed: default/pi
ready.go:231: [debug] Job is not completed: default/pi
ready.go:231: [debug] Job is not completed: default/pi
ready.go:231: [debug] Job is not completed: default/pi
ready.go:231: [debug] Job is not completed: default/pi
ready.go:231: [debug] Job is not completed: default/pi
ready.go:231: [debug] Job is not completed: default/pi
ready.go:231: [debug] Job is not completed: default/pi
ready.go:231: [debug] Job is not completed: default/pi
ready.go:231: [debug] Job is not completed: default/pi
ready.go:231: [debug] Job is not completed: default/pi
ready.go:231: [debug] Job is not completed: default/pi
ready.go:227: [debug] Job is failed: default/pi
ready.go:227: [debug] Job is failed: default/pi
ready.go:227: [debug] Job is failed: default/pi
ready.go:227: [debug] Job is failed: default/pi
ready.go:227: [debug] Job is failed: default/pi
ready.go:227: [debug] Job is failed: default/pi
ready.go:227: [debug] Job is failed: default/pi
ready.go:227: [debug] Job is failed: default/pi
ready.go:227: [debug] Job is failed: default/pi
ready.go:227: [debug] Job is failed: default/pi
ready.go:227: [debug] Job is failed: default/pi
Error: INSTALLATION FAILED: timed out waiting for the condition
helm.go:84: [debug] timed out waiting for the condition
INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:127
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.4.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.4.0/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:255
runtime.goexit
        runtime/asm_arm64.s:1133
```

**Summary**

Job failed but Helm waited until timeout before exiting.  Not the desired response but expected.  
Same result with backoffLimit: 0 and backoffLimit: 1


### PR Test
```
install.go:192: [debug] Original chart version: ""
install.go:209: [debug] CHART PATH: /Users/sdrennan/code/tmp/gg/chart

client.go:128: [debug] creating 1 resource(s)
wait.go:66: [debug] beginning wait for 1 resources with timeout of 1m0s
ready.go:235: [debug] Job is not completed: default/pi
ready.go:235: [debug] Job is not completed: default/pi
ready.go:235: [debug] Job is not completed: default/pi
ready.go:235: [debug] Job is not completed: default/pi
ready.go:235: [debug] Job is not completed: default/pi
ready.go:235: [debug] Job is not completed: default/pi
ready.go:235: [debug] Job is not completed: default/pi
ready.go:235: [debug] Job is not completed: default/pi
ready.go:235: [debug] Job is not completed: default/pi
ready.go:235: [debug] Job is not completed: default/pi
ready.go:235: [debug] Job is not completed: default/pi
ready.go:235: [debug] Job is not completed: default/pi
ready.go:235: [debug] Job is not completed: default/pi
ready.go:235: [debug] Job is not completed: default/pi
ready.go:235: [debug] Job is not completed: default/pi
ready.go:235: [debug] Job is not completed: default/pi
ready.go:235: [debug] Job is not completed: default/pi
ready.go:235: [debug] Job is not completed: default/pi
ready.go:235: [debug] Job is not completed: default/pi
ready.go:230: [debug] Job is failed: default/pi
Error: INSTALLATION FAILED: job is failed: default/pi
helm.go:84: [debug] job is failed: default/pi
INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:141
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.5.0/command.go:872
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.5.0/command.go:990
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.5.0/command.go:918
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_arm64.s:1165
```

**Summary**

Helm exited correctly within timeout period
Same result with backoffLimit: 0 and backoffLimit: 1

**Comment by jouve** [comment]
another blocker for this PR ? 

I could help if needed :)

**Comment by armstrongli** [comment]
this PR works for me. 👍

**Comment by armstrongli** [comment]
@mattfarina , need your help on this PR?

**Comment by armstrongli** [comment]
@jouve , need your help on this PR
