### PR TITLE
Fix helm search command error on index search failures

### LINKED ISSUE #3687: search command returns no error on index search failure
It seems the search command does not return an error

https://github.com/kubernetes/helm/blob/b335bfdabf03cc6aaea9bd3e46a5fc63c932c1dd/cmd/helm/search.go#L84-L87

The tests for the search command seem to miss this (they do not use `runReleaseCases` for testing) as the tests won't fail if there are no errors when an error is expected:

https://github.com/kubernetes/helm/blob/b335bfdabf03cc6aaea9bd3e46a5fc63c932c1dd/cmd/helm/search_test.go#L104-L108

### PR DESCRIPTION
**Pull request by adshmh**
fix(helm): The search command returns error if the index search fails. This PR also refactors the tests on search command to remove some duplication. Fixes #3687 

Signed-off-by: Arash Deshmeh adeshmeh@ca.ibm.com

### CODE REVIEW

**Review by bacongobbler — APPROVED** [review]
LGTM but would love an extra pair of eyes just to be sure

**Comment by michelleN** [comment]
@bacongobbler @adshmh checking this out now

File: cmd/helm/search.go [hunk 1]
```diff
@@ -83,7 +83,7 @@ func (s *searchCmd) run(args []string) error {
 		q := strings.Join(args, " ")
 		res, err = index.Search(q, searchMaxScore, s.regexp)
 		if err != nil {
-			return nil
+			return err
```
Comment (michelleN) [inline cmd/helm/search.go]: This change makes it so that an error will return if there is an issue with parsing regex. 👍

File: cmd/helm/search_test.go [hunk 2]
```diff
@@ -17,78 +17,72 @@ limitations under the License.
...
 		{
-			name:   "search for 'alp[', expect failure to compile regexp",
-			args:   []string{"alp["},
-			flags:  []string{"--regexp"},
-			regexp: true,
-			fail:   true,
+			name:  "search for 'alp[', expect failure to compile regexp",
+			args:  []string{"alp["},
+			flags: []string{"--regexp"},
+			err:   true,
```
Comment (michelleN) [inline cmd/helm/search_test.go]: awesome 👍

**Review by michelleN — APPROVED** [review]
Looks great. Thanks @adshmh !

File: cmd/helm/search_test.go (hunk 2 above)
Comment (adshmh) [reply cmd/helm/search_test.go]: @michelleN Thank you for the review.
