### PR TITLE
Fix/bad name

### LINKED ISSUE #4873: Helm install with a bad name specified still produces resources.
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-07-26T20:40:11Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.3-eks", GitCommit:"58c199a59046dbf0a13a387d3491a39213be53df", GitTreeState:"clean", BuildDate:"2018-09-21T21:00:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Amazon EKS

When I do a helm install and add a name that doesn't work (e.g. has capital letters), the install fails but the resources still get provisioned.  Suggest that the entire install fail and no resources get created at all.  The error could also be clearer.  Here is output from the command line that clearly shows the problem (I tried to use my helm chart to create "BAD_NAME"):

```
$ kubectl get services
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.100.0.1   <none>        443/TCP   12d
$ kubectl get deployments
No resources found.
$ helm list
$ helm install ./lthoihelm --name=BAD_NAME
NAME:   BAD_NAME
Error: getting deployed release "BAD_NAME": release: "BAD_NAME" not found
$ helm list
$ kubectl get services
NAME                  TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
kubernetes            ClusterIP   10.100.0.1       <none>        443/TCP    12d
testingbets-service   ClusterIP   10.100.180.116   <none>        9999/TCP   14s
$ kubectl get deployments
NAME              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
bets-deployment   1         1         1            1           21s
```

The same thing works fine with a lower case name.  I deleted the orphaned deployment and service and then tried again:

```
$ kubectl get services
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.100.0.1   <none>        443/TCP   12d
$ kubectl get deployments
No resources found.
$ helm list
$ helm install ./lthoihelm --name=goodname
NAME:   goodname
LAST DEPLOYED: Thu Nov  1 21:37:25 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Service
NAME                 AGE
testingbets-service  0s

==> v1/Deployment
bets-deployment  0s

==> v1/Pod(related)

NAME                              READY  STATUS             RESTARTS  AGE
bets-deployment-55dc44fd8b-rccrd  0/1    ContainerCreating  0         0s
```

_Edited to add code blocks for readability_

### PR DESCRIPTION
**Pull request by jianliao82**
fix:#4873, check release name

for command helm template and helm install
when customer input invalid release name, return a error

### CODE REVIEW

File: cmd/helm/install_test.go [hunk 1]
```diff
@@ -111,9 +111,9 @@ func TestInstall(t *testing.T) {
 		{
 			name:     "install with name-template",
 			args:     []string{"testdata/testcharts/alpine"},
-			flags:    []string{"--name-template", "{{upper \"foobar\"}}"},
-			expected: "FOOBAR",
-			resp:     helm.ReleaseMock(&helm.MockReleaseOptions{Name: "FOOBAR"}),
+			flags:    []string{"--name-template", "{{lower \"FOOBAR\"}}"},
```
Comment (bacongobbler) [inline cmd/helm/install_test.go]: Would you mind adding failure cases to the bottom here? It's important that we both capture good test cases as well as the bad ones rather than removing them entirely.

```
		// Install, using a bad release name
		{
			name:  "install chart with release name using capitals",
			args:  []string{"testdata/testcharts/alpine"},
			flags: []string{"--name", "FOO"},
			err:   true,
		},
		{
			name:  "install chart with release name using periods",
			args:  []string{"testdata/testcharts/alpine"},
			flags: []string{"--name", "foo.bar"},
			err:   true,
		},
		{
			name:  "install chart with release name using underscores",
			args:  []string{"testdata/testcharts/alpine"},
			flags: []string{"--name", "foo_bar"},
			err:   true,
		},
		// Install, using a bad name-template
		{
			name:  "install with name-template",
			args:  []string{"testdata/testcharts/alpine"},
			flags: []string{"--name-template", "{{UPPER \"foobar\"}}"},
			err:   true,
		},
```

File: cmd/helm/template_test.go [hunk 2]
```diff
@@ -138,9 +138,9 @@ func TestTemplateCmd(t *testing.T) {
 		{
 			name:        "check_name_template",
 			desc:        "verify --name-template result exists",
-			args:        []string{subchart1ChartPath, "--name-template", "foobar-{{ b64enc \"abc\" }}-baz"},
```
Comment (bacongobbler) [inline cmd/helm/template_test.go]: same here; can we add a test case that demonstrates `foobar-{{ b64enc \"abc\" }}-baz` should fail rather than removing it?

**Review by bacongobbler — CHANGES_REQUESTED** [review]

**Comment by bacongobbler** [comment]
looks good to go once the tests have been addressed. Thanks @jianliao82!

File: cmd/helm/install_test.go (hunk 1 above)
Comment (jianliao82) [reply cmd/helm/install_test.go]: thanks for your advice. already added them.

File: cmd/helm/template_test.go (hunk 2 above)
Comment (jianliao82) [reply cmd/helm/template_test.go]: thanks for your advice. already added them.

**Comment by jianliao82** [comment]
@bacongobbler thanks for your review,. already update the PR, could you help to take a look at it again?

**Review by bacongobbler — APPROVED** [review]
perfect, thank you!
