### PR TITLE
fix: clear the discovery cache after CRDs are installed

### LINKED ISSUE #6316: Helm v3 beta -- Wait for CRDs to be created
When deploying CRDs with Helm v3, the rest of the chart deployment occurs _immediately_ after a CRD is installed.  This can cause the chart deployment to fail if the CRDs are not yet available.  Helm should wait until the CRD is deployed before continuing with the chart.

### PR DESCRIPTION
**Pull request by technosophos**
**What this PR does / why we need it**:
This fixes a bug in which CRD instances could not be created in the same chart as the CRDs themselves. This invalidates the local discovery cache and forces a round-trip discovery operation with the Kubernetes API server.

**Special notes for your reviewer**:

Closes #6316 

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Comment by hickeyma** [comment]
@thequailman can you test if this fixes the issue?

**Comment by karuppiah7890** [comment]
I'm wondering if it's possible to write a failing test for the issue and then pass it with this PR

**Review by thomastaylor312 — CHANGES_REQUESTED** [review]
I can't get this to work for me and I think I know why, but am not sure how to fix it. We should pair and see what we can come up with

**Comment by technosophos** [comment]
Looks like were two issues with the earlier draft of this patch:

- The capabilities cache gets generated before the CRDs are installed. I reversed the order of this.
- Some clusters take longer to register CRDs. I was testing locally with Kind, which is fast. But some take a second or two.

The following script is what I have been using for testing:

```bash
BASPATH=/Users/technosophos/Code/Go/src/helm.sh/helm
HELM=$BASPATH/bin/helm
CHART=$BASPATH/_scratch/test-0.1.0.tgz

# Build a fresh Helm
echo "Building Helm"
cd $BASPATH && make build

echo "Cleaning environment"
# Clear all CRDs
kubectl delete crds --all
# Clear cache
rm -r /Users/technosophos/.kube/cache/discovery/127.0.0.1_*

echo "Running test"
# Run a command that forces discovery client to regen
# Install Helm chart
$HELM install --debug test1 $CHART

echo "Deleting helm install"
$HELM delete test1
```

File: pkg/action/install.go [hunk 1]
```diff
@@ -111,6 +111,49 @@ func (i *Install) Run(chrt *chart.Chart, vals map[string]interface{}) (*release.
...
+			// Invalidate the local cache.
+			if discoveryClient, err := i.cfg.RESTClientGetter.ToDiscoveryClient(); err != nil {
+				// On error, we don't want to bail out, since this is unlikely
+				// to impact the majority of charts.
+				i.cfg.Log("Could not clear the discovery cache: %s", err)
+			} else {
+				i.cfg.Log("Clearing discovery cache")
+				discoveryClient.Invalidate()
+				// Give time for the CRD to be recognized.
+				time.Sleep(5 * time.Second)
```
Comment (thomastaylor312) [inline pkg/action/install.go]: We should probably clean up and reuse the code found here in Helm 2 so we aren't just sleeping and hoping it works: https://github.com/helm/helm/blob/3ed073b2e0c37dd5c994562d6fe8e04b5f3609eb/pkg/kube/client.go#L584-L612

**Review by thomastaylor312 — COMMENTED** [review]
I think we already have some code we can copy paste instead of sleeping to wait for CRDs to reach an established state

File: pkg/action/install.go (hunk 1 above)
Comment (technosophos) [reply pkg/action/install.go]: I am adding support to Wait() for CRDs, and then just using that. It has some hidden advantages for if people try to sneak non-CRD things into the CRDs() directory. But _sssssh... don't tell them that they can do this_.

Comment (thomastaylor312) [reply pkg/action/install.go]: tenor-138232708

Comment (technosophos) [reply pkg/action/install.go]: @thomastaylor312 Okay, this is now done. We're using an updated version of the Wait logic to watch for the CRD to become available.

File: pkg/kube/wait.go [hunk 2]
```diff
@@ -46,6 +48,9 @@ type waiter struct {
 // until all are ready or a timeout is reached
 func (w *waiter) waitForResources(created ResourceList) error {
 	w.log("beginning wait for %d resources with timeout of %v", len(created), w.timeout)
+	if err := apiextv1beta1.AddToScheme(scheme.Scheme); err != nil {
```
Comment (technosophos) [inline pkg/kube/wait.go]: Adding CRDs to the globally shared Scheme (Yay, Singletons!) is probably best done elsewhere. Any idea where?

File: pkg/action/install.go [hunk 3]
```diff
@@ -103,6 +103,50 @@ func NewInstall(cfg *Configuration) *Install {
...
+				continue
+			}
+			return errors.Wrapf(err, "failed to instal CRD %s", obj.Name)
+		}
+
+		// Invalidate the local cache.
+		if discoveryClient, err := i.cfg.RESTClientGetter.ToDiscoveryClient(); err != nil {
+			// On error, we don't want to bail out, since this is unlikely
+			// to impact the majority of charts.
+			i.cfg.Log("Could not clear the discovery cache: %s", err)
```
Comment (thomastaylor312) [inline pkg/action/install.go]: So I was thinking about this some more. I think we actually _do_ want to bail out here. If we got into this block, the user was meaning to install CRDs and we don't want their release to just fail on them. What do you think?

File: pkg/kube/client.go [hunk 4]
```diff
@@ -55,6 +58,10 @@ func New(getter genericclioptions.RESTClientGetter) *Client {
 	if getter == nil {
 		getter = genericclioptions.NewConfigFlags(true)
 	}
+	if err := apiextv1beta1.AddToScheme(scheme.Scheme); err != nil {
+		// This should never happen.
```
Comment (thomastaylor312) [inline pkg/kube/client.go]: Famous last words... 😉

File: pkg/kube/client.go [hunk 5]
```diff
@@ -55,6 +58,10 @@ func New(getter genericclioptions.RESTClientGetter) *Client {
 	if getter == nil {
 		getter = genericclioptions.NewConfigFlags(true)
 	}
+	if err := apiextv1beta1.AddToScheme(scheme.Scheme); err != nil {
```
Comment (thomastaylor312) [inline pkg/kube/client.go]: We should add a comment here so people don't have to do the same research you did

File: pkg/kube/wait.go [hunk 6]
```diff
@@ -257,6 +270,26 @@ func (w *waiter) daemonSetReady(ds *appsv1.DaemonSet) bool {
...
+	for _, cond := range crd.Status.Conditions {
+		switch cond.Type {
+		case apiextv1beta1.Established:
+			if cond.Status == apiextv1beta1.ConditionTrue {
+				return true
+			}
+		case apiextv1beta1.NamesAccepted:
+			if cond.Status == apiextv1beta1.ConditionFalse {
+				// This indicates a naming conflict, but it's probably not the
+				// job of this function to faile because of that. Instead,
```
Comment (thomastaylor312) [inline pkg/kube/wait.go]: Spelling nit: s/faile/fail

**Review by thomastaylor312 — CHANGES_REQUESTED** [review]
Just a few small changes that I found on this second pass

File: pkg/action/install.go (hunk 3 above)
Comment (thomastaylor312) [reply pkg/action/install.go]: Oh and also bail out on a failed wait

File: pkg/action/install.go [hunk 7]
```diff
@@ -103,6 +103,50 @@ func NewInstall(cfg *Configuration) *Install {
...
+		} else {
+			i.cfg.Log("Clearing discovery cache")
+			discoveryClient.Invalidate()
```
Comment (thomastaylor312) [inline pkg/action/install.go]: I was looking through this one more time and I think we should do the cache invalidation at the very end, outside of the for loop. When I looked into the code, I think the discovery client calls the api multiple times for each api group, meaning that if someone installs 5-10 CRDs, they will be calling their API hundreds of times

Comment (thomastaylor312) [reply pkg/action/install.go]: Source: https://github.com/kubernetes/cli-runtime/blob/9d670f2021f41f32ed762a6ddbc1c3ac7c441126/pkg/genericclioptions/config_flags.go#L222-L225

Comment (technosophos) [reply pkg/action/install.go]: So originally I was doing this so that the crds folder could have things that depended on each other. And this operates _per file_, not per CRD. But I'll switch it.

File: pkg/action/install.go (hunk 3 above)
Comment (technosophos) [reply pkg/action/install.go]: I don't like the idea of failing on transient errors that are unlikely to impact the user. It seems wrong to me to take something that is not fatal (a cleared cache, a wait that is likely not going to take long anyway) and then require the user to take action.

However, I don't care enough to drag on this PR longer, so I will change it.

**Comment by technosophos** [comment]
Please re-review.

**Review by thomastaylor312 — APPROVED** [review]
LGTM
