### PR TITLE
fix(helm):Fix dependency aliaes not working

### LINKED ISSUE #2794: Dependency aliases not working with semver logic
Issue found on v2.5.1

The alias functionality only works when a hardcoded version is used. Any use of semver logic causes unexpected behavior.

* All aliased dependencies with semver logic are ignored.
* If all aliased dependencies for a chart are ignored, then the base chart name is used

Expected behavior:

* Aliased dependencies should handle semver logic identically to non-aliased dependencies.

Example 1
---
All aliased dependencies use semver logic.

Given:

```
dependencies:
  - name: mariadb
    repository: https://kubernetes-charts.storage.googleapis.com
    version: ~> 0.7.X
    alias: foo
  - name: mariadb
    repository: https://kubernetes-charts.storage.googleapis.com
    version: ~> 0.7.X
    alias: bar
  - name: mariadb
    repository: https://kubernetes-charts.storage.googleapis.com
    version: ~> 0.7.X
    alias: baz
```

Produces

```
# Source: requirement-test/charts/mariadb/templates/secrets.yaml
# Source: requirement-test/charts/mariadb/templates/configmap.yaml
# Source: requirement-test/charts/mariadb/templates/pvc.yaml
# Source: requirement-test/charts/mariadb/templates/svc.yaml
# Source: requirement-test/charts/mariadb/templates/deployment.yaml
```
Example 2
---
Only one aliased dependency uses hardcoded version logic.

Given:

```
dependencies:
  - name: mariadb
    repository: https://kubernetes-charts.storage.googleapis.com
    version: ~> 0.7.X
    alias: foo
  - name: mariadb
    repository: https://kubernetes-charts.storage.googleapis.com
    version: ~> 0.7.X
    alias: bar
  - name: mariadb
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 0.7.0
    alias: baz
```

Produces:

```
# Source: requirement-test/charts/baz/templates/secrets.yaml
# Source: requirement-test/charts/baz/templates/configmap.yaml
# Source: requirement-test/charts/baz/templates/pvc.yaml
# Source: requirement-test/charts/baz/templates/svc.yaml
# Source: requirement-test/charts/baz/templates/deployment.yaml
```
Example 3
---
Mix of semver logic and hard coded versions.

Given:

```
dependencies:
  - name: mariadb
    repository: https://kubernetes-charts.storage.googleapis.com
    version: ~> 0.7.X
    alias: foo
  - name: mariadb
    repository: https://kubernetes-charts.storage.googleapis.com
    version: ~> 0.7.X
    alias: bar
  - name: mariadb
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 0.7.0
    alias: baz
  - name: mariadb
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 0.7.0
    alias: fizz
```

Produces:

```
# Source: requirement-test/charts/fizz/templates/secrets.yaml
# Source: requirement-test/charts/baz/templates/secrets.yaml
# Source: requirement-test/charts/fizz/templates/configmap.yaml
# Source: requirement-test/charts/baz/templates/configmap.yaml
# Source: requirement-test/charts/fizz/templates/pvc.yaml
# Source: requirement-test/charts/baz/templates/pvc.yaml
# Source: requirement-test/charts/baz/templates/svc.yaml
# Source: requirement-test/charts/fizz/templates/svc.yaml
# Source: requirement-test/charts/fizz/templates/deployment.yaml
# Source: requirement-test/charts/baz/templates/deployment.yaml
```

### PR DESCRIPTION
**Pull request by llsheldon**
The alias functionality only works when a hardcoded version
is used. Any use of semver logic causes unexpected behavior.
I use version.IsCompatibleRange to check the dependency version.

Closes #2794

### CODE REVIEW

File: pkg/chartutil/requirements.go [hunk 1]
```diff
@@ -230,7 +231,7 @@ func getAliasDependency(charts []*chart.Chart, aliasChart *Dependency) *chart.Ch
 		if existingChart.Metadata.Name != aliasChart.Name {
 			continue
 		}
-		if existingChart.Metadata.Version != aliasChart.Version {
+		if !version.IsCompatibleRange(aliasChart.Version, existingChart.Metadata.Version) {
```
Comment (bacongobbler) [inline pkg/chartutil/requirements.go]: would you mind writing up a unit test to cover this?

File: pkg/chartutil/requirements.go [hunk 2]
```diff
@@ -266,7 +267,7 @@ func ProcessRequirementsEnabled(c *chart.Chart, v *chart.Config) error {
 	for _, existingDependency := range c.Dependencies {
 		var dependencyFound bool
 		for _, req := range reqs.Dependencies {
-			if existingDependency.Metadata.Name == req.Name && existingDependency.Metadata.Version == req.Version {
+			if existingDependency.Metadata.Name == req.Name && version.IsCompatibleRange(req.Version, existingDependency.Metadata.Version) {
```
Comment (bacongobbler) [inline pkg/chartutil/requirements.go]: same here. Would you mind writing up a unit test to cover this?

**Review by bacongobbler — CHANGES_REQUESTED** [review]

File: pkg/chartutil/requirements.go (hunk 1 above)
Comment (llsheldon) [reply pkg/chartutil/requirements.go]: got it,I have added it,please review it @bacongobbler

File: pkg/chartutil/requirements.go (hunk 2 above)
Comment (llsheldon) [reply pkg/chartutil/requirements.go]: I have added the unit test,please review it@bacongobbler

Comment (llsheldon) [reply pkg/chartutil/requirements.go]: I have added the unit test,please review it

**Comment by llsheldon** [comment]
would you please review it again,thanks a lot @bacongobbler

**Review by bacongobbler — APPROVED** [review]
