### PR TITLE
[v3] Introducing tests for chartutils/errors.go

### LINKED ISSUE #6673: Stack overflow in pkg/chartutil/errors.go
`pkg/chartutil/errors.go` has a recursion bug which results in a stack overflow when trying to serialize the value of the error:

https://github.com/helm/helm/blob/dev-v3/pkg/chartutil/errors.go#L26

If you attempt to render one of these Errors, you'll get a stack overflow. I have proposed a unit test in #6672 which demonstrates the stack overflow.

Excerpt of logs:

```
goroutine 179 [running]:
runtime.heapBitsSetType(0xc006dd8750, 0xd0, 0xc8, 0x110f540)
	/usr/local/go/src/runtime/mbitmap.go:938 +0xa4e fp=0xc02055a3a0 sp=0xc02055a398 pc=0x41823e
runtime.mallocgc(0xd0, 0x110f540, 0x1, 0x0)
	/usr/local/go/src/runtime/malloc.go:1052 +0x53e fp=0xc02055a440 sp=0xc02055a3a0 pc=0x40dfde
runtime.newobject(0x110f540, 0xc02055a518)
	/usr/local/go/src/runtime/malloc.go:1151 +0x38 fp=0xc02055a470 sp=0xc02055a440 pc=0x40e628
fmt.glob..func1(0x1b25100, 0x0)
	/usr/local/go/src/fmt/print.go:132 +0x2d fp=0xc02055a490 sp=0xc02055a470 pc=0x4e372d
sync.(*Pool).Get(0x1b25100, 0xc000177c00, 0x7fdec8505008)
	/usr/local/go/src/sync/pool.go:148 +0xa6 fp=0xc02055a4d8 sp=0xc02055a490 pc=0x46e6a6
fmt.newPrinter(0x0)
	/usr/local/go/src/fmt/print.go:137 +0x31 fp=0xc02055a500 sp=0xc02055a4d8 pc=0x4d5471
fmt.Sprintf(0x119495e, 0x11, 0xc02055a590, 0x1, 0x1, 0x10717c0, 0x42fb0a)
	/usr/local/go/src/fmt/print.go:218 +0x26 fp=0xc02055a558 sp=0xc02055a500 pc=0x4d5a36
helm.sh/helm/v3/pkg/chartutil.ErrNoTable.Error(...)
	/home/circleci/helm.sh/helm/pkg/chartutil/errors.go:26
helm.sh/helm/v3/pkg/chartutil.(*ErrNoTable).Error(0xc006dc3af0, 0x104ea40, 0xc006dc3af0)
	<autogenerated>:1 +0xb4 fp=0xc02055a5b0 sp=0xc02055a558 pc=0xf95274
fmt.(*pp).handleMethods(0xc006dd8680, 0x71, 0xc02055a801)
	/usr/local/go/src/fmt/print.go:624 +0x1db fp=0xc02055a7c0 sp=0xc02055a5b0 pc=0x4d8aeb
fmt.(*pp).printArg(0xc006dd8680, 0x104ea40, 0xc006dc3af0, 0xc000000071)
	/usr/local/go/src/fmt/print.go:713 +0x206 fp=0xc02055a858 sp=0xc02055a7c0 pc=0x4d91d6
fmt.(*pp).doPrintf(0xc006dd8680, 0x119495e, 0x11, 0xc02055a9d0, 0x1, 0x1)
	/usr/local/go/src/fmt/print.go:1030 +0x15b fp=0xc02055a940 sp=0xc02055a858 pc=0x4dcb9b
fmt.Sprintf(0x119495e, 0x11, 0xc02055a9d0, 0x1, 0x1, 0x10717c0, 0x42fb0a)
	/usr/local/go/src/fmt/print.go:219 +0x66 fp=0xc02055a998 sp=0xc02055a940 pc=0x4d5a76
helm.sh/helm/v3/pkg/chartutil.ErrNoTable.Error(...)
	/home/circleci/helm.sh/helm/pkg/chartutil/errors.go:26
helm.sh/helm/v3/pkg/chartutil.(*ErrNoTable).Error(0xc006dc3ae0, 0x104ea40, 0xc006dc3ae0)
	<autogenerated>:1 +0xb4 fp=0xc02055a9f0 sp=0xc02055a998 pc=0xf95274
fmt.(*pp).handleMethods(0xc006dd85b0, 0x71, 0xc02055ac01)
	/usr/local/go/src/fmt/print.go:624 +0x1db fp=0xc02055ac00 sp=0xc02055a9f0 pc=0x4d8aeb
fmt.(*pp).printArg(0xc006dd85b0, 0x104ea40, 0xc006dc3ae0, 0xc000000071)
	/usr/local/go/src/fmt/print.go:713 +0x206 fp=0xc02055ac98 sp=0xc02055ac00 pc=0x4d91d6
fmt.(*pp).doPrintf(0xc006dd85b0, 0x119495e, 0x11, 0xc02055ae10, 0x1, 0x1)
	/usr/local/go/src/fmt/print.go:1030 +0x15b fp=0xc02055ad80 sp=0xc02055ac98 pc=0x4dcb9b
fmt.Sprintf(0x119495e, 0x11, 0xc02055ae10, 0x1, 0x1, 0x10717c0, 0x42fb0a)
	/usr/local/go/src/fmt/print.go:219 +0x66 fp=0xc02055add8 sp=0xc02055ad80 pc=0x4d5a76
helm.sh/helm/v3/pkg/chartutil.ErrNoTable.Error(...)
	/home/circleci/helm.sh/helm/pkg/chartutil/errors.go:26
```

Output of `helm version`:
dev-v3 (Beta 4)

Output of `kubectl version`:
N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
N/A

### PR DESCRIPTION
**Pull request by kenperkins**
- Should panic on string recursion error

**What this PR does / why we need it**:
A stack overflow exists when the `ErrNoTable` or `ErrNoValue` types in `pkg/chartutil` are serialized to strings. This PR introduces failing tests which will be address as a second commit to this PR with a small refactor to not have the string recursion error.

Fixes #6673 

Signed-off-by: Ken Perkins <ken@perkins.io>

### CODE REVIEW

**Comment by kenperkins** [comment]
As expected, this test successfully fails in CI:

```
	/usr/local/go/src/testing/testing.go:960 +0x350

goroutine 1 [chan receive]:
testing.(*T).Run(0xc00022ce00, 0x119e92f, 0x1b, 0x121ff08, 0x484c01)
	/usr/local/go/src/testing/testing.go:961 +0x377
testing.runTests.func1(0xc00022c500)
	/usr/local/go/src/testing/testing.go:1202 +0x78
testing.tRunner(0xc00022c500, 0xc000305d88)
	/usr/local/go/src/testing/testing.go:909 +0xc9
testing.runTests(0xc0002a4660, 0x1b2bac0, 0x23, 0x23, 0x0)
	/usr/local/go/src/testing/testing.go:1200 +0x2a7
testing.(*M).Run(0xc00026f400, 0x0)
	/usr/local/go/src/testing/testing.go:1117 +0x176
main.main()
	_testmain.go:184 +0x1c1

goroutine 19 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x1b3a5e0)
	/go/pkg/mod/k8s.io/klog@v0.4.0/klog.go:1018 +0x8b
created by k8s.io/klog.init.0
	/go/pkg/mod/k8s.io/klog@v0.4.0/klog.go:404 +0x6c
FAIL	helm.sh/helm/v3/pkg/chartutil	3.157s
FAIL
make: *** [Makefile:81: test-coverage] Error 1
```

**Comment by kenperkins** [comment]
When/if the Helm team acknowledges that this should be fixed, I can push a commit that addresses the failed tests through a small reworking of the `ErrNoTable` and `ErrNoValue` types and commensurate calls in `pkg/chartutil/values.go`.

**Comment by kenperkins** [comment]
This is now ready for review.

File: pkg/chartutil/errors.go [hunk 1]
```diff
@@ -21,11 +21,17 @@ import (
 )
 
 // ErrNoTable indicates that a chart does not have a matching table.
-type ErrNoTable string
+type ErrNoTable struct {
+	Key string
+}
 
-func (e ErrNoTable) Error() string { return fmt.Sprintf("%q is not a table", e) }
+// type ErrNoTable string
```
Comment (bacongobbler) [inline pkg/chartutil/errors.go]: would you mind removing this comment?

File: pkg/chartutil/errors_test.go [hunk 2]
```diff
@@ -0,0 +1,37 @@
+package chartutil
+
+/*
```
Comment (bacongobbler) [inline pkg/chartutil/errors_test.go]: typically, the copyright goes before the package declaration (see errors.go). Would you mind switching this around?

**Review by bacongobbler — CHANGES_REQUESTED** [review]
code looks good to me! Just a few changes here and there before I approve.

File: pkg/chartutil/errors.go (hunk 1 above)
Comment (kenperkins) [reply pkg/chartutil/errors.go]: Whoops.

File: pkg/chartutil/errors_test.go (hunk 2 above)
Comment (kenperkins) [reply pkg/chartutil/errors_test.go]: Another whoops. I thought I had it at the top.

**Review by bacongobbler — APPROVED** [review]
This is looking much better. LGTM! I'd like to get another maintainer to have a look at this before merging to make sure this breaking change to the API makes sense. Thanks for writing these tests!

**Review by hickeyma — APPROVED** [review]
LGTM, thanks @kenperkins

**Comment by hickeyma** [comment]
Good to merge when you are ready @bacongobbler

**Comment by kenperkins** [comment]
Thanks @hickeyma @bacongobbler what does the timing look like for Beta 5? Looking at short term remedies in our usage of helm v3.

**Comment by bacongobbler** [comment]
within the next few business days. Probably a week out at this point.
