### PR TITLE
fix(lint): Return non-zero exit status when lint errors present

### LINKED ISSUE #906: lint: return error status code if linter returns errors
Currently the linter doesn't return with a non-zero exit status when there are errors, so there is not an easy way to determine if the linter failed programmatically.

Later we may want to consider extending the linter with a flag to determine which severity level to error on.

### PR DESCRIPTION
**Pull request by prydonius**
closes #906

### CODE REVIEW

File: cmd/helm/lint.go [hunk 1]
```diff
@@ -60,14 +61,20 @@ func lintCmd(cmd *cobra.Command, args []string) error {
 		return errLintNoChart
 	}
 
-	issues := lint.All(path)
+	linter := lint.All(path)
 
-	if len(issues) == 0 {
+	if len(linter.Messages) == 0 {
 		fmt.Println("Lint OK")
```
Comment (migmartri) [inline cmd/helm/lint.go]: Even though this code works since `linter.HighestSeverity` is set to 0 by default and now we have hardcoded `ErrorSev`, I'd return here just to make it clear.

Comment (prydonius) [inline cmd/helm/lint.go]: :+1:

File: cmd/helm/lint.go [hunk 2]
```diff
@@ -60,14 +61,21 @@ func lintCmd(cmd *cobra.Command, args []string) error {
...
 	}
 
-	for _, i := range issues {
+	for _, i := range linter.Messages {
 		fmt.Printf("%s\n", i)
 	}
+
+	if linter.HighestSeverity == support.ErrorSev {
+		fmt.Println("Lint failed")
+		os.Exit(1)
```
Comment (technosophos) [inline cmd/helm/lint.go]: If you `return errors.New("lint failed")`, that will automatically `os.Exit(1)` for you, but it gives any of cobra's post-command hooks a chance to run first.

**Comment by technosophos** [comment]
Other than that one thing with the `return` in the top-level lint command, all looks good to me.

File: cmd/helm/lint.go (hunk 2 above)
Comment (prydonius) [inline cmd/helm/lint.go]: The thing I didn't like about returning an error is that Cobra outputs `Error: Lint failed` instead of just `Lint failed`. Is there anyway to stop it from adding that prefix?

Though the prefix is not a big deal, so we can just do that if you would prefer.

**Comment by prydonius** [comment]
@technosophos I already added the early `return` and force pushed, in case you didn't see it

File: cmd/helm/lint.go (hunk 2 above)
Comment (michelleN) [inline cmd/helm/lint.go]: @prydonius There is. Have you tried changing 'RunE' to 'Run' cobra command definition for the lint command (line 44)?

Comment (prydonius) [inline cmd/helm/lint.go]: @michelleN I think with `Run` you cannot return an error, so I'd have to keep the Println and os.Exit(1)

File: cmd/helm/lint.go [hunk 3]
```diff
@@ -92,15 +94,20 @@ func lintChart(path string) error {
...
+		return nil
 	}
 
-	for _, i := range issues {
+	for _, i := range linter.Messages {
 		fmt.Printf("%s\n", i)
 	}
 
+	if linter.HighestSeverity == support.ErrorSev {
+		return errLintFailed
```
Comment (prydonius) [inline cmd/helm/lint.go]: @technosophos @michelleN: decided to just return the error, and let Cobra print it as `Error: lint failed`

**Comment by technosophos** [comment]
Looks good to me! @prydonius, you should be able to `Merge pull request`. If not, tell me.
