### PR TITLE
fix(helm): fix 'helm dep up' to fetch by URL

### LINKED ISSUE #1845: helm dep update fails to download chart
In the latest canary build, `helm dep update` is broken, failing to download the chart.

cc @viglesiasce

```
$ helm dep update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
    Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Downloading redis from repo https://kubernetes-charts.storage.googleapis.com/
Error: could not download https://kubernetes-charts.storage.googleapis.com/redis-0.4.2.tgz: repo with URL https://kubernetes-charts.storage.googleapis.com not found
```

### LINKED ISSUE #1846: helm dep update ignores requirements
In the latest canary build, I'm seeing a strange issue where the version requirements for dependencies are seemingly ignored, and the latest version is downloaded.

For example, the Spinnaker chart has the following requirements:

```
$ cat requirements.yaml
dependencies:
- name: redis
  version: 0.4.1
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: minio
  version: 0.0.1
  repository: https://kubernetes-charts.storage.googleapis.com/

$ cat requirements.lock
dependencies:
- name: redis
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 0.4.1
- name: minio
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 0.0.1
digest: sha256:88263790242231f7d304c983a911b347490897c6afc377e81057a3a4a9689fd7
generated: 2017-01-20T15:53:10.721275826-08:00
```

After running `helm dep update`, the requirements stay the same, but the charts fetched have newer versions:

```
$ helm dep update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Downloading redis from repo https://kubernetes-charts.storage.googleapis.com/
Downloading minio from repo https://kubernetes-charts.storage.googleapis.com/

$ ls charts/
minio-0.0.2.tgz redis-0.4.2.tgz
```

cc @viglesiasce

### PR DESCRIPTION
**Pull request by technosophos**
A regression was introduced which required chart download URLs have the
same URL prefix as the chart repo that referenced them. A second
regression transformed that URL into a request for the latest version of
that chart, sidestepping semver constraints.

This fix closes both issues, which were present in the same function.

Closes #1845
Closes #1846

### CODE REVIEW

File: cmd/helm/downloader/chart_downloader.go [hunk 1]
```diff
@@ -125,11 +137,11 @@ func (c *ChartDownloader) DownloadTo(ref, version, dest string) (string, *proven
...
 // A version is a SemVer string (1.2.3-beta.1+f334a6789).
 //
-// 	- For fully qualified URLs, the version will be ignored (since URLs aren't versioned)
+//	- For fully qualified URLs, the version will be ignored (since URLs aren't versioned)
 //	- For a chart reference
 //		* If version is non-empty, this will return the URL for that version
 //		* If version is empty, this will return the URL for the latest version
-// 		* If no version can be found, an error is returned
+//		* If no version can be found, an error is returned
 func (c *ChartDownloader) ResolveChartVersion(ref, version string) (*url.URL, *repo.ChartRepository, error) {
```
Comment (technosophos) [inline cmd/helm/downloader/chart_downloader.go]: @adamreese I feel like maybe we should change the return value from a `*repo.ChartRepository` to a `repo.Getter`, since what this function is really intended to to do is resolve a reference to a downloadable unit.

The main issue with the bug I am resolving is that at some point someone assumed that every chart URL _must_ be in a known repo. This method signature matches that assumption, but really it should be saying "here is the URL and a client to use to download that URL".

Thoughts? Or should I just leave it?

File: cmd/helm/downloader/chart_downloader.go [hunk 2]
```diff
@@ -264,11 +276,48 @@ func pickChartRepositoryConfigByName(name string, cfgs []*repo.Entry) (*repo.Ent
...
+//
+// Technically, the fact that a URL is not found in a repo is not a failure indication.
+// Charts are not required to be included in an index before they are valid. So
+// be mindful of this case.
+//
+// The same URL can technically exist in two or more repositories. This algorithm
+// will return the first one it finds. Order is determined by the order of repositories
+// in the repositories.yaml file.
+func (c *ChartDownloader) scanReposForURL(u string, rf *repo.RepoFile) (*repo.Entry, error) {
+	// FIXME: This is far from optimal. Larger installations and index files will
```
Comment (thomastaylor312) [inline cmd/helm/downloader/chart_downloader.go]: Do we have an issue open for this FIXME? It might be a good idea to have one so we don't forget to make this better 😄

**Review by thomastaylor312 — APPROVED** [review]
Just one small, non blocking comment, but this LGTM. As a note, I was unable to reproduce #1845 with master, so I cannot 100% confirm that it fixes that specific bug, but the behavior as I tested things all seems correct.

**Comment by thomastaylor312** [comment]
@technosophos Would you still like @adamreese to review before I mark this LGTM?

File: cmd/helm/downloader/chart_downloader.go (hunk 2 above)
Comment (technosophos) [inline cmd/helm/downloader/chart_downloader.go]: Added #1904

**Comment by technosophos** [comment]
@thomastaylor312 I'll ask him. I did have a chance to talk through the major API change with him the other day.

**Review by adamreese — APPROVED** [review]

**Comment by prydonius** [comment]
LGTM and confirmed that this fixes #1846. #1845 is more difficult to repro.
