### PR TITLE
Fix goroutine leak in perform

### LINKED ISSUE #11871: why are  many goroutines got stuck  at batchPerform
Output of `helm version`:
helm v3.9.0 

I use helm sdk(v3.9.0) in my operator to CRUD charts,  I find the operator's memory is growing .  I use pprof to detact this problem. Finally, I find many goroutines are got stuck at batchPerform()

image

image

Can any one help me? thanks

### PR DESCRIPTION
**Pull request by willzgli**
**What this PR does / why we need it**:
 the  function perform()  shoud wait all goroutines  created in  function batchPeform finish  to avoid goroutine leak, 

closes #11871
**Special notes for your reviewer**:
@gjenkins8 @joejulian please give some comments asap, thanks  a lot

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

**Review by gjenkins8 — APPROVED** [review]
LGTM, looks to be a (minimal) fix to the bug/issue (not a maintainer, will need maintainer review).

Overall, the code here could be improved. It isn't ideal how `perform`/`batchPerform` implement scatter/gather ad-hoc, rather than relying on a library primitive (which gets the details like error handling right). But a minimal fix to the existing code is first is fine.

File: pkg/kube/client.go [hunk 1]
```diff
@@ -542,9 +543,12 @@ func perform(infos ResourceList, fn func(*resource.Info) error) error {
 	for range infos {
 		err := <-errs
 		if err != nil {
-			return err
+			errList = append(errList, err)
 		}
 	}
+	if errList != nil {
+		return errList[0]
```
Comment (TerryHowe) [inline pkg/kube/client.go:550]: Why would you save all the errors and just use the first?

Comment (willzgli) [reply pkg/kube/client.go:550]: HI, Howe,  I don't find a proper way to keep the return type not be changed and  return all the errors. I think the import thing is avoid gorotine leak here. If you have other ideas, please tell me,thanks.

Comment (TerryHowe) [reply pkg/kube/client.go:550]: `var lastError error` and just return it instead of `return nil`

Comment (willzgli) [reply pkg/kube/client.go:550]: yes, use lastError looks good, thanks.

**Review by TerryHowe — APPROVED** [review]

**Comment by willzgli** [comment]
@mattfarina  why the test case TestInstallRelease fails, I run the test case locally, it passed.

**Comment by willzgli** [comment]
@mattfarina  why the test case TestInstallRelease fails( ref Test build  log line 1962), I run the test case locally, it passed.

File: pkg/kube/client.go [hunk 2]
```diff
@@ -532,6 +532,7 @@ func (c *Client) WatchUntilReady(resources ResourceList, timeout time.Duration)
 }
 
 func perform(infos ResourceList, fn func(*resource.Info) error) error {
+	var lastError error
```
Comment (mattfarina) [inline pkg/kube/client.go:535]: Did you think about using a multi-error to capture all of them and return all of them?

**Comment by mattfarina** [comment]
@willzgli I think it was a CI flake. Problem seems to be gone after I re-ran the job.

File: pkg/kube/client.go (hunk 2 above)
Comment (willzgli) [reply pkg/kube/client.go:535]: yeah , I searched two packages 
1. https://github.com/uber-go/multierr
2. https://github.com/hashicorp/go-multierror
But both of them are not active recently, and I am not sure which is better.   Do you have any suggestion to use which package ? or is there a new famous package ?

Comment (willzgli) [reply pkg/kube/client.go]: @mattfarina  please review again

**Review by mattfarina — APPROVED** [review]

**Comment by mattfarina** [comment]
Note, this needs a second maintainer to approve before it can be merged.

File: go.mod [hunk 3]
```diff
@@ -17,6 +17,7 @@ require (
 	github.com/gobwas/glob v0.2.3
 	github.com/gofrs/flock v0.8.1
 	github.com/gosuri/uitable v0.0.4
+	github.com/hashicorp/go-multierror v1.1.1
```
[the remark this answers is not in the document]
Comment (hiddeco) [reply go.mod:20]: With the built-in multi-error support in Go 1.20, it might be an idea to put a `// TODO` somewhere once the version in `go.mod` allows to do so. Which won't happen with #11896, but support for `1.19` should end in [~5 months](https://endoflife.date/go).

**Review by hiddeco — APPROVED** [review]
Not a maintainer, but quite familiar with the internals and this looks OK to me.

File: go.mod (hunk 3 above)
[the remark this answers is not in the document]
Comment (wujunwei) [reply go.mod:20]: I don't think it's necessary to introduce a new library, we can use`k8s.io/apimachinery/pkg/util/errors.NewAggregate([]error)` to aggregate errors, be consistent with the behavior (incorrect format) of Kubernetes incidentally

[the remark this answers is not in the document]
Comment (mattfarina) [reply go.mod:20]: What's happening here is fine for now.

**Review by sabre1041 — APPROVED** [review]
LGTM
